### ISSUE TITLE
Hit a wall

### ISSUE THREAD

**Issue by sparkerino** [HenriquesLab/ZeroCostDL4Mic#1]
I found a few issues with the wiki compared to Supp Video 1, and I am unable to move past Step 3 in trying to set the paths to use Noise2VOID.

In section 1.2, it says "Click on "Files" site on the right. Refresh the site. Your Google Drive folder should now be available here as "drive"." I couldn't figure this out until watching the video and saw that the mounted Google Drive files can be accessed on the left by leaving the table of contents and clicking on the file folder icon. Just a typo, but the video is much clearer than the wiki

At Step 4, I am stuck (see screenshots). My drive is mounted, and I think I've set the paths correctly, but I cannot move past because of the error given in the screenshot

This is using Safari on Mac OS Catalina 10.15.3. I'll give it a shot on Chrome and see if that browser behaves

<img width="1049" alt="Screen Shot 2020-03-21 at 12 01 08 AM" src="https://user-images.githubusercontent.com/30428353/77221633-7d0aed80-6b08-11ea-94ce-b1a2262182c5.png">
<img width="1058" alt="Screen Shot 2020-03-21 at 12 01 17 AM" src="https://user-images.githubusercontent.com/30428353/77221634-7da38400-6b08-11ea-8de4-cd0a5018c7a3.png">

**Comment by sparkerino** [comment]
Same issue in Chrome

**Comment by guijacquemet** [comment]
Hi,
Many thanks for reaching out ! It looks like it could be an issue with the type of data you are trying to load into N2V. 
Did you use the notebook for Noise2Void 2D or Noise2Void 3D ?
Could you tell us a little bit more about the type of images you are using ? File format and dimensions would be very useful. 

At the moment Noise2Void 2D only accepts single .tif images (grayscale images) while you can load Z stacks (.tif) in Noise2Void 3D (also grayscale images).

**Comment by Romain-Laine** [comment]
Hi, here's my suggestion: 
Try and test it first on the data we provide by following the same protocol as described on the video, adapting it to N2V, and check if this works for you.

As Guillaume suggested, it sounds like it may be a format or data dimension issue. Please see if the following works for you:
- if using N2V 2D, make sure they are single frame 2D tif images
- if using N2V 3D, make sure they are  z-stack tif images

You should be able to convert your images into tif by using Fiji/ImageJ if your images are not tif to start with but beware that conversion can (and most likely will) change the actual data.
All the best !
R

**Comment by sparkerino** [comment]
Ok! So yes, I was trying to run it on a timelapse video, forgetting that technically, that's 3D 🤓. I had the same error with a single channel, single frame, single color LUT 16-bit TIF, but changing it to grayscale worked! I'll see if I can get further without hitting another error, thanks for your help! Stay safe!

**Comment by guijacquemet** [comment]
Great ! If you want to denoise a timelapse video then I would still use the 2D notebook. Just save your timelapse as single images. You can do this very easily using Fiji "save as an image sequence" export function. The 3D notebook is more dedicated to dealing with Z stacks.  
Stay safe too !
