### ISSUE TITLE
CARE 3D 

### ISSUE THREAD

**Issue by EvaNordmann** [HenriquesLab/ZeroCostDL4Mic#10]
**Describe the bug**
ResourceExhaustedError in step 6.1. of CARE 3D notebook.

First, thank you so much for making these notebooks available to use. The CARE 2D works fantastically on my images! 

Right now I am trying to apply my trained CARE 3D model on 3 of my stacks. They are all tiff files with 217 Slices. Though when running it, the following error comes up:
ResourceExhaustedError. 
[ResourceExhaustedError.pdf](https://github.com/HenriquesLab/ZeroCostDL4Mic/files/4510157/ResourceExhaustedError.pdf)

 - OS: Windows10
 - Browser: Firefox

**Comment by uschmidt83** [comment]
Hi @EvaNordmann,

I've found and [fixed the bug](https://github.com/CSBDeep/CSBDeep/commit/483bd61ad0f63fffd176c0386f8025366ebbaed7) in the https://github.com/CSBDeep/CSBDeep code, but this won't help you in the short term.

The authors of https://github.com/HenriquesLab/ZeroCostDL4Mic can probably help you to increase the number of tiles manually, such that your large stack is broken into smaller pieces for prediction.

Best,
Uwe

**Comment by guijacquemet** [comment]
Hi @EvaNordmann,
Many thanks for reaching out and glad to hear that you find the notebooks useful!
We will update the CARE 3D notebook so that you can easily change the number of tiles when performing the prediction! 
Thanks, @uschmidt83 for suggesting it. Indeed a very important feature to add.
All the best
Guillaume

**Comment by EvaNordmann** [comment]
Hi Uwe and Guillaume,

Thank you so much for your support! 
Looking forward to trying it with a higher number of tiles then :)

All the best and thank you again for making these notebooks available! They are great to work with.
Eva

**Comment by guijacquemet** [comment]
Hi @EvaNordmann,
We have now uploaded a new version of the CARE3D notebook which will allow you to control the number of tiles to use when performing the predictions. Let us know how it works!
I would recommend that you progressively increase these numbers until the ResourceExhaustedError disappear.
Let us know how it works and thanks again for reaching out!
All the best
Guillaume

**Comment by EvaNordmann** [comment]
Hi Guillaume,

Thank you so much! That's really great. I will try it right away and let you know how it works!

All the best!
Eva

**Comment by EvaNordmann** [comment]
Hi @guijacquemet,

It works. Thank you very much for your help!

Best regards
Eva

**Comment by guijacquemet** [comment]
Great to hear that!
Thanks for letting us know
All the best
Guillaume
