### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode' during CARE and Stardist training

### ISSUE THREAD

**Issue by Jul0201** [HenriquesLab/ZeroCostDL4Mic#100]
Hello!

I am trying to use CARE for denoising and Stardist for segmentation and get the same error message during training for both (AttributeError: 'str' object has no attribute 'decode').

My CARE dataset is
- Training source: 114 images  (1024x1024, 16-bit in .tif-format)
- Training target:  114 images  (1024x1024, 16-bit in .tif-format) 
The target images have the same name as the corresponding images from the training source.

My Stardist training dataset is
- Training source: 15 images (2048x2048, 16-bit)
- Training target : 15 images (2048x2048, 16-bit) (with the same name as the corresponding training source images)

I followed the CARE (2D)/Stardist mask in Google Colab but when it comes to the training step, there is an error message and 8 frames are displayed which look like this:

> /usr/local/lib/python3.7/dist-packages/stardist/models/model2d.py in train(self, X, Y, validation_data, augmenter, seed, epochs, steps_per_epoch)
>     379                       epochs=epochs, steps_per_epoch=steps_per_epoch,
>     380                       callbacks=self.callbacks, verbose=1)
> --> 381         self._training_finished()
>     382 
>     383         return history
> 
> /usr/local/lib/python3.7/dist-packages/csbdeep/models/base_model.py in _training_finished(self)
>     203             if self.config.train_checkpoint is not None:
>     204                 print()
> --> 205                 self._find_and_load_weights(self.config.train_checkpoint)
>     206             if self.config.train_checkpoint_epoch is not None:
>     207                 try:
> 
> /usr/local/lib/python3.7/dist-packages/csbdeep/models/base_model.py in wrapper(*args, **kwargs)
>      30                 warn is False or warnings.warn("Suppressing call of '%s' (due to basedir=None)." % f.__name__)
>      31             else:
> ---> 32                 return f(*args, **kwargs)
>      33         return wrapper
>      34     return _suppress_without_basedir
> 
> /usr/local/lib/python3.7/dist-packages/csbdeep/models/base_model.py in _find_and_load_weights(self, prefer)
>     165         weights_chosen = weights_preferred[0] if len(weights_preferred)>0 else weights_files[0]
>     166         print("Loading network weights from '%s'." % weights_chosen.name)
> --> 167         self.load_weights(weights_chosen.name)
>     168 
>     169 
> 
> /usr/local/lib/python3.7/dist-packages/csbdeep/models/base_model.py in wrapper(*args, **kwargs)
>      30                 warn is False or warnings.warn("Suppressing call of '%s' (due to basedir=None)." % f.__name__)
>      31             else:
> ---> 32                 return f(*args, **kwargs)
>      33         return wrapper
>      34     return _suppress_without_basedir
> 
> /usr/local/lib/python3.7/dist-packages/csbdeep/models/base_model.py in load_weights(self, name)
>     182             Name of HDF5 weight file (as saved during or after training).
>     183         """
> --> 184         self.keras_model.load_weights(str(self.logdir/name))
>     185 
>     186 
> 
> /tensorflow-1.15.2/python3.7/keras/engine/saving.py in load_wrapper(*args, **kwargs)
>     490                 os.remove(tmp_filepath)
>     491             return res
> --> 492         return load_function(*args, **kwargs)
>     493 
>     494     return load_wrapper
> 
> /tensorflow-1.15.2/python3.7/keras/engine/network.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
>    1228             else:
>    1229                 saving.load_weights_from_hdf5_group(
> -> 1230                     f, self.layers, reshape=reshape)
>    1231             if hasattr(f, 'close'):
>    1232                 f.close()
> 
> /tensorflow-1.15.2/python3.7/keras/engine/saving.py in load_weights_from_hdf5_group(f, layers, reshape)
>    1181     """
>    1182     if 'keras_version' in f.attrs:
> -> 1183         original_keras_version = f.attrs['keras_version'].decode('utf8')
>    1184     else:
>    1185         original_keras_version = '1'
> 
> AttributeError: 'str' object has no attribute 'decode'
> 

I would appreciate any help!

Jul0201

**Comment by Jul0201** [comment]
Hi Romain,
thanks for answering! I will try it asap and tell you whether it worked
Cheers
Jul0201

**Comment by Jul0201** [comment]
I repeated the training step in Stardist and CARE with the training data described above but after around 1h 30 min, both stopped running although the training sessions did not go through all epochs.

When I re-started the training, there was an error message in CARE:

> ---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

<ipython-input-1-950cade14c7c> in <module>()
      1 #@markdown ##Start training
      2 
----> 3 start = time.time()
      4 # history = model.fit_generator(train_datagen, steps_per_epoch = number_of_steps, epochs=epochs, callbacks=[model_checkpoint,csv_log], validation_data = validation_datagen, validation_steps = validation_steps, shuffle=True, verbose=1)
      5 history = model.fit_generator(train_datagen, steps_per_epoch = number_of_steps, epochs = number_of_epochs, callbacks=[model_checkpoint, reduce_lr], validation_data = validation_datagen, validation_steps = validation_steps, shuffle=True, verbose=1)

NameError: name 'time' is not defined

and in StarDist there was the same error message:

> ---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

<ipython-input-1-c9e19e669122> in <module>()
      1 #@markdown ##Start training
      2 
----> 3 start = time.time()
      4 
      5 

NameError: name 'time' is not defined

I am not sure whether I should change anything when I try to re-start the training?

Also, I wondered whether my training dataset was too big. So I tried the CARE training with a much smaller training dataset (10 pairs of images instead of 114) and I was able to generate a model. Maybe I should have started training with few images and continue to train this model in another session with further images? (But the training time with the larger training dataset did not even succeed 90 min before it stopped, so I am not sure)

**Comment by guijacquemet** [comment]
Hi @Jul0201 

from what you describe it sounds like you were disconnected from the runtime. This can happen when you heavily use Colab (you will get shorter session), but can also happen when Colab is not used interactively. You may get an "I a not a robot" message that if you do not interact with, will trigger the termination of your session. Because of this, it is good to keep an eye on the training. 

I would not decrease the size of your training dataset. Even if you get disconnected before the end of your chosen number of Epoch, models are saved at the end of every epoch and you can restart training using these if the training is insufficient. 

the error you describe above is because your session was restarted, you need to run all the cells again after a session restart to make sure that all the variables are correctly loaded.

hope this helps

Cheers

Guillaume
