### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode

### ISSUE THREAD

**Issue by Goes2021** [HenriquesLab/ZeroCostDL4Mic#103]
Hi,

I've encountered a problem with the ZeroCost YOLO notebook, which I did not encounter previously. About one week ago the training with my dataset was working, but since a couple of days it gives this error: AttributeError: 'str' object has no attribute 'decode'. I did not change anything in my dataset.  

AttributeError                            Traceback (most recent call last)
<ipython-input-9-0fa96811ec14> in <module>()
    112 
    113 os.chdir('/content/gdrive/My Drive/keras-yolo2')
--> 114 train('config.json', full_model_path, percentage_validation)
    115 
    116 shutil.copyfile('/content/gdrive/My Drive/keras-yolo2/config.json',full_model_path+'/config.json')

5 frames
/tensorflow-1.15.2/python3.7/keras/engine/saving.py in load_weights_from_hdf5_group(f, layers, reshape)
   1181     """
   1182     if 'keras_version' in f.attrs:
-> 1183         original_keras_version = f.attrs['keras_version'].decode('utf8')
   1184     else:
   1185         original_keras_version = '1'

AttributeError: 'str' object has no attribute 'decode'

Thanks!

**Comment by lucpaul** [comment]
Hello, thanks for raising this. We have noticed this recently in the keras notebooks. There seems to have been a version update sometime recently. This error has to do with the version h5py and we're going to fix this in all the notebooks asap.
I just updated the YOLO notebook to fix this error. Can you maybe check the new YOLOv2 notebook (on the wiki as of now) and see if the model can be trained now? The installation section is a little bit different, so just make sure you play all the cells.
If it works now and fixes the problem, you can close the issue.
