### ISSUE TITLE
3D U-Net: error when using images of different shape and a batch size > 1

### ISSUE THREAD

**Issue by esgomezm** [HenriquesLab/ZeroCostDL4Mic#106]
Hi there!

I'm training a 3D U-Net on a set of images with different shapes, a batch size of 5, and a  patch size of (256,256,8). All the images are larger than the patch size. However, during the training, I get the following error:

```python
TimeoutError                              Traceback (most recent call last)
/tensorflow-1.15.2/python3.7/keras/utils/data_utils.py in get(self)
    609                     future = self.queue.get(block=True)
--> 610                     inputs = future.get(timeout=30)
    611                 except mp.TimeoutError:

9 frames
/usr/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    652         if not self.ready():
--> 653             raise TimeoutError
    654         if self._success:

TimeoutError: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-41-6942199a09e9> in <module>()
     27             ckpt_period=checkpointing_period,
     28             save_best_ckpt_only=save_best_only,
---> 29             ckpt_path=last_ckpt_path)
     30 
     31 print('Training successfully completed!')

<ipython-input-3-d0f2f0a837db> in train(self, epochs, batch_size, train_generator, val_generator, model_path, model_name, optimizer, loss, metrics, ckpt_period, save_best_ckpt_only, ckpt_path)
    538                                  callbacks=[csv_logger,
    539                                             model_ckpt,
--> 540                                             sample_img])
    541 
    542         last_ckpt_name = ckpt_dir + '/' + model_name + '_last.hdf5'

/tensorflow-1.15.2/python3.7/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/tensorflow-1.15.2/python3.7/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1730             use_multiprocessing=use_multiprocessing,
   1731             shuffle=shuffle,
-> 1732             initial_epoch=initial_epoch)
   1733 
   1734     @interfaces.legacy_generator_methods_support

/tensorflow-1.15.2/python3.7/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    183             batch_index = 0
    184             while steps_done < steps_per_epoch:
--> 185                 generator_output = next(output_generator)
    186 
    187                 if not hasattr(generator_output, '__len__'):

/tensorflow-1.15.2/python3.7/keras/utils/data_utils.py in get(self)
    623         except Exception:
    624             self.stop()
--> 625             six.reraise(*sys.exc_info())
    626 
    627 

/usr/local/lib/python3.7/dist-packages/six.py in reraise(tp, value, tb)
    701             if value.__traceback__ is not tb:
    702                 raise value.with_traceback(tb)
--> 703             raise value
    704         finally:
    705             value = None

/tensorflow-1.15.2/python3.7/keras/utils/data_utils.py in get(self)
    615                         ' It could be because a worker has died.'.format(idx),
    616                         UserWarning)
--> 617                     inputs = self.sequence[idx]
    618                 finally:
    619                     self.queue.task_done()

<ipython-input-3-d0f2f0a837db> in __getitem__(self, idx)
    248 
    249                 source_batch[batch,:,:,i,0] = src_crop
--> 250                 target_batch[batch,:,:,i,0] = tgt_crop
    251 
    252         if self.augment:

ValueError: could not broadcast input array from shape (211,256) into shape (256,256)
```
If I set the `batch_size = 1`, the notebook works perfectly. I think the method takes the shape of the first image to calculate the corresponding 5 patches of the batch. 

Thank you!
Esti

**Comment by Anushri1903** [comment]
hey 
I am trying to run U-net-3D zerocostDL4  for my data set. Data  is a tif file having dimension x=256, y=256,z= 37. I am able to run till Data augmentation section but in Data augmentation I am getting an errorr  - ValueError: validation_split too small! Increase val_split or decrease z-depth. I tried changing valuefor validation_split bu nothing is working out.
Can you please help me with this? Thanks

Attaching complete error for your reference

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:171: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-34-4abee48e1257>](https://localhost:8080/#) in <module>()
     87                                        random_crop=random_crop,
     88                                        downscale=downscaling_in_xy,
---> 89                                        binary_target=binary_target)
     90 
     91 

1 frames
[<ipython-input-25-e3da6cc9330e>](https://localhost:8080/#) in on_epoch_end(self)
    357 
    358         if self.is_val and (len(self.batch_list) <= 0):
--> 359             raise ValueError('validation_split too small! Increase val_split or decrease z-depth')
    360         random.shuffle(self.batch_list)
    361 

ValueError: validation_split too small! Increase val_split or decrease z-depth

**Comment by esgomezm** [comment]
Hi @Anushri1903 

Thank you for trying the notebook. 

How many images do you have to train the network? Is it only one? The problem here is that when it tries to get a small portion of the data for the validation (for example 10%), it gets 0 images. Could you please share the configuration you wrote in section 3.1? 

Thank you!

**Comment by Anushri1903** [comment]
Hi,
I am glad you replied.

I am able to identify the issue.
Root cause:
It was because of the training shape(256,256,8,1) that we specify in
training parameters and the validation percentage (20%) that we set.
So in the Augmentation section  my stack_sart was 30  and end = 37-8=29
thus the range of validation data was range(30,29)--- bug
when I increased my validation split = 50 % and the  bug was handled.
 Although, the first thing I was trying to do is to decrease the z -depth
from 8 to 4 as this could have been another way out to resolve the problem
but it was giving me some model(Unet) related bug. I know validation split
= 50 % is not a very good idea.

Also I am looking for some guidance for my image analysis project.
My image size is (37,256,256,4). These 4 channels are focusing on different
objects ex. ch-1 membrane, ch-2, virus. My goal is to identify how many
viruses are on the membrane, in the membrane, out of the membrane. I am
able to segment the membrane, my next task is to find the location and
count of viruses.
Can you please help me for my next task ? I appreciate any guidance from
you.

Thank you so much for your time.
Thanks and regards
Anushri



Sorry for taking yor

**Comment by esgomezm** [comment]
Hi @Anushri1903 

Glad to hear that you found the reason. See my comments below:

> Although, the first thing I was trying to do is to decrease the z -depth
from 8 to 4 as this could have been another way out to resolve the problem
but it was giving me some model(Unet) related bug. 

This is related to the shape of the 3D U-Net. This architecture has a U-shape, that is formed by downsamplings in encoder part (left side of the U shape) and then upsampling in the decoder (right side of the U shape). The more downsamplings you have, the deeper the architecture is. In the notebook, the number of downsamples is set to 3, which means that in the Z-dimension you need to at least have at least a dimension of 8 (2*2*2).

> I am able to segment the membrane, my next task is to find the location and count of viruses.
Can you please help me for my next task ? I appreciate any guidance from you.

As you are able to segment the membrane, could you label the three parts differently? For example, you could get three binary images with the following information:
- pixels representing membrane = 1
- pixels representing the inside part of the membrane = fill the holes of the membrane segmentation and then subtract the membrane. 
- pixels that are not part of the membrane = the entire image - pixels in the membrane - pixels representing the membrane

Then you could measure how many viruses are in the first image, the second image and the third image, by multiplying the virus segmentation with each of the three binary images above.

**Comment by Anushri1903** [comment]
Hi,
Thanks for detailed explanations, I really appreciate it.
I will try the approach that you are suggesting, theoretically I can
imagine it.
As far as I know, the segmented image is a binary classified image
which means my pixel values will be 1 and 0 [1-membrane, 0 background].
How to detect which part of the background is inside the membrane and
which one is outside of it? both will have pixels values 0

Can we read image having both the channels at the same time [CH1-Virus and
Ch-2-Membrane] and change the problem into multi level
classification[membrane,Virus, background]
When I was trying to load full_image[ch1+ch2], the notebook was throwing an
error, thus I had to separate images channel wise. What do you think?
Here, I am sharing with you full_image[Ch-1 Virus, Ch2-Membrane]

Sorry, if I am taking so much of your time.

Thanks and regards
Anushri

**Comment by esgomezm** [comment]
Hi @Anushri1903 


> How to detect which part of the background is inside the membrane and which one is outside of it? both will have pixels values 0

If the membranes are closed structures (like circles or so), they will have a "hole", which is the inside part of the membrane. In ImageJ, you can run "Fill holes". Then you subtract to this image, the binary image with only the membrane labelled, and you will get a mask for the inside part of the membrane. 



> Can we read image having both the channels at the same time [CH1-Virus and Ch-2-Membrane] and change the problem into multi level classification[membrane,Virus, background] When I was trying to load full_image[ch1+ch2], the notebook was throwing an error, thus I had to separate images channel wise. What do you think?

At the moment this is not possible without programming. The network is prepared for images with one channel. 

> Here, I am sharing with you full_image[Ch-1 Virus, Ch2-Membrane]

I cannot see any image, sorry.

**Comment by Anushri1903** [comment]
Hey,
I have one more question.
Earlier I was training the model for one tif file(z-stack=37).
I have multiple tiff files for the same object  and I want to increase the
efficiency of the model by training the model using multiple tiff files.
Can I do that using ZeroCostDL, actually i tried passing a folder of my
training and tiff files but I don't think it accepts a complete folder, how
can I do this?

Thanks
Anushri

**Comment by Anushri1903** [comment]
Thanks for your explanation.
