### ISSUE TITLE
Stardist 2D training does not finish at last epoch but automatically starts all over again

### ISSUE THREAD

**Issue by Jul0201** [HenriquesLab/ZeroCostDL4Mic#107]
Hi there,

during Stardist 2D training, the following issue occured to me:

When the training reaches epoch 100/100, it restarts at 1/100, runs until 100/100 and then starts at 1/100 again, i.e. the training does not finish.

What could I do to stop the training at epoch 100/100?

My training data are 60 images (1024x1024 pixels, 16-bit).

I would appreciate any help!

Best
Jul0201

**Comment by guijacquemet** [comment]
Hey @Jul0201 ,

That's a new one. A very puzzling issue especially since I cannot reproduce it on my end. Did you have this error in multiple Google Colab session?

If you share your training dataset I could test again with your data. But I cannot see how your images could be the issue here.

**Comment by Jul0201** [comment]
Hi!

I also could not reproduce the issue anymore althout it happened to me three times in the row (but afterwards everything worked perfectly fine)

Thanks anyways!
