### ISSUE TITLE
Error in 4.1. Prepare the training data and model for training

### ISSUE THREAD

**Issue by crtorreg** [HenriquesLab/ZeroCostDL4Mic#111]
Hi, 

I have the following error in the section 4.1:

_>   8%|▊         | 184/2340 [00:00<00:01, 1838.75it/s]Normalizing image channels independently
> 100%|██████████| 2340/2340 [00:01<00:00, 1806.15it/s]
> 100%|██████████| 2340/2340 [00:00<00:00, 3429.06it/s]
> number of images: 2340
> - training:       2106
> - validation:     234
> Number of steps: 4688.0
> Using default values: prob_thresh=0.5, nms_thresh=0.4.
> WARNING: median object size larger than field of view of the neural network.
> ---------------------------------------------------------------------------
> UnicodeEncodeError                        Traceback (most recent call last)
> <ipython-input-54-199424ba1834> in <module>()
>     120 
>     121 #Export pdf summary of training parameters
> --> 122 pdf_export(augmentation = Use_Data_augmentation, pretrained_model = Use_pretrained_model)
>     123 
> 
> 4 frames
> /usr/local/lib/python3.7/dist-packages/fpdf/fpdf.py in _putpages(self)
>    1168             if self.compress:
>    1169                 # manage binary data as latin1 until PEP461 or similar is implemented
> -> 1170                 p = self.pages[n].encode("latin1") if PY3K else self.pages[n]
>    1171                 p = zlib.compress(p)
>    1172             else:
> 
> UnicodeEncodeError: 'latin-1' codec can't encode character '\u0301' in position 2881: ordinal not in range(256)_

Do you know why this is happening?

Thank you,
Cristina.

**Comment by guijacquemet** [comment]
Dear Cristina,

Thanks for reaching out! 
Could you confirm which notebook you are using?
From the error message, it looks like the object you want to segment are very large? it is the case?

Cheers

Guillaume

**Comment by crtorreg** [comment]
Dear Guillaume, 

For sure, it is the SplineDist_2D notebook. The images are like the atached one, do you think that it could be used this notebook for this type of problem? 

![image](https://user-images.githubusercontent.com/86312162/122984054-e2e5c500-d39c-11eb-8f44-fad80e01ad65.png)

Thanks in advance!

Best, 
Cristina

**Comment by Romain-Laine** [comment]
Hi Cristina,
It definitely looks like it could be used, yes. Could you please send us a representative dataset where this issue occurs?
This sort of issues happen when there are some characters in the names of the folders or files that are problematic. Could you also please check your file and folder names?

Cheers,

Romain

**Comment by crtorreg** [comment]
Hi Romain, 

Yes, for sure! You can find in the link below a representative dataset, it is needed to accept the petition in order to share the data.
https://drive.google.com/drive/folders/1pvOcN3Z8NlS12TKUgiVEsMIzBQ8pt0IZ?usp=sharing

I have checked my folder names and I think that are the same to the ones stated on the notebook.

Best,
Cristina.

**Comment by Romain-Laine** [comment]
Hi Cristina, I just took a look at your data and the masks are provided as background and foreground only (0 and 255 respectively). You need to provide instance masks for the SplineDist (or StarDist) to train, 
check our wiki page 
https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki/Stardist

and our StarDist example dataset for example of how training data should look like
https://zenodo.org/record/3715492#.YNmoji1Q1QK

Basically, you need each object to have a different value to differentiate them, you can do that using the "Analyze particles" plugin followed by the "ROIs to Label image" in Fiji.
 
Have a try at that and see how it works. 

Alternatively you can use 2D U-Net to do that on the current data you have. This should also work, probably even better because your objects look really big compared to the patch size you'll get (here limited by the width of the image), as @guijacquemet pointed out.

Cheers,

Romain

**Comment by Romain-Laine** [comment]
Hi Cristina, 
It also looks like there is no 1 to 1 correspondence between the dataset in source and in target. That will also be quite a problem. Please check your data again. Something is not quite right, by the look of it.
Cheers,

Romain

**Comment by crtorreg** [comment]
Hi,

I have fixed the correspondence between images, thank you! Also, I have created the masks with fiji as you have said in order to fix that error but it is still the same and also with the UNet, I do not know what is happening... The error in splinedist is the following:

```
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-16-199424ba1834> in <module>()
    120 
    121 #Export pdf summary of training parameters
--> 122 pdf_export(augmentation = Use_Data_augmentation, pretrained_model = Use_pretrained_model)
    123 

4 frames
/usr/local/lib/python3.7/dist-packages/fpdf/fpdf.py in _putpages(self)
   1168             if self.compress:
   1169                 # manage binary data as latin1 until PEP461 or similar is implemented
-> 1170                 p = self.pages[n].encode("latin1") if PY3K else self.pages[n]
   1171                 p = zlib.compress(p)
   1172             else:

UnicodeEncodeError: 'latin-1' codec can't encode character '\u0301' in position 2807: ordinal not in range(256)

```
and the error of UNet is:

```
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-9-1d561811c58c> in <module>()
     64 print('---------------------------- ------------------------ ----------------------------')
     65 
---> 66 pdf_export(augmentation = Use_Data_augmentation, pretrained_model = Use_pretrained_model)

4 frames
/usr/local/lib/python3.7/dist-packages/fpdf/fpdf.py in _putpages(self)
   1168             if self.compress:
   1169                 # manage binary data as latin1 until PEP461 or similar is implemented
-> 1170                 p = self.pages[n].encode("latin1") if PY3K else self.pages[n]
   1171                 p = zlib.compress(p)
   1172             else:

UnicodeEncodeError: 'latin-1' codec can't encode character '\u0301' in position 2952: ordinal not in range(256)
```


Thank you,
Cristina

**Comment by crtorreg** [comment]
Hi,

I have commented the "pdf_export" function as it is the one that was giving problems. Now, everything work perfectly, with the exception of this error in SplineDist:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-6a8064f47749> in <module>()
     16 #Here we optimize the network.
     17 
---> 18 model.optimize_thresholds(X_val, Y_val)
     19 
     20 print("Done")

8 frames
/content/splinedist/splinedist/nms.py in non_maximum_suppression(coord, prob, grid, b, nms_thresh, prob_thresh, verbose, max_bbox_search)
     62     survivors[ind] = c_non_max_suppression_inds(polygons.astype(np.int32),
     63                     mapping, np.float32(nms_thresh), np.int32(max_bbox_search),
---> 64                     np.int32(grid[0]), np.int32(grid[1])), np.int32(verbose))
     65 
     66     if verbose:

TypeError: function takes exactly 6 arguments (7 given)
```

What do you think?

Thank you,
Cristina

**Comment by Romain-Laine** [comment]
Hi Cristina,
I have tested SplineDist on your data and cannot reproduce the error. It might be in the way you name your folders on your drive. Do you have any letters and characters that are unusual? Please avoid those and see if that works.

For that last error, StarDist (SplineDist's mother) has been updated and I have a fix for a number of bugs that have appeared. This might be one of them. I have not released that new version yet but we will do so soon (end of this week hopefully).

Cheers,

Romain

**Comment by Romain-Laine** [comment]
Hi Cristina,
We have now released new versions of the notebooks, have a play around and see if that fixes a couple of things for you.
Cheers,

R

**Comment by crtorreg** [comment]
HI,

Now, SplineDist do not give any error! Thanks a lot :) 

Best,
Cristina
