### ISSUE TITLE
Session crashing in noise2void (2D)

### ISSUE THREAD

**Issue by morphogenetic2** [HenriquesLab/ZeroCostDL4Mic#113]
Hi, and many thanks for making this amazing set of tools available to the microscopy community! :)

**Describe the bug**
In the noise2void 2d notebook, after executing section 2.1 there's an error saying "The session crashed for an unknown reason", and I'm unable to access my mounted gdrive folder under the Files section in the left vertical bar, even after remounting the drive from the notebook itself.  I have access to GPU but can't find anywhere how to select Python3, I guess it's already preselected?

I'm using the notebook from Chrome in Win10, and have my data files already loaded in GDrive.

Thanks for your help!
Alex

**Comment by guijacquemet** [comment]
Hi Alex,

Thanks for reaching out. Yes, we noticed this yesterday as well. Colab has now a new bug :)
To fix this, once your session has restarted (after section 2.1), 
- you can either reload the page
- You can click on Connect to a hosted runtime

<img width="40%" alt ="Example of image detection with retinanet." src="https://github.com/HenriquesLab/ZeroCostDL4Mic/raw/master/Wiki_files/connect_to_hosted.png"><figcaption> Connect to a hosted runtime. </figcaption>

We will post a new notebook with these instructions soon.

**Comment by morphogenetic2** [comment]
Hi @guijacquemet, thanks for your help, it's working now correctly.
