### ISSUE TITLE
U-Net (2D) training on 2D RGB TIF images.

### ISSUE THREAD

**Issue by ved-sharma** [HenriquesLab/ZeroCostDL4Mic#117]
Hello, I am trying to train my RGB images (512x512) for segmentation with the corresponding binary masks (grayscale) using U-Net (2D) colab. But I ran into this error:

![Screenshot_error](https://user-images.githubusercontent.com/39934015/125113961-53882380-e0b7-11eb-9cc7-0c26bcb89bb6.jpg)

I am guessing that this colab expects training images to be grayscale not RGB, which has three channels. Is that true? If so, is there a colab for training RGB images with the corresponding binary (grayscale) masks for segmentation?

Thanks,
Ved

**Comment by guijacquemet** [comment]
Hi @ved-sharma 

Indeed the U-Net 2D notebook is expecting RGB images. 
I cannot promise that we can make it compatible at this stage but I will tag  @Romain-Laine and @lucpaul who primarily worked on this notebook.

Can you transform your images to grayscale images prior to segmentation?

Depending on what type of structure you want to segment, you could also consider using the StarDist / SplineDist notebook which supports RGB images.

If you are looking for other implementations of U-net, you could check [DeepMIB](http://mib.helsinki.fi/help/main2/ug_gui_menu_tools_deeplearning.html) which may support RGB images. 

I hope this helps

Cheers

Guillaume

**Comment by ved-sharma** [comment]
Thanks for your feedback, will check out the resources!

**Comment by ofrag** [comment]
I wonder if you have a 2D-UNET - preferably multi-label 2D-UNET that accept RGB and/or multi-channel images 
this will be a great resource

Thanks
Ofra
