### ISSUE TITLE
SplineDist Results

### ISSUE THREAD

**Issue by crtorreg** [HenriquesLab/ZeroCostDL4Mic#118]
Hi :) 

I am using the Spline Dist 2D notebook with my data. It would be incredible if you could asses me which parameters could be better to change for my problem, as the segmentation seems to be limited due to those used for default. I have tried by changing some of them but the segmentation is still poor. This is an example of the kind of images and one of the results obtained:

![image](https://user-images.githubusercontent.com/86312162/125150671-ef5e7180-e141-11eb-9f7b-69b5a64697db.png)

Best, 
Cristina

**Comment by LPUoO** [comment]
Hello,
I can't help much with SplineDist (other than suggesting to increase the `contoursize`) but maybe Cellpose will work better with their default values.

**Comment by sohmandal** [comment]
Hi, certain segmentation methods, such as SplineDist, StarDist, rely on shape descriptors. So these methods generally need to have the entire object in the view of their corresponding neural networks. Now for the images that you have attached in your post, you would need training patch sizes as (64x64) or more. This will allow the network to see the entire object at training time.

Here is an example of SplineDist results trained with different patch sizes. 
<img width="764" alt="splinedist" src="https://user-images.githubusercontent.com/75616990/126811535-99b629d5-9134-4563-9eef-a71df93fbfed.png">

**Comment by crtorreg** [comment]
Thank you so much! This has been of great help to me :)
