### ISSUE TITLE
fnet(2D) Data augmentation and training error

### ISSUE THREAD

**Issue by SujanGhim** [HenriquesLab/ZeroCostDL4Mic#121]
Hello!
I had tried to train a model using ZeroCostDL4mic fnet(2D) notebook. However, I run into some errors:
**First was in Data Augmentation with the following message:**

NameError                                 Traceback (most recent call last)
<ipython-input-15-5ccdb5f38c8c> in <module>()
    145   #The best value will depend on the size of the images and the assigned GPU.
    146   #If too many images are loaded to the buffer the notebook will terminate the training as the RAM limit will be exceeded.
--> 147   if len(aug_source)>100:
    148     number_of_images =  100
    149   else:

NameError: name 'aug_source' is not defined

**I progressed the training by turning augmentation off, but got following error during training:**

train_model.py: error: unrecognized arguments: extravasation project/DEEP_LEARNING_NETWORKS/210128_pix2pix _HUVECs_TCs_PECAM_DAPI/Dataset_sorted_focus_TIFF/fnet_Results/fnet_PECAM_training1/fnet_PECAM_training1.csv extravasation project/DEEP_LEARNING_NETWORKS/210128_pix2pix _HUVECs_TCs_PECAM_DAPI/Dataset_sorted_focus_TIFF/fnet_Results/fnet_PECAM_training1 extravasation project/DEEP_LEARNING_NETWORKS/210128_pix2pix _HUVECs_TCs_PECAM_DAPI/Dataset_sorted_focus_TIFF/fnet_Results/fnet_PECAM_training1/fnet_PECAM_training1_val.csv
Time elapsed: 0.0 hour(s) 0.0 min(s) 1 sec(s)

**Dataset size was of 71 images.** Please let me know if you need further information regarding the issue. 

Thanks in advance and have a nice summer days!!

**Comment by guijacquemet** [comment]
Hey @SujanGhim 
thanks for reaching out, @lucpaul do you think you could help @SujanGhim out?
Cheers
Guillaume

**Comment by esgomezm** [comment]
This one should be solved now. Please, reopen the issue if you still encounter problems.
