### ISSUE TITLE
Notebook run locally stops

### ISSUE THREAD

**Issue by LPUoO** [HenriquesLab/ZeroCostDL4Mic#122]
Hello,
I have been getting into this issue where a notebook that I am training locally with my PC resources stops for no apparent reason during the training. This happened multiple times with N2V although I don't know if it is an issue with my system or the notebook. 

```
Epoch 60/100
1156/1156 [==============================] - 303s 262ms/step - loss: 0.1937 - n2v_mse: 0.1937 - n2v_abs: 0.3320 - val_loss: 0.1977 - val_n2v_mse: 0.1977 - val_n2v_abs: 0.3338
Epoch 61/100
1156/1156 [==============================] - 303s 262ms/step - loss: 0.1976 - n2v_mse: 0.1976 - n2v_abs: 0.3354 - val_loss: 0.1976 - val_n2v_mse: 0.1976 - val_n2v_abs: 0.3337
Epoch 62/100
1140/1156 [============================>.] - ETA: 4s - loss: 0.1962 - n2v_mse: 0.1962 - n2v_abs: 0.3339Batch 1140: Invalid loss, terminating training

Loading network weights from 'weights_best.h5'.
peak memory: 3083.91 MiB, increment: 0.25 MiB
Model training is now done.
Time elapsed: 5.0 hour(s) 13.0 min(s) 55 sec(s)
INFO:tensorflow:No assets to save.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: C:\Users\Lab\AppData\Local\Temp\tmpqemz1ijl\model\saved_model.pb

Model exported in BioImage ModelZoo format:
D:\Google Drive\n2vNRformation\models\3dv3sat\export.bioimage.io.zip
Your model has been successfully exported and can now also be used in the CSBDeep Fiji plugin
```

As you can see above, the training stops midway in an epoch 62/100. 

after that, the cell to show a plot of training errors vs. epoch number doesn't work and I get:
```
---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

<ipython-input-45-222443768794> in <module>
      8     next(csvRead)
      9     for row in csvRead:
---> 10         lossDataFromCSV.append(float(row[0]))
     11         vallossDataFromCSV.append(float(row[1]))
     12 

IndexError: list index out of range
```
I guess this happens because the last row of the `training_evaluation.csv` in the quality control folder has a `nan` for the last value of the loss.

Continuing the training from the point it stopped doesn't work with the `last `epoch but it does with the `best`:
`pretrained network learning rate found
Learning rate of best validation loss: 2.5e-05
Weights found in:
/Google Drive/n2vNRformation/models/3dv3\weights_best.h5
will be loaded prior to training.`

However when I concatenate the two `training_evaluation.csv` I get:
![image](https://user-images.githubusercontent.com/64419544/126152150-3861a247-938c-4433-98c8-a90acc8c7343.png)
The training went for 114 epoch before stopping then another 61 before stopping again.
(I am not sure what is going on with the validation loss, as it looks like it jumps from 0.185 to 0.197?)

So my question is what could cause the training to stop? This happened while the PC was not attended during the night, Could something on the PC get into stand-by and stop the training without causing errors? At no point the notebook gets disconnected from my local runtime since it does save the model and so on.

Thank you very much for any suggestions.

**Comment by guijacquemet** [comment]
Hi @LPUoO ,
Sorry for the super slow answer, we have not been working much with the notebook locally. Is your issue still persisting?

Cheers
Guillaume

**Comment by LPUoO** [comment]
@guijacquemet, I started using a different workstation and I didn't have that issue 🤷‍♂️
Thanks
