### ISSUE TITLE
MaskRCNN: error at loading depencies block

### ISSUE THREAD

**Issue by rr1610** [HenriquesLab/ZeroCostDL4Mic#123]
Hi, 

I'm running the MaskRCNN notebook through Google Colab and haven't been able to get passed the "1.3 Load key dependencies" block. I've made sure that I am running the most up-to-date version of the nb.

When running the "1.1 Install key dependencies" block I make sure to wait a few seconds, so that the force session restart completes in full. 

At which point, I get the following error when running block 1.3:
```
TensorFlow 1.x selected.

  File "/content/Mask_RCNN/mrcnn/model.py", line 704
    class_ids = tf.ones_like(probs[:, 0], dtype=tf.int32)
            ^
IndentationError: expected an indented block
```

Thanks in advance if anyone can fix the issue.

**Comment by Romain-Laine** [comment]
Hey Edward, thanks for raising that issue. 
I have just tested it using the latest version of the notebook and cannot reproduce the error you mention above. It all installs well for me.
Could you please give us some more info about the environment you're using? 

<img width="582" alt="Screenshot 2021-07-28 at 16 49 30" src="https://user-images.githubusercontent.com/21193399/127354476-fb8fc21b-c4ac-4ab4-a36d-b33cf90a8159.png">

**Comment by rr1610** [comment]
Hey Romain. I was initially unable to reproduce the error myself when I opened the notebook in a completely fresh runtime. When run in a completely new (as in factor reset NOT restarted) runtime, I also don't get the OP error.

From some experimentation, I think the error is only raised when the "Load key dependencies" block is run more than once in the same runtime. Usually this wouldn't happen, but if the session crashes eg RAM usage, I think you are still required to run the load dependencies block at which point the "IndentationError" is still raise

I do repeatedly however get an error at the "3.1. Setting the main training parameters" block.

![image](https://user-images.githubusercontent.com/45792265/127568243-e62774dc-9e57-4b74-bf1d-d36c772731f2.png)

By commenting out lines 175-179  and preventing "loading and displaying samples", the 3.1 block executes w/o error. 

However, then running the "4.1 training the network" block returns the following error

![image](https://user-images.githubusercontent.com/45792265/127569201-695a4b96-e940-4114-b3d7-9511323fbedd.png)

I tried simply commenting out line 3 and ignoring the pdf export. But, the following error is still returned: 

![image](https://user-images.githubusercontent.com/45792265/127569387-c6dabe67-7120-4079-a4f7-2acfb88dd671.png)

**Comment by Romain-Laine** [comment]
Hi Edward, 
OK, it would make sense to reset the session from scratch when crashing, this would avoid the issue you've seen.

Regarding the following errors, it all looks like no images are found in your training data folders. Could you check that everything is loaded properly?
Please check that you have organised the dataset properly as described in section 0. of the notebook. See below:

<img width="1047" alt="Screenshot 2021-08-02 at 10 36 34" src="https://user-images.githubusercontent.com/21193399/127839852-b4424c7a-bdb3-4a14-94e0-a052254e24d8.png">

**Comment by guijacquemet** [comment]
Hi @rr1610 ,
Are you still having some issues with this notebook or can I close your issue?
Cheers
Guillaume
