### ISSUE TITLE
Noise2Void 2D notebook not found

### ISSUE THREAD

**Issue by llemgruber** [HenriquesLab/ZeroCostDL4Mic#13]
Hiya

I'm trying to open Noise2Void 2D notebook and I keep getting this error message - attached.
All other notebooks open without a problem.

cheers
leandro
![Screenshot 2020-04-28 at 12 41 34](https://user-images.githubusercontent.com/62759899/80491029-145e2e80-895a-11ea-92cd-810ae1622612.png)

**Comment by guijacquemet** [comment]
Hi,
Thank you very much for letting us know. This issue should be fixed now!

All the best
Guillaume
