### ISSUE TITLE
StarDist 2D notebooks does not segmentate but outputs raw input

### ISSUE THREAD

**Issue by DaniK-BIP** [HenriquesLab/ZeroCostDL4Mic#14]
Hello,

First, thank you and your team for making such a nice platform for ease of use in microscopy deep-learning and research.

The StarDist 2D notebook that i have been using works well, however, when i want the network to analyse my own dataset, it outputs the raw input. Besides this, it also outputs a .rar with black images, where the network tries to find a cell. 

For this, i have performed no edits to the StarDist 2D notebook, and trained the network with 1000 epochs at standard settings. I have tried different bit versions of the same file, which was originally 16-bit, now adapted to 32-bit. 

Below i have included my system information and my data and it's results, zipped. My data input into the notebook as a .tiff file, not a .rar. I also included the original 16-bit .tiff file before it was 

https://drive.google.com/file/d/1WMlHVQOQOGWQiGH1NjtFnR9NUJUAtuoU/view?usp=sharing
[Systeminfo.txt](https://github.com/HenriquesLab/ZeroCostDL4Mic/files/4548529/Systeminfo.txt)

**Comment by guijacquemet** [comment]
Hi,
Thanks a lot for reaching out! It indeed look like there is a bug with the image being exported. We will fix this shortly.
However, the .zip file should contain the ROI of the detected object and this appear to work fine.
Looking at your images and the ROI being detected, did you train the network using your own images ? or did you try to apply on your images a network trained with the one we provide?

**Comment by DaniK-BIP** [comment]
Hello Guillaume,
I have trained the network the training data provided in the ZeroCostDL4mic wiki for StarDist 2D. From the data i have provided you, are you achieving the desired result? 
I use Fiji to open the files, i assume the .tiff and ROI files have to be combined, but i have not yet been able to do this through Fiji

Cheers,
Dani

**Comment by guijacquemet** [comment]
Hi, 
No, the segmentation looks horrible, but this is because the data we provide is too different from the one you want to segment. You need to create a training set and train Stardist using your own images.
In Fiji, you can open the ROI exported by the stardist segmentation by just dragging and dropping the .Zip file. You can also open the .Zip file directly from Fiji ROI manager.

Cheers
Guillaume

**Comment by DaniK-BIP** [comment]
Hello,
I have gotten the ROI to overlay onto the brightfield image, portaying 4 cells in each corner.
Regarding making our own training set, is this done using, for example, using the StarDist 2D plugin available in Fiji?

Cheers,
Dani

**Comment by guijacquemet** [comment]
To create your own training set you can follow our suggestions here:
https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki/Stardist
Or follow the suggestions provided by the Stardist authors:
https://github.com/mpicbg-csbd/stardist
All the best
Guillaume

**Comment by guijacquemet** [comment]
Hi,
I have now fixed the bug you reported! thanks again for reaching out 
Cheers
Guillaume
