### ISSUE TITLE
StarDist(2D) notebook local error - Section 4.2 

### ISSUE THREAD

**Issue by qinghongwan** [HenriquesLab/ZeroCostDL4Mic#151]
When running the StarDist(2D) notebook locally, I get an error in section 4.2
ValueError: images and masks should have corresponding shapes/dimensions

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_2984/2926955051.py in <module>
      5 
      6 history = model.train(X_trn, Y_trn, validation_data=(X_val,Y_val), augmenter=augmenter,
----> 7                       epochs=number_of_epochs, steps_per_epoch=number_of_steps)
      8 None;
      9 

~/miniconda3/envs/myenv/lib/python3.7/site-packages/stardist/models/model2d.py in train(self, X, Y, validation_data, classes, augmenter, seed, epochs, steps_per_epoch, workers)
    420         classes_val = self._parse_classes_arg(validation_data[2], n_data_val) if self._is_multiclass() else None
    421         n_take = self.config.train_n_val_patches if self.config.train_n_val_patches is not None else n_data_val
--> 422         _data_val = StarDistData2D(validation_data[0],validation_data[1], classes=classes_val, batch_size=n_take, length=1, **data_kwargs)
    423         data_val = _data_val[0]
    424 

~/miniconda3/envs/myenv/lib/python3.7/site-packages/stardist/models/model2d.py in __init__(self, X, Y, batch_size, n_rays, length, n_classes, classes, patch_size, b, grid, shape_completion, augmenter, foreground_prob, **kwargs)
     36                          n_classes=n_classes, classes=classes,
     37                          batch_size=batch_size, patch_size=patch_size, length=length,
---> 38                          augmenter=augmenter, foreground_prob=foreground_prob, **kwargs)
     39 
     40         self.shape_completion = bool(shape_completion)

~/miniconda3/envs/myenv/lib/python3.7/site-packages/stardist/models/base.py in __init__(self, X, Y, n_rays, grid, batch_size, patch_size, length, n_classes, classes, use_gpu, sample_ind_cache, maxfilter_patch_size, augmenter, foreground_prob)
    148         if isinstance(X, (np.ndarray, tuple, list)) and \
    149            isinstance(Y, (np.ndarray, tuple, list)):
--> 150             all(y.ndim==nD and x.ndim==x_ndim and x.shape[:nD]==y.shape for x,y in zip(X,Y)) or _raise(ValueError("images and masks should have corresponding shapes/dimensions"))
    151             all(x.shape[:nD]>=tuple(patch_size) for x in X) or _raise(ValueError("Some images are too small for given patch_size {patch_size}".format(patch_size=patch_size)))
    152 

~/miniconda3/envs/myenv/lib/python3.7/site-packages/csbdeep/utils/utils.py in _raise(e)
     89 def _raise(e):
     90     if isinstance(e, BaseException):
---> 91         raise e
     92     else:
     93         raise ValueError(e)

ValueError: images and masks should have corresponding shapes/dimensions

**Comment by guijacquemet** [comment]
Hi,

Thanks for reaching out. Out of curiosity, is the dataset you are using working when using the notebook in Google Colab? Just to make sure this is not an issue with the training dataset itself

Cheers

Guillaume

**Comment by qinghongwan** [comment]
Thank you for your letter to answer, I found that the way I read the image was wrong, now the problem has been solved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HenriquesLab/ZeroCostDL4Mic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 凌晨0:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HenriquesLab/ZeroCostDL4Mic] StarDist(2D) notebook local error - Section 4.2  (Issue #151)





 
Hi,
 
Thanks for reaching out. Out of curiosity, is the dataset you are using working when using the notebook in Google Colab? Just to make sure this is not an issue with the training dataset itself
 
Cheers
 
Guillaume
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guijacquemet** [comment]
Hi,
Great to hear!
Thanks for letting me know
Cheers
Guillaume
