### ISSUE TITLE
Cellpose 6.2 model choice

### ISSUE THREAD

**Issue by LPUoO** [HenriquesLab/ZeroCostDL4Mic#154]
Hello,
I can see that the  "Cytoplasm2_Omnipose" and  "Bacteria_Omnipose" models were added to the possible models in section `6.2 Generate prediction(s) from unseen dataset (3D stacks)
  `
but the option has not been integrated in

```
#@markdown ###What model do you want to use?
model_choice = "Cytoplasm" #@param ["Cytoplasm","Cytoplasm2", "Nuclei", "Own_model"]
```

By the way, I don't know if they are available but it would be super cool to also have the Cellpose model trained on TissueNet
https://twitter.com/NoahGreenwald/status/1461370582335844355?s=20
(idem for Stardist)

Thanks a lot

**Comment by guijacquemet** [comment]
Hi @LPUoO ,

To answer your first question, they are not included as they do not appear to work in the 3D mode. I am waiting for the Omnipose team to release the documentation to try to figure out why.

Thanks, I will check the TissueNet models
Cheers
Guillaume

**Comment by LPUoO** [comment]
Hi @guijacquemet,

A few weeks ago new models trained on the TissueNet and LiveCell datasets were released by the Cellpose team ([github](https://github.com/MouseLand/cellpose/blob/072b1d5e7d3e2def2a75c2d3cd625c1ddba8de78/docs/models.rst), [preprint](https://www.biorxiv.org/content/10.1101/2022.04.01.486764v1.full)).
I was wondering if you were planning on adding them to the Cellpose notebook? I could try to make a pull request?

Thanks a lot

**Comment by guijacquemet** [comment]
TissueNet and LiveCell datasets are now available in the notebook.
