### ISSUE TITLE
Install Cellpose and Dependencies error

### ISSUE THREAD

**Issue by Marien-kaefer** [HenriquesLab/ZeroCostDL4Mic#157]
Hi guys, 

I am regularly using the Cellpose notebook and recommend it to users of the imaging facility I work for as Image analyst. Lately, this error is coming up when installing Cellpose and the required dependencies. It does not seem to stop the notebook from working but it is somewhat unsettling and some of our facility users then stop using the notebook. 

     |████████████████████████████████| 69 kB 2.9 MB/s 
  Building wheel for folium (setup.py) ... done
     |████████████████████████████████| 562 kB 4.2 MB/s 
  Building wheel for imgaug (setup.py) ... done
     |████████████████████████████████| 365 kB 4.1 MB/s 
     |████████████████████████████████| 61 kB 500 kB/s 
     |████████████████████████████████| 47.6 MB 23.3 MB/s 
     |████████████████████████████████| 15.7 MB 37.9 MB/s 
     |████████████████████████████████| 3.4 MB 39.1 MB/s 
     |████████████████████████████████| 1.9 MB 43.1 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.3.post1 requires numpy<1.20,>=1.16.0, but you have numpy 1.21.4 which is incompatible.
  Building wheel for wget (setup.py) ... done
  Building wheel for memory-profiler (setup.py) ... done
  Building wheel for fpdf (setup.py) ... done

Is this something that can be resolved or should I recommend users to ignore the error and go ahead with the subsequent notebook steps?

**Comment by guijacquemet** [comment]
Hi @Marien-kaefer 

Thanks for reaching out! The yellowbrick dependency issue does not affect the notebook as this package is not used. 
I have in any case updated the notebook so that the error is not displayed anymore

Best wishes

Guillaume
