### ISSUE TITLE
Understanding Training for Instance segmentation

### ISSUE THREAD

**Issue by jaideep11061982** [HenriquesLab/ZeroCostDL4Mic#160]
**Describe the bug**
Which model shall i use for the instance segmentation
https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/Beta%20notebooks/Cellpose_2D_ZeroCostDL4Mic.ipynb#scrollTo=tsn8WV3Wl0sG ?

How should my target look like . I have instance level RLEs
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guijacquemet** [comment]
Hi @jaideep11061982 

Thanks for reaching out! I am sorry but I am not quite sure what your issue is. Could you elaborate a little?

Cheers

Guillaume
