### ISSUE TITLE
Cellpose - Ominpose (2D) - key dependencies error 

### ISSUE THREAD

**Issue by Marien-kaefer** [HenriquesLab/ZeroCostDL4Mic#161]
Hi there, 

I am trying to use the Cellpose notebook, using a pretrained network. The first cell runs fine but the second cell (Load key dependencies) throws an error: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d907464d37da> in <module>()
     54 from urllib.parse import urlparse
     55 get_ipython().magic('matplotlib inline')
---> 56 from cellpose import models
     57 #use_GPU = models.use_gpu()
     58 

5 frames
/usr/local/lib/python3.7/dist-packages/cv2/__init__.py in <module>()
      7 
      8 from .cv2 import *
----> 9 from .cv2 import _registerMatType
     10 from . import mat_wrapper
     11 from . import gapi

ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/usr/local/lib/python3.7/dist-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

The runtime was connected at the time. Consequently, cells further down the line also throw errors. Can you please help? 

Thanks,
Marie

**Comment by guijacquemet** [comment]
Hi @Marien-kaefer 

Thanks a lot for reaching out!
It looks like a recent Google Colab update broke the OpenCV libraries. I have now updated the notebook to ensure they are installed properly and this should solve your issue.

Let me know if it works well on your side.

Best wishes

Guillaume

**Comment by Marien-kaefer** [comment]
Hi Guillaume, 

Thank you very much for the swift action. The notebooks now works as expected using a pre-trained model. 

Best wishes, 

Marie

**Comment by guijacquemet** [comment]
Excellent! thanks again for reaching out!
