### ISSUE TITLE
UNet 3D - training data set errors at training (4.1)

### ISSUE THREAD

**Issue by axelmoore** [HenriquesLab/ZeroCostDL4Mic#165]
Hello, I am running into an error when trying to run the training data set for UNet 3D. Do you know what the issue is? I am at step 4.1 to 'Start Training'. Line 30 and 1129 are in red text. 

```
PDF report exported in /content/gdrive/MyDrive/Colab Notebook Testing/3DUNet_example_dataset/Models/myfirst_model/
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:606: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
Epoch 1/100
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-a606ff243c12> in <module>()
     28             ckpt_period=checkpointing_period,
     29             save_best_ckpt_only=save_best_only,
---> 30             ckpt_path=last_ckpt_path)
     31 
     32 print('Training successfully completed!')

3 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1127           except Exception as e:  # pylint:disable=broad-except
   1128             if hasattr(e, "ag_error_metadata"):
-> 1129               raise e.ag_error_metadata.to_exception(e)
   1130             else:
   1131               raise

TypeError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "<ipython-input-13-4766c4b156bb>", line 426, in _weighted_binary_crossentropy  *
        binary_crossentropy = K.binary_crossentropy(y_true, y_pred)
    File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 5158, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(labels=target, logits=output)

    TypeError: Input 'y' of 'Mul' Op has type bool that does not match type float32 of argument 'x'.

```

**Comment by esgomezm** [comment]
Hi!

Thank you for trying the notebook. Could you please check the data type of your masks? (the annotated images)

**Comment by axelmoore** [comment]
Hi, thanks for the reply. I am just using the example 3D data set that is mentioned for getting started. All image files and masks are .tif stacks.

**Comment by esgomezm** [comment]
Hi @axelmoore 

I'm trying to replicate the error using the data from EPFL as well but it's working for me. 

Did you use the same name for the input and its corresponding mask? Also, are you using the default parameters given in the notebook? Maybe the easiest way is to share some screenshots of how your data is organised and the notebook setup so I can detect where the problem comes from.

**Comment by axelmoore** [comment]
Here are some screen shots of my notebook organization.

![Screen Shot 2022-03-08 at 8 57 50 PM](https://user-images.githubusercontent.com/52958242/157357472-f02fdd6e-9c21-492d-89e4-6214634c6cc8.png)
![Screen Shot 2022-03-08 at 8 58 03 PM](https://user-images.githubusercontent.com/52958242/157357473-e4b7bc9e-e17d-4aca-a112-ee340eee07af.png)

![Screen Shot 2022-03-08 at 8 55 36 PM](https://user-images.githubusercontent.com/52958242/157357332-ef09d228-a459-4649-a7ce-40aa3c1e3257.png)
![Screen Shot 2022-03-08 at 8 56 00 PM](https://user-images.githubusercontent.com/52958242/157357333-01202075-ba0c-44ce-bda8-8c427c308ef5.png)
![Screen Shot 2022-03-08 at 8 56 08 PM](https://user-images.githubusercontent.com/52958242/157357334-cafb60da-5c46-4d29-a413-4abc5175d8c0.png)

**Comment by thecobb** [comment]
I had the same error using the example dataset on the Google Collab using the default parameters of the notebook. Changing the loss from weighted_binary_crossentropy to binary_crossentropy resolved the error and let me train the model so I think either the true labels or the predictions need to have their type changed to match the other within the weighted_binary_crossentropy function as defined in the section 1 of the
 notebook and shown in the attached screenshot.

<img width="404" alt="Screen Shot 2022-03-09 at 4 11 48 PM" src="https://user-images.githubusercontent.com/17283036/157537358-f9fe478a-aaf4-4359-a6b4-eef9d96a9f1b.png">

**Comment by esgomezm** [comment]
@axelmoore I think we found the problem :) please note that the training data needs to be organised in the way described at the beginning of the notebook (see the screenshot below). Basically, you need to create a folder (e.g., "training") and two more folders inside it (e.g., "input", "masks"). Then, place the training image in the input folder, change the name of the training_ground truth image to the same as the training image (e.g., "training.tif") and place it in the masks folder. The same for the test. Then, it works, at least for me. Please let me know if it's working.
![Screenshot 2022-03-10 at 09 49 33](https://user-images.githubusercontent.com/43643518/157636138-bb6b9441-eabc-408d-b068-8d5be83730c7.png)
 
@thecobb how did you specify the training source and target? did you provide the link directly to the tif files?

**Comment by axelmoore** [comment]
This is actually starting to run. It went through 2 epochs on first try and then crashed. I am trying again and will update here. I have attached a screenshot of the variables I changed.
![Screen Shot 2022-03-10 at 6 54 51 AM](https://user-images.githubusercontent.com/52958242/157657020-39cedc9e-c121-4a19-aac6-e1db4166f4d4.png)

**Comment by axelmoore** [comment]
I am still getting stuck on the first few epochs. I have changed the file structure as suggested. 

![Screen Shot 2022-03-11 at 8 19 29 AM](https://user-images.githubusercontent.com/52958242/157874152-8b07dc14-48bb-482c-b165-d39b71bf8599.png)
![Screen Shot 2022-03-11 at 8 23 07 AM](https://user-images.githubusercontent.com/52958242/157875423-8881f3bb-fdfc-4f57-9849-bb04c855d2d1.png)

**Comment by thecobb** [comment]
I'm running it locally on my computer (MacBook Pro M1max GPU) (as well as on Collab Pro) so I specified the training and target data using the path directly to the tif files. I have it working now though with weight_binary_crossentropy on Collab by adding the following code to the beginning  _weight_binary_crossentropy function " y_true = tf.cast(y_true,tf.float32)". If it's running for 2 epochs and failing, is it possible that it's timing out as a result of being a normal Collab instance? I've been running the notebook with Collab Pro high-ram instance as well and was able to train for 30ish epochs before timing out.

**Comment by axelmoore** [comment]
I don't think it is timing out. It usually doesn't run more than 40 minutes before taping out and the standard version of Collab is supposed to run for 12 hrs from what I understand.

**Comment by esgomezm** [comment]
Hi @axelmoore, as @thecobb said, it's most probably that your colab session was interrupted. The sessions are cut on demand, they do not always stay for 12hrs. Actually nowadays is less common to have such long runs. An easy way to check it is by cropping the training images so you get a smaller training dataset that makes the training faster; then, you should see that it trains for more than 2 epochs. 
Note that when your session is expired, you can always start it again, specify that path to the last checkpoint of the model, and keep training it, rather than running the training from scratch. 



> I'm running it locally on my computer (MacBook Pro M1max GPU) (as well as on Collab Pro) so I specified the training and target data using the path directly to the tif files. I have it working now though with weight_binary_crossentropy on Collab by adding the following code to the beginning _weight_binary_crossentropy function " y_true = tf.cast(y_true,tf.float32)". If it's running for 2 epochs and failing, is it possible that it's timing out as a result of being a normal Collab instance? I've been running the notebook with Collab Pro high-ram instance as well and was able to train for 30ish epochs before timing out.

@thecobb this might be due to different python or tf versions. Thank you!

**Comment by axelmoore** [comment]
I think I am up and running now. I just keep it pointed back to the last checkpoint.
