### ISSUE TITLE
Predicted mask is complete black image. How to save mask, outline and cell pose image separately

### ISSUE THREAD

**Issue by pccoe-co** [HenriquesLab/ZeroCostDL4Mic#169]
Executing Cellpose_2D_ZeroCostDL4Mic.ipynb, the output mask predicted by the model which is saved in my result folder is complete black image but in the notebook it displays the original image, predicted outline, mask and cell pose correctly. How can i save these predicted mask, cell pose and outline files separately in different folders in my drive.

**Comment by guijacquemet** [comment]
Hi,
Thanks for reaching out. 
Could you share an example? How do you open your predicted mask image?
Cheers
Guillaume

**Comment by pccoe-co** [comment]
Thank you for the response. 
since predicted mask image is saved in result folder in my drive with .tif extension, i am trying to open it using image viewing application on google drive itself

images and there predicted mask can be found here:
https://drive.google.com/drive/folders/1HvTq1yUQzDy6aUeAG_PjDuepihn9-9FT?usp=sharing

**Comment by guijacquemet** [comment]
Hi @pccoe-co 
Checking your images, the mask looks fine. The Google Drive image viewer cannot display them properly as they are 16bit Tifs. You need to open them with another viewer. For instance Fiji or Cellprofiler.
![image](https://user-images.githubusercontent.com/25171305/155081655-ab77c1b6-3128-4ff4-8f3d-bdb079062f39.png)
Cheers
Guillaume
