### ISSUE TITLE
No hdf5 file produced for model in Unet

### ISSUE THREAD

**Issue by kamalnahas** [HenriquesLab/ZeroCostDL4Mic#17]
**Describe the bug**
When I try to generate the model with the training data downloaded from ISBI, no hdf5 file is produced in the model directory. The only item present in this directory is the Quality Control folder containing the csv file. 

**To Reproduce**
1. Click on 'Run this cell to check if you have GPU access'
2. Click on 'Play the cell to connect your Google Drive to Colab'
3. Click on 'Play to install U-net dependencies'
4. Create folders 'Training_images' to store train_volume.tif and 'Training_masks' to store train_labels.tif
####Section 3.1####
5. Paste in '/content/gdrive/My Drive/Colab Notebooks/Unet/Training_images' for training_source 
6. Paste in '/content/gdrive/My Drive/Colab Notebooks/Unet/Training_masks' for training_target
7. 50 epochs
8. Click on 'Augmentation options'
####Section 6.1####
9. Create folders 'Test_data' to store test-volume.tif and 'Test_results'.
10. Paste in '/content/gdrive/My Drive/Colab Notebooks/Unet/Test_data' for Data_folder
11. Paste in '/content/gdrive/My Drive/Colab Notebooks/Unet/Test_results' for Results_folder
12. Use the current trained model (ticked)
13. Play the cell

Error message produced:

OSError                                   Traceback (most recent call last)

<ipython-input-19-6a3b1a37cb23> in <module>()
     54 
     55 # Load the model
---> 56 My_model = load_model(Prediction_model_path+'/'+Prediction_model_name+'/'+Prediction_model_name+'.hdf5')
     57 
     58 layers=My_model.layers

----------------------------------------------------------------------------

/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

----------------------------------------------------------------------------

OSError: Unable to open file (unable to open file: name = '/content/gdrive/My Drive/Colab Notebooks/Unet/Model/Unet_model_2020_5_9/Unet_model_2020_5_9.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Screenshots**
![Unet_error](https://user-images.githubusercontent.com/65083303/81479598-165aa400-921c-11ea-9c54-aa32827ee3fd.png)

**Desktop:**
 - OS: Ubuntu 18.04.4 LTS; (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))
 - Browser: Firefox
 - Version: 76

**Comment by guijacquemet** [comment]
Hi, 
Many thanks for reaching out! we just released a new version of the Unet notebook where we fixed many bugs. Could you check if you still have the same issue with the new notebook?
Many thanks
Guillaume

**Comment by Romain-Laine** [comment]
Hi kamalnahas, following the steps you described above, it looks like you did not train the model in the first place. You will need to run the Train model sections in order to generate a trained model to be used in section 6 for prediction!
I hope this helps !

Romain
