### ISSUE TITLE
How to generate output with input image and its mask, cropped RoI and Its mask 

### ISSUE THREAD

**Issue by pccoe-co** [HenriquesLab/ZeroCostDL4Mic#170]
How to generate output as given here https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/master/BioimageModelZoo/Images/cellpose_notebook_2.png

**Comment by guijacquemet** [comment]
Hi @pccoe-co ,

Thanks for reaching out!

To generate this output I used the cellpose notebook found here: https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/Beta%20notebooks/Cellpose_2D_ZeroCostDL4Mic.ipynb

Here I did not train a new model but instead used the cyto2 model already available with cellpose. If you want to do the same, in the notebook, run part 1 and 2. Then Skip sections 3, 4 and 5. Go directly to section 6 and follow the instructions. Once you found the cellpose parameters you want to use, click on the yellow button "process your images".
Then you can download the images and open them in Fiji. In Fiji, I used the Glasbey LUT (to colour-code the instance segmentation image).  
I hope this helps, if you have a question about one of the specific part, let me know!
Cheers
Guillaume
