### ISSUE TITLE
Unable to clone StarDist 3D from github

### ISSUE THREAD

**Issue by zacswider** [HenriquesLab/ZeroCostDL4Mic#198]
Hello,
I made a copy of the StarDist 3D notebook from the wiki (https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki). When installing StarDist and other dependencies I ran into the following error:

> Obtaining stardist from git+git://github.com/stardist/stardist.git@0.6.2#egg=stardist
  Updating ./src/stardist clone (to revision 0.6.2)
  Running command git fetch -q --tags
  fatal: unable to connect to github.com:
  github.com[0: 52.192.72.89]: errno=Connection timed out

I tried changing the offending line from
`!pip install -e git://github.com/stardist/stardist.git@0.6.2#egg=stardist`
to
`!pip install -e git+https://github.com/stardist/stardist.git@0.6.2#egg=stardist`

and it appeared to work:

> Obtaining stardist from git+https://github.com/stardist/stardist.git@0.6.2#egg=stardist
  Cloning https://github.com/stardist/stardist.git (to revision 0.6.2) to ./src/stardist
  Running command git clone -q https://github.com/stardist/stardist.git /content/src/stardist
  Running command git checkout -q 810dec4727e8e8bf05bd9620f91a3a0dd70de289
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done

However, importing stardist fails in the next cell:

> ---------------------------------------------------------------------------
>ModuleNotFoundError                       Traceback (most recent call last)
>[<ipython-input-2-ccd2401dd6b9>](https://localhost:8080/#) in <module>()
>    52 
>   53 # ------- Variable specific to Stardist -------
>---> 54 from stardist import fill_label_holes, random_label_cmap, calculate_extents, gputools_available
>     55 from stardist.models import Config3D, StarDist3D, StarDistData3D
>     56 from stardist import relabel_image_stardist3D, Rays_GoldenSpiral, calculate_extents
>
>ModuleNotFoundError: No module named 'stardist'

I am using Google Chrome Version 103.0.5060.134 (Official Build) (x86_64) on a Macbook. The problem reproduces using Safari Version 14.0 (15610.1.28.1.9, 15610).

**Comment by ctr26** [comment]
Does 

`!pip install stardist==0.6.2`

Work instead?

**Comment by zacswider** [comment]
Yes that seems to work fine!
