### ISSUE TITLE
SplineDist_2D in Colab: FileNotFoundError: [Errno 2] No such file or directory: 'models/phi'

### ISSUE THREAD

**Issue by mzouiouich** [HenriquesLab/ZeroCostDL4Mic#199]
Hello,

I am training a new model on SplineDist 2D Colab (which I did a few months ago without any issues) and I have this issue now in part "4.1 Prepare the training data and model for training":

Normalizing image channels independently
100%|██████████| 53/53 [00:00<00:00, 1014.85it/s]
100%|██████████| 53/53 [00:00<00:00, 338.27it/s]
number of images:  53
- training:        48
- validation:       5
Number of steps: 100
Using default values: prob_thresh=0.5, nms_thresh=0.4.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-7-199424ba1834>](https://localhost:8080/#) in <module>()
    100 
    101 os.chdir(model_path+'/'+model_name)
--> 102 phi_generator(number_of_control_points, conf.contoursize_max)
    103 grid_generator(number_of_control_points, conf.train_patch_size, conf.grid)
    104 

[/content/splinedist/splinedist/utils.py](https://localhost:8080/#) in phi_generator(M, contoursize_max)
    311 
    312     if not os.path.isdir('models/phi'):
--> 313         os.mkdir('models/phi')
    314 
    315     np.save('models/phi/phi_' + str(M) + '.npy',phi)

FileNotFoundError: [Errno 2] No such file or directory: 'models/phi'

I tried to change some parameters (number of control points, contour size...) to train the model but it doesn't resolve the problem.
Do you know what could cause this issue ? 

Thanks for the help (and the notebooks) !

Best regards,
Mehdi Zouiouich

**Comment by JulieEich** [comment]
Hello,
I have the same issue but during the prediction :

The SplineDist_endo_v7 network will be used.
Single images are now being predicted
Performing prediction on: 20220721_MCF7STARD3deltaSTART_GSK3i_4.tif
Normalizing image channels independently
Loading network weights from 'weights_best.h5'.
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.588363, nms_thresh=0.3.

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-4-fae2f747a427>](https://localhost:8080/#) in <module>()
     73     img = normalize(X, 1,99.8, axis = axis_norm)
     74     os.chdir(full_Prediction_model_path)
---> 75     labels, details = model.predict_instances(img)
     76     os.chdir(Results_folder)
     77 

3 frames

[/content/splinedist/splinedist/models/base.py](https://localhost:8080/#) in predict_instances(self, img, axes, normalizer, prob_thresh, nms_thresh, n_tiles, show_tile_progress, verbose, predict_kwargs, nms_kwargs, overlap_label)
    444 
    445         prob, dist = self.predict(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles, show_tile_progress=show_tile_progress, **predict_kwargs)
--> 446         return self._instances_from_prediction(_shape_inst, prob, dist, prob_thresh=prob_thresh, nms_thresh=nms_thresh, overlap_label=overlap_label, **nms_kwargs)
    447 
    448 

[/content/splinedist/splinedist/models/model2d.py](https://localhost:8080/#) in _instances_from_prediction(self, img_shape, prob, dist, prob_thresh, nms_thresh, overlap_label, **nms_kwargs)
    397         coord = dist_to_coord(dist, grid=self.config.grid)
    398         inds = non_maximum_suppression(coord, prob, grid=self.config.grid,
--> 399                                        prob_thresh=prob_thresh, nms_thresh=nms_thresh, **nms_kwargs)
    400         labels = polygons_to_label(coord, prob, inds, shape=img_shape)
    401         # sort 'inds' such that ids in 'labels' map to entries in polygon dictionary entries

[/content/splinedist/splinedist/nms.py](https://localhost:8080/#) in non_maximum_suppression(coord, prob, grid, b, nms_thresh, prob_thresh, verbose, max_bbox_search)
     33     M = np.shape(coord)[2]
     34 
---> 35     phi = np.load('models/phi/phi_' + str(M) + '.npy')
     36     phi = tf.convert_to_tensor(phi)
     37     SplineContour = sg.SplineCurveVectorized(M,sg.B3(),True,coord)

[/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py](https://localhost:8080/#) in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    415             own_fid = False
    416         else:
--> 417             fid = stack.enter_context(open(os_fspath(file), "rb"))
    418             own_fid = True
    419 

FileNotFoundError: [Errno 2] No such file or directory: 'models/phi/phi_32.npy'

I already used this model for sevral prediction without any troubles.

Thanks for the help !
Best regards
Julie Eichler

**Comment by ctr26** [comment]
We're working on a fix upstream

**Comment by guijacquemet** [comment]
Hi, 
the notebook should now be fixed. 
Please let us know if you are still having issues!
Cheers
Guillaume
