### ISSUE TITLE
StarDist 2D Notebook fail on Google Colab: tensorflow1 not supported in Colab - should be updated to use Tensorflow 2

### ISSUE THREAD

**Issue by ofrag** [HenriquesLab/ZeroCostDL4Mic#201]
**Describe the bug**
I'm trying to run StarDist 2D notebook in Google Colab
It fails at stage 1.3 with the following error message: 

    ValueError: Tensorflow 1 is unsupported in Colab.
    
    Your notebook should be updated to use Tensorflow 2.
    See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2.

I wonder if there is an updated notebook, or should I go through the migration myself ? 

Thanks
Ofra

I use Chrome on Windows 10
and the notebook version is:

Notebook_version = '1.13'
Network = 'StarDist 2D'

**Comment by Vathys** [comment]
I'm having the same problems but with YOLOv2.

**Comment by guijacquemet** [comment]
Hi @ofrag and @Vathys 
Thanks for reaching out! Yes, it looks like google colab does not support TF1.15.2 anymore, causing issues in several notebooks. We are on the case and will fix them as soon as possible. 
StarDist2D is now working again using TF2.8.

Cheers

Guillaume

**Comment by ofrag** [comment]
@guijacquemet, 

I think that the previous notebook saved the model into TF_SavedModel.zip that I could convert to onnx for use in QuPath  using tf2onnx, as described for example in: 
https://c4science.ch/w/bioimaging_and_optics_platform_biop/image-processing/qupath/ 

Do you have any idea how this can be achieved with the output of the updated notebook ?

Thanks
Ofra

**Comment by ofrag** [comment]
@guijacquemet 

Thanks for all your support, the trained model is working well in QuPath !!! 
(after conversion using tf2onnx on the unzipped TF_Saved_Model) 

Ofra
