### ISSUE TITLE
WGAN pdf file

### ISSUE THREAD

**Issue by esgomezm** [HenriquesLab/ZeroCostDL4Mic#210]
Hey @iarganda and @IvanHCenalmor 

The notebook is there and working already. We just need to add some peaky details to agree with the platform requirements:
- The results are stored as 8bits. As Images enter the network normalised already to the [0, 1] range, do you think it is too bad to not have them in float or 16bits? (fluorescence intensity is lost in any case)
- Add the Quality PDF file. @IvanHCenalmor you can find examples in the notebooks of the main folder. Maybe check deepSTORM as it also plots SSIM. (Maybe @guijacquemet has another better suggestion)
- I'm trying to get the requirements.txt file using the functions given in ZeroCostDL4Mic but the filtering is removing all the modules from the list (from line 48 of the code in the notebook). I could check this one later.
- Could we link the EM data as well? Do you have any publicly available links?
- In the wiki, we suggest different datasets but some (like F-actin) do not really have a citation associated. Could we add the refs as well? With all this, I can also upload cards to the BioImage Model Zoo :D

I think this is all to have it super perfectly working and documented

**Comment by IvanHCenalmor** [comment]
Hi @esgomezm, I've fixed the problem with the training. The problem was during the checkpoint, which I realized it wasn't really being used and by removing it, it has been solved. In addition, I've already implemented the generation of the PDF files.
