### ISSUE TITLE
StarDist_2D_ZeroCostDL4Mic training super slow

### ISSUE THREAD

**Issue by miinaojansivu** [HenriquesLab/ZeroCostDL4Mic#217]
I am using StarDist_2D_ZeroCostDL4Mic to analyze my super-resolution images of lysosomes. I have done this for several datasets successfully in the past, the latest successful run being about a month ago. I have normally 5-15 training images which I have manually annotated in ImageJ (LOCI plugin). Now I'm trying to do exactly the same training for another similar dataset but for some reason the training is super slow, each epoch taking at least an hour, meaning that there's no way the training could ever be completed with this speed. All my training parameters are exactly the same as previously with the successful runs. I first noticed this problem around a week ago.

Normally the training takes up to 6h or so, depending on the amount of training data. This is what I'd expect to see here as well.

Desktop:
 - HP
 - Firefox (91.3.0esr (64-bit)) & Chrome (I've tried both)

**Comment by esgomezm** [comment]
Hi @miinaojansivu 

The conditions of Google Colab have changed and the old versions of the notebooks do not connect with GPUs anymore. If you will not use the model in Fiji, I would recommend you update the notebook. The performance will be the same. 

Hope this works. I will close the issue but if you still have problems, please reopen it

Thanks!
