### ISSUE TITLE
U-net: trained model applied to "unseen images" of bigger xy size not working

### ISSUE THREAD

**Issue by BMaco** [HenriquesLab/ZeroCostDL4Mic#22]
Dear Developers,

For the membrane segmentation I was able to train the U-net network and my model at size of 512x512 pixels. My understanding was, after training the small portion of the dataset one could apply the trained network to the whole image. But I discovered that it does not work: 512x512 pixels trained model applied to "unseen images" of 3732 x 4720 pixels size resulted to very fuzzy prediction with no recognizable membrane...however, after cropping random region of the same size as training images (e.i. 512x512 pixels) it seems to work and I got membrane segmentation.

So I would like to ask you if this is a way how the algorithm is set at the moment or is it really some issue? How it would be possible to apply the trained network (model) to perform the whole image size... 

Thank you very much for any suggestion.

**Comment by Romain-Laine** [comment]
Hi BMaco, good to hear from you! We have noticed this issue and have a solutions for this. I am actually working on this right at the moment and we hope this can be implemented by next week for the next release ! 
Cheers,

Romain

**Comment by Romain-Laine** [comment]
Hi BMaco, in case you haven't seen this, we have released a new version that should fix your issues. Please have a try and post some examples here if you can to show us how you're getting on !
I hope this helps.

Cheers,

Romain
