### ISSUE TITLE
Cannot load previously trained model - N2V(2D)

### ISSUE THREAD

**Issue by mariana-gferreira** [HenriquesLab/ZeroCostDL4Mic#220]
Hello everyone,

When loading a model previously trained on the N2V(2D) notebook to make a new prediction, it failed, giving this error: AttributeError: 'N2VConfig' object has no attribute 'blurpool'.

I was able to find the issue, the notebook loads the most recent n2v version (0.3.2), while the model had been trained on version 0.3.1. 

Forcing the previous version with `!pip install -q n2v==0.3.1` on Install Key Dependencies solved it.

Thank you 😄

**Comment by esgomezm** [comment]
Hey Mariana! 
Thank you very much for the report :)
I will close the issue as you already said how to solve it. Nevertheless it will be there for any users to find it out
