### ISSUE TITLE
StarDist2: tifffile ERROR

### ISSUE THREAD

**Issue by wyplogin** [HenriquesLab/ZeroCostDL4Mic#226]
TypeError: imwrite() got an unexpected keyword argument 'compress'.

After getting my training data, i upload my stacks tiff(z:200),and run the PART6.
unlucky, show me the error infos.
how can i fixi this error?

thanks a lot,
Bests,
Yipeng

**Comment by esgomezm** [comment]
Hi @wyplogin 

I have just updated the notebook and should work fine. Please, reopen the issue if it doesn't :) 

Thanks!

**Comment by jbogomolovas2** [comment]
Hi I am getting same error in same part of Cellpose notebook. Could you update Cellpose too?
