### ISSUE TITLE
Issue with StarDist2D 6.1 Generate predictions

### ISSUE THREAD

**Issue by mzouiouich** [HenriquesLab/ZeroCostDL4Mic#228]
Hello,

I am having the following error when trying to predict on StarDist2D:

> TypeError                                 Traceback (most recent call last)
> 
> [<ipython-input-8-43b8f2019085>](https://localhost:8080/#) in <module>
>      90 
>      91     if Mask_images:
> ---> 92       imsave(FILEnames[i], labels, polygons)
>      93 
>      94     if Region_of_interests:
> 
> [/usr/local/lib/python3.8/dist-packages/tifffile/tifffile.py](https://localhost:8080/#) in imsave(*args, **kwargs)
>    1235         stacklevel=2,
>    1236     )
> -> 1237     imwrite(*args, **kwargs)
>    1238 
>    1239 
> 
> TypeError: imwrite() takes from 1 to 2 positional arguments but 3 were given

Bests,
Mehdi

**Comment by esgomezm** [comment]
Dear @mzouiouich 
I have updated the notebook already and now it should work :)
