### ISSUE TITLE
imwrite() error with StarDist3D 6.1 generate predictions

### ISSUE THREAD

**Issue by GeorginaSV** [HenriquesLab/ZeroCostDL4Mic#229]
Hello, when I try to generate predictions in the StarDist3D notebook v1.15.1 using Chrome browser I get the following error

![Screenshot 2022-12-15 at 13 10 37](https://user-images.githubusercontent.com/120651767/207867452-2734bac0-314b-4f93-8a96-c91eb9f77f3a.png)

Thank you for your help with this, and for making these notebooks available!

**Comment by esgomezm** [comment]
Dear @GeorginaSV 

Yes, the packages have been updated and this function does not work like that anymore. Could you please download the last version of the notebook? 

If you already have a model working and you don't want to update the notebook, would you mind changing the function as follows?
  - Where it sais `imsave(FILEnames[i], labels, polygons)` please substitute by `imwrite(FILEnames[i], labels)`

Thanks!

**Comment by GeorginaSV** [comment]
Thank you. I found I had to substitute `imsave(FILEnames[i], labels, polygons)` with `imsave(FILEnames[i], labels)` instead of `imwrite(FILEnames[i], labels)`
