### ISSUE TITLE
Cellpose issue:  imwrite() got an unexpected keyword argument 'compress'

### ISSUE THREAD

**Issue by jbogomolovas2** [HenriquesLab/ZeroCostDL4Mic#230]
When I do batch processing of images in section 6.1 I get the following error:
TypeError: imwrite() got an unexpected keyword argument 'compress'
Is there any way of fixing it?

<img width="891" alt="Screenshot 2022-12-15 at 2 35 18 PM" src="https://user-images.githubusercontent.com/105531636/207981726-f6648955-6dc0-4e57-bbae-77dea4aafceb.png">

**Comment by Marien-kaefer** [comment]
Hi ZerCost Team, 

I and other users of our facility are facing the same issue as the person above. Using a built-in model, the preview is generated and looks as I would hope/expect but the images cannot be written onto the G drive. 
In addition, there is an error message in the first code cell - just in case these two problems are related:
`   |████████████████████████████████| 69 kB 3.9 MB/s 
  Building wheel for folium (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.17.5 requires folium>=0.9.1, but you have folium 0.2.1 which is incompatible.`
Is this anything you could help with?

**Comment by jbogomolovas2** [comment]
I found a way to fix imwrite() error by forcing to install older version of  tifffile, in section 1:
!pip install -q tifffile==2022.4.8
