### ISSUE TITLE
for question relate the Stardist(2D and 3D) 5.2 error mapping and quality metrics estimation

### ISSUE THREAD

**Issue by jinxsfe** [HenriquesLab/ZeroCostDL4Mic#234]
**Describe the bug**

As for 5.2 error mapping and quality metrics estimation,
for annotation # modify the names to suitable form: path_images/_numberX.tif

I can't run successfully due to setp error below
for the step " imsave(names[i],labels ,polygons)"

but when I delete polygons, and imsave(names[i],labels )" like this, the picture will generate 
, I don't know why I can save without polygons and what effect if I delete thems?
<img width="767" alt="Screen Shot 2023-01-05 at 11 54 29 PM" src="https://user-images.githubusercontent.com/121477741/210932781-e56d45f3-c977-435f-b869-cd0c7e716db5.png">

**Expected behavior**

**Screenshots**
<img width="1045" alt="Screen Shot 2023-01-05 at 11 46 26 PM" src="https://user-images.githubusercontent.com/121477741/210931916-961f776f-65ff-40c2-94a0-bfa0e7c7d365.png">

<img width="566" alt="Screen Shot 2023-01-05 at 11 47 28 PM" src="https://user-images.githubusercontent.com/121477741/210932027-51e2b321-5526-4e86-ad23-6665f0cda5b1.png">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, 

macbookpro

**Comment by guijacquemet** [comment]
Hi @jinxsfe 
Thanks for reaching out.
I am not sure I understand your issue. Could you post a screenshot of the error you get?

Thanks

Guillaume

**Comment by jinxsfe** [comment]
> Hi @jinxsfe Thanks for reaching out. I am not sure I understand your issue. Could you post a screenshot of the error you get?
> 
> Thanks
> 
> Guillaume

Hello, Guija, Thanks for help!
<img width="737" alt="Screen Shot 2023-01-13 at 2 51 53 PM" src="https://user-images.githubusercontent.com/121477741/212406843-cfdf83f5-b1d3-47e1-af1c-3ac599ec310b.png">

This is Stardist 3D model, as you see, when I run the code in secton 5.2 (name:error mapping and quality matrics estimation, it show the error informations in here, 

the major problem is here, imsave(names[i], labels, polygons), I can run when I delete polygons, just leave names[i] and labels, but I had remembered polygons is used to build to 3D, I don't know whether good or not to delete polygons, do you have better solutions for here? I am worried that will cause bad effect in predictions(may show the 2D instead of 3D, because stardist 2D models don't have polygons in here), Do you have any comments for that?

**Comment by jinxsfe** [comment]
<img width="824" alt="Screen Shot 2023-01-14 at 11 48 53 PM" src="https://user-images.githubusercontent.com/121477741/212523467-4c584771-4a5b-4b95-9c63-79ae8a4d3d26.png">
I also have question for that when I put the real data(19.511,511), does some possible that I can run it without reduce the size of image? I am afraid the information will be loss, if I would reduce x y to half of 511. I try to use grid = (1,8,8) instead of 4 but faild, fov is (16,73,73) which is also small, does some possible situation to increase that problem?

**Comment by guijacquemet** [comment]
Hi,
@jinxsfe 
I have now uploaded a new version of the StarDist 3D notebook that should fix the first issue you reported.

Best wishes

Guillaume

**Comment by guijacquemet** [comment]
Hi,
I am now closing this issue. Let me know if you still have problems.
