### ISSUE TITLE
Unable to connect to GPU backend in pix2pix notebook

### ISSUE THREAD

**Issue by akabago** [HenriquesLab/ZeroCostDL4Mic#239]
Hello, I am using the pix2pix colab notebook with the dataset of the tutorial for Zenodo. But when I try to run it the following message from Google Colab appears: 
"Unable to connect to GPU backend. You are currently unable to connect to a GPU due to Colab's usage limits."
So I am not able to run this notebook, I do not know if this error is due to the Google Colab version I am ussing (the free of Google) or anything else.

**Comment by guijacquemet** [comment]
Hi,

This is due to the Google colab limitations. If you wait a day or so you should be able to run the notebook

Cheers

Guillaume
