### ISSUE TITLE
pix2pix Model Evaluation

### ISSUE THREAD

**Issue by akabago** [HenriquesLab/ZeroCostDL4Mic#247]
Hello I am trying to use the pix2pix notebook with the images of the example, as a tutorial. Once I´ve trained my model and want to evaluate it after I put the paths for the folders and so, when I run the cell the message that I have attached here appears. 
![image](https://user-images.githubusercontent.com/114954154/221858873-5c26fce9-0bb2-452b-bce4-2d3b234e2d58.png)
I don´t know how to fix this problem.

**Comment by alievakrash** [comment]
Hi, I have the same problem on the test dataset provided. It seems that somewhere over the script the shortname_no_PNG, as well as test_GT, etc are not defined.

**Comment by guijacquemet** [comment]
Hi, 
Do you still have an issue? The notebook is working well on my side when using the test dataset.

Here it looks like you are not loading your pix2pix model at all. could you provide a few more screenshot showing your issues?

Best wishes

Guillaume
