### ISSUE TITLE
3D stardist collab: request for preprocessing step: image sequence > separate z stack tiffs

### ISSUE THREAD

**Issue by Jiburii** [HenriquesLab/ZeroCostDL4Mic#25]
Dear all

Thanks for this resource. We are planning to do a lot of different 3D segmentation, and have run into a simple issue.

Mostly we export out images from a proprietary microscope file format to either an image sequence or a 4D tiff stack. At the moment, we are using an imagej macro to then make the tiff stack into separate tiff stacks for each time point, each containing a full z volume.

It would be great to integrate this step into the collab script, and I have tried but I can't figure out what to do/where to put it.

Could this be included as a 'preprocessing' cell? It would make this very easy to use resource even easier. 

Thanks,

Michael

p.s. happy to include example data if this request isn't clear

**Comment by Jiburii** [comment]
Hi Guillaume

Thanks for your positive message. This is going to be a powerful tool for us.

Yes, the prediction part is the bit i'm referring to.

I await the new cell - please let me know.

In case it is useful and for speed/efficiency purposes, I provide example data here: 

https://drive.google.com/drive/folders/1W77hsZSNx5QUoM-3FltsdtMPC-_0UrVv?usp=sharing

It is a 4D stack containing two timepoints back to back, each composed of 10 slices to make up each full z range.

For some reason, I have been getting a 'list index out of range' error using the local version of stardist 3D on these files, therefore I thought it might be useful to provide them to you in case two issues can be solved at once.

The vast majority of the data we have and want to segment are 4D timelapses like these - these tiff stacks are the export output of a proprietary microscope file format (.sld).

Thanks!

Michael

**Comment by guijacquemet** [comment]
Dear Michael,
I tested your file and it works just fine on my end. Can you tell me a little bit more about the error you are getting on your end?
What do you mean by the "local version of stardist 3D " ? are you using a local runtime?

Regarding your export, are you using slidebook ? I think slidebook offers the option to export 4D stacks as multiple stacks (one per time point). But I may be mistaken


![image](https://user-images.githubusercontent.com/25171305/84415779-ed16a480-ac1b-11ea-8ba6-b3797b91c67e.png)

Cheers
Guillaume

**Comment by Jiburii** [comment]
Hi Guillaume

Issue 1: SOLVED (although possibly a preprocessing cell could be useful for other users)

Re: export from slidebook. Wow I found this so confusing to start with but yes, you are right - you can export it in the correct format by just typing this as the file name. 

%N_C%C_T%T

Other slidebook users may not be aware that changing this part is the clunky way of choosing which files will in actuality be exported. It doesn't only change what is included in the file name, it changes what you export.

Issue 2: 

Yes, I mean that as well as trying to use the collab, I have installed stardist running on GPU locally, using the jupyter notebook 3_prediction here: https://github.com/mpicbg-csbd/stardist/tree/master/examples/3D

Here I run this cell:

```
img = normalize(X[2], 1,99.8, axis=axis_norm)
labels, details = model.predict_instances(img)
---------------------------------------------------------------------------

And receive this error:


IndexError                                Traceback (most recent call last)
<ipython-input-10-8679c3cd7667> in <module>
----> 1 img = normalize(X[2], 1,99.8, axis=axis_norm)
      2 labels, details = model.predict_instances(img)

IndexError: list index out of range
```
I understand that this is maintained by the StarDist people themselves, but it relates here because while it works in the collab, it doesn't seem to like my tiff files in the offline version.

Thanks,

M

**Comment by guijacquemet** [comment]
Hi,

you are most likely getting an error here because you are trying to analyse one stack while the stardist Demo notebook assumes that you are analysing multiples (using the demo data).

Here 
img = normalize(X[2], 1,99.8, axis=axis_norm)
will analysis X[2] which does not exist in your folder (you need at least 3 stacks). You need to modify the number.

If you want to see how we have implemented Stardist 3D in our notebook, you can easily access the underlying code by double-clicking on a cell:

![image](https://user-images.githubusercontent.com/25171305/84471267-afeafa80-ac8d-11ea-827e-8bd4927c3d1a.png)

I hope this helps

Cheers

Guillaume

**Comment by Jiburii** [comment]
It helps, thank you. 

I have solved these issues based on your suggestions. 

Cheers,

Michael
