### ISSUE TITLE
Error in Install Cellpose and 1.3. Load key dependencies Cellpose (2D and 3D)

### ISSUE THREAD

**Issue by DigiQueen** [HenriquesLab/ZeroCostDL4Mic#250]
Hello, I run into the following problems trying to Install Cellpose and load key dependencies for Cellpose (1.3. Load key dependencies). 

Load key dependencies
Libraries installed
Notebook version: 1.15.4
Latest notebook version: 1.15.4
This notebook is up-to-date.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-1-2ebaa8451511>](https://localhost:8080/#) in <module>
    403 # Build requirements file for local run
    404 after = [str(m) for m in sys.modules]
--> 405 build_requirements_file(before, after)

3 frames
[/usr/local/lib/python3.9/dist-packages/pandas/io/parsers/readers.py](https://localhost:8080/#) in _refine_defaults_read(dialect, delimiter, delim_whitespace, engine, sep, error_bad_lines, warn_bad_lines, on_bad_lines, names, prefix, defaults)
   1534 
   1535     if delimiter == "\n":
-> 1536         raise ValueError(
   1537             r"Specified \n as separator or delimiter. This forces the python engine "
   1538             "which does not accept a line terminator. Hence it is not allowed to use "

ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.

**Comment by guijacquemet** [comment]
Hi,
Thanks. This issue should now be fixed!

Please reopen this issue ticket if this is note the case

Best wishes

Guillaume
