### ISSUE TITLE
start_interactive_segmentation_local_installation

### ISSUE THREAD

**Issue by tomMEM** [HenriquesLab/ZeroCostDL4Mic#251]
Hello,
I try to run the ZeroCostDL4Mic using a local installation. 
Unfortunately, I was not able to get exactly the same environment as in the environment files suggested. 
Still, torch and tensorflow run with CUDA11.2. 
Testing the tutorial.py and ZeroCostDL4Mic_Interactive_annotations_Cellpose.ipynb, the scripts run into troubles at start_interactive_segmentation() with the following error message:
```File "E:\users\~\Python\envs\imjoy-interactive-segmentation\imjoy_interactive_trainer\interactive_trainer.py", line 106, in load_sample_pool
          mask = transform_labels(np.expand_dims(labels, axis=2))
        File "E:\users\~\Python\envs\imjoy-interactive-segmentation\imjoy_interactive_trainer\models\interactive_cellpose.py", line 132, in transform_labels
          flows = np.concatenate(
        File "<__array_function__ internals>", line 180, in concatenate
      ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)
```

I am wonder if somebody could give a hint how to solve this glitch. 
Thank u in advance. 

**Desktop (please complete the following information):**
 - Windows 11
 - Browser [chrome]
 - Version 111.0.5563.65

**Comment by tomMEM** [comment]
I had to change in "interactive_cellpose.py" the line 130 "veci = dynamics.masks_to_flows(label_image)[0]" to "veci = dynamics.masks_to_flows(label_image)#[0]" to get same dimensions of variables and to get start_interactive_segmentation() functional. However, I am not sure if dimension = 3 for labels and veci are correct.

**Comment by guijacquemet** [comment]
Hi @tomMEM ,
Unfortunately, we cannot help you much as we have not set up this notebook in a local environment ourselves.

FYI, [Cellpose 2](https://www.nature.com/articles/s41592-022-01663-4) allows you to retrain with your data in a GUI, so if that's your objective, it may be much easier than setting up our notebook locally.

Cheers

**Comment by tomMEM** [comment]
Hello @guijacquemet, Thank you for your feedback. Indeed, cellpose2 works well. I am trying to get local installations of your great collection of recent deep learning based image processing, mainly for educational purposes. Also, colab is hard to use from where I am, maybe IBM's Watson Studio would be an alternative. All the best. T
