### ISSUE TITLE
SEM images without pre/post processing of size 1024x1024 can be used to train the model and the number of images of size 1024x1024 required to train the model 

### ISSUE THREAD

**Issue by anirbannavalarch** [HenriquesLab/ZeroCostDL4Mic#254]
Hi,
I am looking forward to re-train the StarDist 2D model and generate a new model to process SEM images for my research. Samples training images (SEM) are attached herewith and the sizes of each of the images are 1024x1024. Further, all the training images are 8 bit. I am looking forward to know if the images that are attached herewith can be used as is to train the model without any pre/post processing of the images.
Moreover, I am also looking forward to know how many images that I will be requiring to train the model. Please explicitly let me know the number of images. I will be using Google Colab ZeroCostDL4Mic to create the model.

![TI_1](https://user-images.githubusercontent.com/128252461/228617936-6f3c044f-f4e7-4558-a439-9f921f4c8aab.jpg)
![TI_2](https://user-images.githubusercontent.com/128252461/228617939-945a8f4d-2fec-46b9-bd2d-9f62cdb77867.jpg)
ppen.

**Desktop :**
 - OS: Windows 8.1
 - Browser: chrome
 - Version: 109.0.5414.129 

Thanks for all your help.
Regards,
Anirban

**Comment by guijacquemet** [comment]
Hi @anirbannavalarch ,
It depends on what you want to segment.
StarDist would likely do a very good job a segmented the ovale shape structures on your images. However StarDist will likely not perform well on the very elongated shapes here.

If you want to segment everything, I would recommend using the Unet notebook instead.

Best wishes
Guillaume

**Comment by anirbannavalarch** [comment]
Hi  Guillaume,
Thanks for all your help and guidance.
Highly appreciated!
I will work on Unet notebook and use the same segmented training and mask
images to create the tensor flow model and verify the model using separate
quality control training source and mask image.
However, I am not able to use the tensor flow model created in StarDist and
U-net in ImageJ software as processing of section 5.3 is creating some
errors.
Please help me fix the error such that I can convert the tensor flow model
into a compatible ImageJ plugin.
If possible, please outline the necessary steps to fix the error.
Regards,
Anirban
