### ISSUE TITLE
Error when loading key dependencies CARE_2D

### ISSUE THREAD

**Issue by BelES123** [HenriquesLab/ZeroCostDL4Mic#255]
Hello, I run into this problem in step 1.3 load key dependencies in CARE_2D. Any ideas on how to fix it? 

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/127130599/228971521-7fb72c5e-afa6-492d-8fde-6742849283fe.png">

**Comment by guijacquemet** [comment]
Hi,

This issue should now be solved!

Let us know if you are still having issues

Cheers

Guillaume
