### ISSUE TITLE
Error encountered while performing error mapping and quality metrics estimation

### ISSUE THREAD

**Issue by anirbannavalarch** [HenriquesLab/ZeroCostDL4Mic#259]
Hi Team  ZeroCostDL4Mic,
Thanks for helping me.
I am looking forward to using 6 images (512x512) to evaluate the model. However, I have encountered an error in the error mapping and quality metrics estimation while evaluating my model as shown in the screenshot:
![image](https://user-images.githubusercontent.com/128252461/230484968-5c82ff3e-ddf5-4c23-abee-75dba93bb985.png)
Further, I am also enclosing the screenshot of training errors vs epoch number for your review:
![image](https://user-images.githubusercontent.com/128252461/230486896-3447b98b-f297-4c1c-8ba5-4d0b372604a0.png)
Also attaching the screenshot of the last few steps of the training:
![image](https://user-images.githubusercontent.com/128252461/230487525-0dd4c444-33fd-4e9e-8c75-c3df74a3492a.png)
Please help me fix the error.
**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser  chrome
 - Version  109.0.5414.129
 
Also, let me know the subsequent steps needed to use the trained model in FIJI.
Thanks for helping me.
Regards,
Anirban

**Comment by guijacquemet** [comment]
Hi @anirbannavalarch ,
Thanks for reaching out. 
From the error you describe it looks like the notebook is not able to find your ground truth. Perhaps you have an issue with the way they are named?

Cheers

Guillaume

**Comment by anirbannavalarch** [comment]
Hi  Guillaume,
Thanks for all your help and guidance.
Highly appreciated!
I am able to fix the issue.
However, I cannot use the tensor flow model created in StarDist as a plugin
in ImageJ software as the processing of section 5.3 is making some errors.
Please help me fix the error which will help me convert the tensor flow
model into a compatible ImageJ plugin.
Please outline the necessary steps to fix the error.
Also, share some videos if possible.
Regards,
Anirban

**Comment by esgomezm** [comment]
Hi @anirbannavalarch 
This error should be fixed in the new version of the notebook. Also, you can use StarDist in Fiji via deepImageJ as well if needed. 
I will close this issue, but feel free to reopen it if you still find the problem
