### ISSUE TITLE
Out of memory (RAM) using StarDist 3D colab script (pro version)

### ISSUE THREAD

**Issue by Jiburii** [HenriquesLab/ZeroCostDL4Mic#26]
**Describe the bug**

When I try to run StarDist 3D prediction step in google colab on a small subset (four timepoints, 10 z slices each) of my data, the runtime crashes and informs me it ran out of RAM.

The kernel restarts, and I have to install stardist dependencies again.

I treid upgrading to colab pro, using a 'High RAM' runtime mode. 

I also tried increasing the number of tiles It does not go away when I test a range of tiles from automatic to z=10 x=50 y=50 and beyond.

**To Reproduce**

Run the script on the data provided here (google drive link), using the 3D demo model weights.

https://drive.google.com/drive/folders/17q11-hAJjCs72YFbsVKoGve3e5nzXyJf?usp=sharing

**Expected behavior**

I would expect the 25 gb of RAM available to be enough for this, so it is strange.

**Desktop (please complete the following information):**
 - OS: Windows 10 home 64 bit
 - Browser: Chrome
 - Version: latest version of chrome

**Additional context**

This issue may be related to an as of yet unsolved tif file problem, where my tifs are different to yours somehow. Please note that these are ome tifs.

Thanks!

Michael

**Comment by guijacquemet** [comment]
Hi,
Thanks for reaching out. The issue appear to come from the way your files have been saved/exported. Once loaded using they, for some reason make, the RAM explode. If I open your files in ImageJ and resave them (without doing anything else), they now work just fine.
I tested a few different Tiff loader in the notebook but the results are the same in each case. So my advice is to process them differently. 
I hope this helps
All the best
Guillaume

**Comment by Jiburii** [comment]
Hi Guillaume

I am so thankful! 

It seems that slidebook exports a kind of tif that is not compatible with downstream python based applications. 

Your solution (resaving the tiff stacks in Fiji/ImageJ) solved my issue.

Thank you,

Michael

**Comment by guijacquemet** [comment]
Hi,
Glad to help!
Good luck
Cheers
Guillaume
