### ISSUE TITLE
Adjusting dependencies to JupySQL

### ISSUE THREAD

**Issue by idomic** [HenriquesLab/ZeroCostDL4Mic#260]
**Is your feature request related to a problem? Please describe.**
I think it'll be beneficial for you to use [Jupysql](https://github.com/ploomber/jupysql) in your repo as we've added support in many interactive features on top of `ipython-sql`. There's backward compatibility so it's just changing the dependency.

**Describe the solution you'd like**
Using the maintained package.

**Describe alternatives you've considered**
Replacing the dependency in the requirements.txt

**Comment by guijacquemet** [comment]
Hi,
Thanks for letting us know!
Cheers
Guillaume
