### ISSUE TITLE
StarDist 2D- Encountering an error while trying to export the model to Bioimage model zoo format(Section 5.3.)

### ISSUE THREAD

**Issue by anirbannavalarch** [HenriquesLab/ZeroCostDL4Mic#263]
Hi,
Thanks for creating ZCDL4Mic. I was able to create the model from scratch in StarDist 2D using the test and mask data set. However, while performing the quality control data I am encountering some warning. Attached is the screenshot of the warning sign. 
![image](https://user-images.githubusercontent.com/128252461/233817215-8d543009-d242-40c2-ac85-499409aa876b.png)
However, the model generated is able to perform predictions. Attached is the screenshot.
![image](https://user-images.githubusercontent.com/128252461/233817270-fd4b0d37-96c7-4d66-a1ed-44c61897279a.png)
However, I am encountering an error while trying to export the model to BioImage model zoo format(Section 5.3.) such that I can use it with DeepimageJ plugin in Fiji software and process my data. Attached is the screenshot of the error.  
 
![image](https://user-images.githubusercontent.com/128252461/233817473-b8966a15-96a3-4758-ae03-7b50c22bcdf5.png)
Please help me fix the error such that I can use the model in Fiji software.

Desktop (please complete the following information):

OS: Windows 8.1
Browser chrome
Version 109.0.5414.129
Thanks for helping me. I appreciate your help.
Regards,
Anirban

**Comment by esgomezm** [comment]
Dear Anirban, 

thank you for the issue. we identified it as well and trying to get it solved as soon as possible ([see here the issue](https://github.com/stardist/stardist/issues/229)).
Meanwhile, I can see that the quality assessment is performed correctly in the previous sections, so would you need the model exported to the BioImage Model Zoo? I can help with that.

Esti

**Comment by anirbannavalarch** [comment]
Hi Esti,
Thank you for your prompt reply.
Sincere apology for my late response.
My objective is to use the tensor flow model (created in StarDist 2D) in
Fiji software and process SEM image.
Please help me export the model from StarDist 2D to BioImage Model
Zoo/DeepImageJ such that it could be used in Fiji(imageJ) software.
Please outline the necessary processes that need to be done.
If possible please attach some relevant video outlining the steps.
Thanks for all your help.
Appreciated.
Regards,
Anirban

**Comment by anirbannavalarch** [comment]
Hi Esti,
Thanks for reaching out to me.
If you could help me use the tensor flow model in Fiji software by
converting it into Bioimage Model Zoo/DeepImageJ, it would be
really helpful.
Please outline the necessary processes that need to be done.
Also, if possible, attach relevant video outlining the steps.
Thanks for all your help.
Regards,
Anirban

**Comment by esgomezm** [comment]
Hi again,

Sorry for the late response. The export has been fixed and now it should work. To run the training in the notebook, please take a look at the wiki of ZeroCostDL4Mic (https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki). Regarding the execution of the model in Fiji, please, note that the current version of deepImageJ is not compatible with TensorFlow 2 (yet). This should be fixed this month. Meanwhile, you can work on the training and evaluation of the model. 

I will close the issue, but please do not hesitate to reopening it again if you still encounter problems,
Sincerely

**Comment by anirbannavalarch** [comment]
Hi Esti,
Thanks for helping me with this.
As suggested by you, I will work on training and model evaluation with my
image data.
Is the Bioimage IO model generated can be used in Imagej/Fiji.
Thanks for all your help.
Appreciated for helping me.
Regards,
Anirban
