### ISSUE TITLE
StarDist 2D- Encountering error while exporting the model to BioImage Model Zoo format 

### ISSUE THREAD

**Issue by monbsi** [HenriquesLab/ZeroCostDL4Mic#264]
Hello,
Thanks for developing the StarDist 2D module for segmentation. I was able to successfully create a preliminary model from scratch in StarDist 2d. However, while trying to export the trained model in BioImage Model Zoo format such that the model could be used in Fiji software, I am encountering an error while executing section 5.3 of StarDist 2D. Screenshot of the error is attached herewith
![image](https://user-images.githubusercontent.com/131627808/233876244-2fb1d142-319a-4feb-afa9-a8ac063f8afb.png)
Please if you could help me execute the final step such I can integrate the model in Fiji software and process the my data.
Screenshot of the other warning sign that I am encountering are attached herewith:
![image](https://user-images.githubusercontent.com/131627808/233876855-9026dc8d-ffe5-46c4-9231-acbe080537db.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser [ chrome]
 - Version [109.0.5414.129]

**Comment by esgomezm** [comment]
Hi!

We have just fixed it. Could you please try it now? I will close the issue. Please, reopen it if it does not work for you :)

thank you!
