### ISSUE TITLE
Dependencies txt files for local GPU use

### ISSUE THREAD

**Issue by harryofhorsley** [HenriquesLab/ZeroCostDL4Mic#267]
Hi guys,

Wanted to untilise local gpu and file system. Unfortunately, I can't find the dependencies txt file in the notebooks. Have checked u-net and unet 2d thus far.......am I being stupid? Very possible...

All the best,

Harry

**Comment by harryofhorsley** [comment]
Apologies - I'm referring to "requirements.txt" file referenced in your how to

**Comment by IvanHCenalmor** [comment]
Hi @harryofhorsley ,

Sorry for the slow answer. You will be able to find them in the [requirements_files folder](https://github.com/HenriquesLab/ZeroCostDL4Mic/tree/master/requirements_files) that is in the main folder of the GitHub repo: 

<img width="1379" alt="Screenshot 2023-08-01 at 09 41 00" src="https://github.com/HenriquesLab/ZeroCostDL4Mic/assets/47150974/1a48aae9-8ec8-4575-817b-8a92813e32f5">

Hope is not to late and that this helps you.
Iván.
