### ISSUE TITLE
MaskRCNN - Fiji macro

### ISSUE THREAD

**Issue by pejmanrasti** [HenriquesLab/ZeroCostDL4Mic#274]
Hello everyone,

I aim to use MaskRCNN on my data but I don't have a CSV file for them. It is a little confusing for me how should I make it to be compatible with the code. 
I read in the explanation that there is Fiji macro that can help to make them when mask segmentations are available. I have segmentation masks for my images and I would be thankful if you can send me an available link that I can download the Fiji macro.

**Comment by esgomezm** [comment]
Dear @pejmanrasti 

Sorry, for the confusion, the macro is here: https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/master/Tools/Annotate_MRCNN_Data.zip

Esti
