### ISSUE TITLE
Retain the image size of output for pix2pix model

### ISSUE THREAD

**Issue by Shawnmhy** [HenriquesLab/ZeroCostDL4Mic#277]
HI team, I am currently using pix2pix model for image translation. My inputs are of dimension 333 x 333 pixels. However, the prediction output from the pix2pix notebook implementation is 256 x 256. How can I retain the original dimension for my output? Thank you!

**Comment by guijacquemet** [comment]
Hi @Shawnmhy ,

Unfortunately, only image dimension multiples of 256 can be used in the current implementation. 
Best wishes

Guillaume
