### ISSUE TITLE
Patch Size Value Error and 3D Mask Creation

### ISSUE THREAD

**Issue by GionaKleinberg** [HenriquesLab/ZeroCostDL4Mic#29]
Hello, 

I am currently trying to use the notebook to count cells in a 3D image. I spent some time looking around for a guide on creating a 3D mask similar to the one used for the 2D notebook but couldn't find one. I used the provided tutorial for creating a 2D mask with the LOCI ROI Map plugin for each slice of an image with 4 slices then concatenating the ROI Maps into one 4 slice tiff. I figured starting on this small stack would be best for learning to use this tool and finding a way to create a larger training set but I've been running into errors when using the notebook. 

The first message that I saw was when I was setting the training parameters which read:
"Your chosen patch_size is not divisible by 8; therefore the patch_size chosen is now: 128
Parameters initiated."

When I continue with the notebook by using the data augmentation and creating the model, I get an error when trying to train the model which reads:

/usr/local/lib/python3.6/dist-packages/stardist/models/sample_patches.py in get_valid_inds(datas, patch_size, patch_filter)
     38 
     39     if not all(( 0 < s <= d for s,d in zip(patch_size,datas[0].shape) )):
---> 40         raise ValueError("patch_size %s negative or larger than data shape %s along some dimensions" % (str(patch_size), str(datas[0].shape)))
     41 
     42     if patch_filter is None:

ValueError: patch_size (4, 128, 128) negative or larger than data shape (143, 145, 4) along some dimensions

I've tried re-running everything without data augmentation and I've tried manually adjusting the patch heigh and patch size to see if I could get any values to work but no combination has yielded no errors. I'm assuming the main issue is that my training set of one 4 slice stack is too small and that is what is creating errors. The example training sets seem much much larger than what I'm currently working with.

If this is what is causing the errors, how can I get around this? The method I'm using right now to create the 3D Mask is pretty time consuming as I'm selecting every cell manually on each slice of the image. Using a full stack would take very long to create an ROI map. Is there a better way to create the target set of masks for a 3D image. I'm doubtful that I've been doing it the best way, and if there is a way to do it much quicker I should be able to use a larger stack and avoid the errors I've been getting.

Thanks!

**Comment by guijacquemet** [comment]
Hello,

Many thanks for reaching out!
Regarding the labelling, you could try to use LabKit as suggested by the Stardist Authors (see link)
https://github.com/mpicbg-csbd/stardist

Regarding the patch size error, would you be willing to share one example image? so I could have a look?
Cheers
Guillaume

**Comment by GionaKleinberg** [comment]
Hello and thanks for the reply,

I've looked into LabKit previously and it seems like you still have to isolate each cell manually. Running the segmentation process after creating labels of all cells on a slice doesn't really create anything resembling the clean mask shown in the example training set. I've tried playing around with this tool a lot but can't seem to find a way to get it to work right. For large stacks of images, it just doesn't seem like it would be feasible to manually select each individual cell on every slice. I would be very happy to hear I'm just not using this tool right and that it can create the mask needed easily.

Since it doesn't seem easy to balance a quality segmentation with a semi-automated process (seems like it's one or the other), I'm hoping that trying to fix the patch size error will help. Looking at the error message, it seems like an image had its dimensions switched around at some point which is causing the problem. That's why I think the 4 slice z dimension is the problem.

ValueError: patch_size (4, 128, 128) negative or larger than data shape (143, 145, 4) along some dimensions

Here is one of the slices of the ROI mask for one of the images to give you an idea of the small size that I'm currently trying to work with.
![image](https://user-images.githubusercontent.com/67409977/85748697-41b72680-b6d6-11ea-81b8-ac6887a85e5d.png)

**Comment by guijacquemet** [comment]
Hi,
Yes, unfortunately, the data labelling is very time-consuming and is definitively the limiting step. It is especially true for 3D segmentation.
Could you share one full stack (and associated mask) so I can try to replicate your patch error? 
It is currently very hard for me to see where the error is coming from
Cheers

Guillaume

**Comment by GionaKleinberg** [comment]
Of course, here are the 4 slice stack and ROI map I used which gave me the error.

[Source and ROI Map.zip](https://github.com/HenriquesLab/ZeroCostDL4Mic/files/4840827/Source.and.ROI.Map.zip)

**Comment by guijacquemet** [comment]
Hi,

I finally got the chance to test your images.
The main issue is that your number of Z is too low and that it confuses the Python loader (it thinks they are channels for some reason). It currently works with 5 z slices. 
Also, it would be best to save your masks as regular 8-bit images instead of 8-bit RGB images.
I hope this helps!
Cheers
Guillaume

**Comment by GionaKleinberg** [comment]
Hi,

Thanks for figuring out that issue and all your help in navigating this awesome tool, I got a chance to fix the issues you mentioned and successfully made the training set. I'm having trouble now however in applying the training set to new data.

I've run it several times and it seems to work on small image stacks (it worked on a 7 slice, and a 10 slice image) however whenever I try to run it on a full image stack (100-150 z slices) it runs into errors. This error happens even when I run it on something as small as 21 slices.

The error given is the OOM error when using the "automatic number of tiles" option. The notebook says the following:

"If you get an Out of memory (OOM) error when using the "Automatic_number_of_tiles" option, disable it and manually input the values to be used to process your images. Progressively increases these numbers until the OOM error disappear."

I've tried following these instructions but I'm not sure what value to increment the values by. I've tried incrementing it by 1 (ran it at 1 2 3 4 and 5 for each of the n_tiles values) and each time I do this, it gives me a new error:

NameError: name 'os' is not defined

Looks to be that this is happening because the whole notebook crashes and reloads the session and cannot find the training set I was just using so I end up having to redo everything to try again.

Do you have any ideas to solve these issues? I'm not sure why I would have problems with an image stack of as little as 21 slices since the example training set contained image stacks of 64 slices which are much bigger.  

I can't find a way to attach the image since the 21 slice image seems to be too big to attach with the 10MB limit of this forum.

**Comment by guijacquemet** [comment]
Hi,
Sorry for the slow reply. I am currently out of the office.
If your stack is very large, do not hesitate to try a large tile number. Especially for the first number (maybe 10-20).

Just to check.

Once you have trained a network (step 4) you do not need to do it again. In the prediction part (step 6) you can just indicate where you network was saved. So once a network is saved you just need to run step 1, 2 and 6.  Step 2 needs to be run at every session but step 3,4 and 5 can be skipped if you have a model that you are happy with.

When you restart the notebook after a crash, did you rerun step 2 ? if so do you still have the  "NameError: name 'os' is not defined" when running step 6?

Cheers

G

**Comment by GionaKleinberg** [comment]
Thank you for the info on using a previously trained model, I couldn't get it to work before because I was choosing a file path that was not specific enough but it works now.

The notebook still crashes when I set the tile sizes to as low as 4, 4, 4. I tried it with larger patch sizes and it also crashes. Anything lower than 4, 4, 4 gives me the OOM error. I'm not sure how to move forward. I did all these tests on an image stack of only 64 slices and the size is not that big. Do you have any ideas?

Thanks!

**Comment by guijacquemet** [comment]
Hi,
Great to hear that some of your issues have been solved.
I am not sure I understand your latter issue. Does it work with 4,4,4 ? If increase the number. You do not have to increase one by one. For very large stacks, use maybe 10, 4,4, or 20, 4, 4

Cheers

**Comment by GionaKleinberg** [comment]
Hello,
It does not work with 4,4,4. Since my last comment, I've kind of brute force tested a very large amount of combinations of patch sizes. I've tried 10, 4, 4, and 20, 4, 4 along with many other combinations varying each of the three numbers as high as 20 and as low as 1. I don't think I'll be able to fix this just by varying the three numbers as I either get an OOM error or the notebook crashes when it runs out of RAM which happens very quickly ( <5 minutes after attempting to test the model)

My current theory is that the trained model I'm using was trained with a very small (5 slice) image and that is what is causing problems. Does this sound plausible? Is there anything else that might be causing this issue?

**Comment by guijacquemet** [comment]
Hi,
How large is the stack you are trying to predict?
To me, it sounds like you have hit one of Google Colab limitations. you probably get the OOM error when the number of slice is too low. Your most likely get the RAM error when it is too high. 

One way to get around that (which is not very practical) would be to decrease the size of the stacks you want to predict.

**Comment by GionaKleinberg** [comment]
The stack I am trying to predict is 174 slices. I have tried trimming the stack though and get errors even when I try to predict on a 21 slice image.

That seems too low to have hit a limitation of Google Colab naturally. Do you think anything could be causing the notebook to use more RAM than normal?

**Comment by guijacquemet** [comment]
Ok, then that's indeed not a google colab limitation. 
Would you be able to share your trained model and the stack you want to predict?

**Comment by GionaKleinberg** [comment]
Absolutely, is there a google address I could share the folder on my google drive with? It doesn't seem like I can attach files that large here.

**Comment by guijacquemet** [comment]
Hi,
sure, you can use jacquemetguillaume {at} gmail.com

**Comment by GionaKleinberg** [comment]
I just shared the folder. It includes the training source images (training source) and ROI Maps (training target) used to create the model. I've trained the model multiple times so using any of the models in the Model folder will work the same. The image I am trying to predict on is in Test. 

Thanks again! I really appreciate your help in figuring out these issues.

**Comment by guijacquemet** [comment]
Hi,
Your model is not the issue. You are indeed hitting a Google Colab limitation. The main issue is that your stack is very very large. For some reason Stardist requires a very large amount of RAM to stitch the tiles back together. 
Your model works fine with an image size of 512x512 (90 z slices). So you could split your data in smaller chunk or you would need to run stardist on something that has more RAM than Google Colab.
![image](https://user-images.githubusercontent.com/25171305/88096134-da8a7600-cb9e-11ea-91d7-298aa3860e5d.png)
PS: your model would be much better if you used more than one field of view for training.
Cheers
G

**Comment by GionaKleinberg** [comment]
Thank you so much! I will look into a way to separate and stitch back smaller images from the main image. Do you know if there are any easy tools or pipelines to accomplish this? Could I just divide the image into 8 cubes (4  square quadrants each half the stack in depth) and then run stardist on each cube? I'm sure fiji has plugins that would make this easier than cropping the raw image 8 times.

Thank you for helping to figure out the issue!

**Comment by guijacquemet** [comment]
Hi, 
I am not aware of any plugin designed to do this.

@lucpaul , I seem to remember that you wrote a macro that can be used to split datasets?

**Comment by uschmidt83** [comment]
> The main issue is that your stack is very very large. For some reason Stardist requires a very large amount of RAM to stitch the tiles back together.

StarDist runs the neural network prediction step on separate tiles (when using the `n_tiles` parameter) and will stitch them back together without requiring extra memory. However, the subsequent non-maximum suppression step can require quite a bit of memory, depending on how many object candidates need to be processed.

> I will look into a way to separate and stitch back smaller images from the main image. Do you know if there are any easy tools or pipelines to accomplish this? Could I just divide the image into 8 cubes (4 square quadrants each half the stack in depth) and then run stardist on each cube?

It's not that simple. However, the latest release of StarDist includes a new function to predict on very large images. I've just finished making an [example notebook](https://github.com/mpicbg-csbd/stardist/blob/dev/examples/other2D/predict_big_data.ipynb) to demonstrate this. Although the notebook is for a 2D example, it should also work on 3D images.

**Comment by guijacquemet** [comment]
Thanks a lot @uschmidt83 
I will have a look at your notebook and see if we can implement this for our next release!

**Comment by GionaKleinberg** [comment]
Thank you for the info!

I'm having trouble recreating the results you obtained above. Cropping images to the dimensions you mentioned and adjusting the parameters the same way is causing my notebook to crash. It now crashes on even much smaller images. As I run the prediction on the test image it slowly increases to 100% progress then freezes for a while and eventually, the notebook crashes. I have not had this happen before as usually when it gets to 100% it works. 

Did you do anything else other than cropping the image stack that I might have missed?
