### ISSUE TITLE
UNET3D prediction problem

### ISSUE THREAD

**Issue by jinxsfe** [HenriquesLab/ZeroCostDL4Mic#296]
**Describe the bug**
 I use UNET 3D model to segment the 3Dobject, but the 3D visualization of the object is slice by slice, which is not continuous, When I get result for segmentation and open by icy, it has multichannel instead of multi-stack, I open python and save it for io.save.the result visualize at below, how to make them look more continuous, instead of slice by slice
**To Reproduce**
![image](https://github.com/HenriquesLab/ZeroCostDL4Mic/assets/121477741/7c920929-dd30-4d3a-8d18-29aaf5326645)

**Expected behavior**
<img width="576" alt="image" src="https://github.com/HenriquesLab/ZeroCostDL4Mic/assets/121477741/b8d9909b-9b9e-433f-8bfe-86d08c5689ee">

**Comment by jinxsfe** [comment]
<img width="640" alt="Screenshot 2023-10-08 at 10 40 55 AM" src="https://github.com/HenriquesLab/ZeroCostDL4Mic/assets/121477741/5e22898e-8613-44a4-84d7-0608d9671d2e">

**Comment by esgomezm** [comment]
Hi @jinxsfe I'm not sure what is exactly the issue with the notebook. Could you please, explain it with more details and maybe with screenshots of the notebook's output?

Thank you!
Esti

**Comment by jinxsfe** [comment]
Oh, sorry about my explanation, my question is when I segment the cell based on your algorithms, and I open it image on icy
<img width="922" alt="Screenshot 2023-10-09 at 1 46 15 PM" src="https://github.com/HenriquesLab/ZeroCostDL4Mic/assets/121477741/b1975ff6-fa7b-4b7f-ac6e-47d132fb3ca8">
 the result looks like, this, it's multiple channels, instead of multiple stacks, and when I open it by python function and save it again by io. save, the visualization of the image(one of the nucleus) is shown above(red), the surface is not continuous, seems the stack plied with each other.

**Comment by jinxsfe** [comment]
can you check the code that makes them directly segment and the result is a 3D stack? instead of multiple channels? or can you tell me why this happened?

**Comment by mdoaskndfweon** [comment]
@esgomezm

**Comment by mdoaskndfweon** [comment]
I also face the same problems,

**Comment by mariana-gferreira** [comment]
Hello @jinxsfe, the new version of the U-Net 3D notebook has fixed the issue of saving stacks as channels. 
Please run the updated version and let us know if you still encounter issues.

Thank you
Mariana

**Comment by esgomezm** [comment]
I'm closing the issue. If the problem still remains, please open it again
