### ISSUE TITLE
Enhancement Request: Pix2Pix Notebook - Export Trained Model to bioimage.io and deepImageJ Compatibility

### ISSUE THREAD

**Issue by cfusterbarcelo** [HenriquesLab/ZeroCostDL4Mic#303]
Hi, 

I've been using the Pix2Pix Notebook in ZeroCostDL4Mic for image-to-image translation and identified a missing feature for exporting trained models to the bioimage.io format. I've taken steps to integrate this capability into the notebook, but encountered an issue during installation in deepImageJ. This issue outlines the need for the Pix2Pix Notebook to support bioimage.io export and seeks assistance in resolving the installation error. I've attached the modified notebook and the resulting zip file for your review.

**Is your feature request related to a problem? Please describe.**
I encountered an issue with the Pix2Pix Notebook in ZeroCostDL4Mic, specifically related to exporting the re-trained or trained model to the bioimage.io format. Currently, there is no built-in functionality for this, and my attempts to manually export and install the model in deepImageJ resulted in an error: "Unable to read the rdf.yaml specifications file in the following folder."

**Describe the solution you'd like**
I propose enhancing the Pix2Pix Notebook to include a dedicated section for exporting the trained model to the bioimage.io format, similar to the functionality available for the StarDist notebook. This would enable users to seamlessly export their Pix2Pix models and subsequently upload them to the BioImage Model Zoo or install them in deepImageJ.

**Describe alternatives you've considered**
I attempted to address the issue by modifying the notebook to include an export feature for the bioimage.io format. However, the current implementation results in an error during the installation process in deepImageJ.

**Additional context**
I have prepared a modified version of the Pix2Pix Notebook with the added functionality for exporting to bioimage.io format. However, upon attempting to install the exported model in deepImageJ, I encountered the error mentioned above: "Unable to read the rdf.yaml specifications file in the following folder." I believe there might be an issue with the export process or the generated files.

Here's a link with the modified notebook of Pix2Pix and the exported model: [Drive Folder](https://drive.google.com/drive/folders/1uGxLoRGcqPm7fM5rDg5H2jTchYm9fZoX?usp=sharing)

**Comment by esgomezm** [comment]
Thank you! pix2pix now exports bmz models
