### ISSUE TITLE
CARE (3D) Google Colab - issue with GPU

### ISSUE THREAD

**Issue by AlejandraRM67** [HenriquesLab/ZeroCostDL4Mic#305]
**Describe the bug**
When installing the key dependencies I get some errors and then I don't have access to the GPU when I am actually using a V100 which works for other notebooks. 

**To Reproduce**

**1.Install CARE and dependencies**
**1.1. Install key dependencies:**
**I get the following errors:**
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-gbq 0.19.2 requires google-auth-oauthlib>=0.7.0, but you have google-auth-oauthlib 0.4.6 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.1/301.1 kB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for h5py (setup.py) ... error
  ERROR: Failed building wheel for h5py
ERROR: Could not build wheels for h5py, which is required to install pyproject.toml-based projects

**1.3. Load key dependencies:**
**I get the following warning:**
2.8.0
Tensorflow enabled.
/usr/local/lib/python3.10/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Libraries installed
Notebook version: 1.15.2
Latest notebook version: 1.15.2
This notebook is up-to-date.

**2. Initialise the Colab session**
**2.1. Check for GPU access:**
You do not have GPU access.
Did you change your runtime ?
If the runtime setting is correct then Google did not allocate a GPU for your session
Expect slow performance. To access GPU try reconnecting late

**Expected behavior**
I have followed the instructions and run the code cells in order, and I am connected to a V100 GPU, I would expect to have access to the GPU. I'm trying to use it like other times in the past but now it doesn't work.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version : 119.0.6045.199 (Build oficial) (x86_64)
 
Thank you in advance!!!!

**Comment by esgomezm** [comment]
Hi @AlejandraRM67 

Are you in Google Colab or locally? If locally, could you please try running the notebook using [DL4Miceverywhere](https://github.com/HenriquesLab/DL4MicEverywhere)? 
Thank you
Esti

**Comment by guijacquemet** [comment]
Hi,
I think this issue should now be fixed 
Cheers
Guillaume
