### ISSUE TITLE
new bug issue for UNET 3D

### ISSUE THREAD

**Issue by jinxsfe** [HenriquesLab/ZeroCostDL4Mic#319]
![image](https://github.com/HenriquesLab/ZeroCostDL4Mic/assets/121477741/2232570b-efd5-428b-a80b-9a26e5676817)
today I install the dependence for UNET3D, which show an error for this

**Comment by esgomezm** [comment]
Hi! I fixed the notebook. Please try it again. I'm closing the issue but if it remains unsolved, please reopen de issue
