### ISSUE TITLE
U-Net dependencies fail to import from bioimageio.core

### ISSUE THREAD

**Issue by JoachimGoedhart** [HenriquesLab/ZeroCostDL4Mic#320]
Hi, first of all thanks for making this platform. These are my first steps into training a DL network and I'm pretty excited about that!

Trying to load 'key U-Net dependencies' fails. It seems to hang on importing 'load_raw_resource_description' from 'bioimageio.core'
I enclose a screenshot of the error:
![U-Net-dep](https://github.com/HenriquesLab/ZeroCostDL4Mic/assets/39348589/5c1ed4bc-7f0b-4206-8fcc-19719fe3a313)

It seems related to issue #319, but since it is a different notebook I decided to open a new issue, I hope that's OK.

Best Regards,
Joachim.

**Comment by esgomezm** [comment]
Hi Joachim ,thank you for reporting it! Our bioimageio package has been updated but not the notebook accordingly. 

I just updated the notebook so this problem should be sorted. Can you please try it again? I will close the issue, but if it persists, do not hesitate opening it again
