### ISSUE TITLE
Load dependency error Stardist 2D Colab 

### ISSUE THREAD

**Issue by cshum1** [HenriquesLab/ZeroCostDL4Mic#327]
There are issues loading the necessary dependencies in section 1.3 of the StarDist_2D_ZeroCostDL4Mic.ipynb notebook when running it in colab on Chrome. This error is new since last week, I'm assuming due to package updates that have sparked incompatibility issues.
![stardist_colab_dependency_error](https://github.com/user-attachments/assets/2ec0874a-bd61-4439-8ed0-c402442a6c7a)

Let me know if anyone has suggestions on how to avoid these errors!

**Comment by guijacquemet** [comment]
Hi,

Thanks for reaching out, the issue was with the GPUtool package. The notebook should be working again.

**Comment by cshum1** [comment]
Wonderful, thanks for the quick fix!
