### ISSUE TITLE
Make a small logo for BioImage.IO

### ISSUE THREAD

**Issue by oeway** [HenriquesLab/ZeroCostDL4Mic#34]
Could you please make a simple and small logo image for displaying in [BioImage.IO](https://bioimage.io)?

The [current one](https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/master/Wiki_files/ZeroCostLogo.png) is a bit too big to fit in the community partners bar, and it takes long to load for slow network.

Squared png image, 100x100 pixels in size would be perfect.

**Comment by paxcalpt** [comment]
Going to keep this open until we make a decent icon, I temporarily uploaded a 100x100 placeholder

**Comment by guijacquemet** [comment]
We have now uploaded a new icon for ZeroCostDL4Mic !
