### ISSUE TITLE
Fix notebook preview link

### ISSUE THREAD

**Issue by oeway** [HenriquesLab/ZeroCostDL4Mic#35]
Right now the notebook preview app doesn't work properly due to the wrong value in the `source` field.

The way the "notebook preview" application works is to take the `source` field of the item and render a notebook preview page.

So we need to set a raw url to the ipynb file from github to the `source` field.

[This line](https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/307e945f3a6aed5f4bbc1ffc790f4827de67f689/manifest.bioimage.io.yaml#L130) for example, the `source` value should be changed to 
`https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/U-net_2D_ZeroCostDL4Mic.ipynb`

If you want to add a reference to github repo, set the `git_repo` field, so I would add `git_repo: https://github.com/HenriquesLab/ZeroCostDL4Mic`

**Comment by paxcalpt** [comment]
Should be fixed now, check and close please

**Comment by oeway** [comment]
No, it should starts with `https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/...`, the one we have now is for colab, we need one which serve the raw file from github.

I will fix that.
