### ISSUE TITLE
TensorFlow 2.x or PyTorch Implementation

### ISSUE THREAD

**Issue by gimseng** [HenriquesLab/ZeroCostDL4Mic#37]
**Is your feature request related to a problem? Please describe.**
I see that the google colab file (at least I'm using the Stardist_2D_ZeroCostDL4Mic.ipynb) is using tensorflow 1.x.

Is there a plan to upgrade to TF 2.x or implement similar things in PyTorch?

**Describe the solution you'd like**
If there is a plan, great ! Otherwise, I'm interested in contributing to either TF2.x or PyTorch if it is helpful or of any value.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by guijacquemet** [comment]
Hello,

Many thanks for your interest in our project. Regarding the version of TF or the use of Pytorch, we are currently limited to by the actual implementation of the Deep learning network provided by the original authors. We are not providing "new network" here, but rather notebooks that allow users to easily use them in Google Colab. Some notebook work using tensorflow, other using Pytorch.
You are correct some of the notebook are currently using tensorflow 1.x, but actually we are in the process of updating several of them to work in tensorflow 2.x
Cheers

**Comment by gimseng** [comment]
@guijacquemet Cool thanks ! Looking forward to the TF 2.x.
