### ISSUE TITLE
U-net patch generation

### ISSUE THREAD

**Issue by cselenyak** [HenriquesLab/ZeroCostDL4Mic#38]
Dear All, 

I started to use the U-net colab notebook with 1024x1024 images and masks and received the following error message during patch generation. I used the default parameter settings. I cropped these image because the original size was 1360x1024 and then the  same error occurred. What else can I try out to solve this issue?

Thank you! 

![errorUnet](https://user-images.githubusercontent.com/68633293/88143500-95def900-cbf7-11ea-9021-e464cedbc313.JPG)

**Comment by sfhbarnett** [comment]
I'm getting the same error with my files, they are slightly larger though. 2044x2048

images are 8bit

Thanks,
Sam

**Comment by sfhbarnett** [comment]
@cselenyak cselenyak

I have a solution that works until the main version is fixed.

If you haven't already, copy the notebook into your local environment.

if you right click on the "2. Install U-net dependencies" block and then go form>show code.

Then use ctrl+F to find the "convert2mask" call that isn't commented out (green), I think it's the second one down.

you want to change the code in the else statement to have a 0 on the end like this (bold added for emphasis):
`if pixel_threshold_array[int(round(len(pixel_threshold_array)*0.98))]>0:
      io.imsave(img_save_path, img_as_ubyte(normalizeMinMax(all_patches_img[i])))
      io.imsave(mask_save_path, convert2Mask(normalizeMinMax(all_patches_mask[i]),0))
    else:
      io.imsave(Patch_rejected+'/patch_'+str(i)+'_image.tif', img_as_ubyte(normalizeMinMax(all_patches_img[i])))
      io.imsave(Patch_rejected+'/patch_'+str(i)+'_mask.tif', convert2Mask(normalizeMinMax(all_patches_mask[i]),**0**))`

**Comment by cselenyak** [comment]
thank you, that helped me too!!

**Comment by Romain-Laine** [comment]
Hi everyone, thanks for your patience! I've not had time to look into the issue but as sfhbarnett highlights, it's a quick fix that will be easily incorporated in the next release ! And thanks for suggesting a fix already.

Romain

**Comment by Romain-Laine** [comment]
Hi all, I have included the fix to the new version! This will come with the new release this week.
Romain
