### ISSUE TITLE
Label-free prediction | Sizes of tensors dimensions error when training the network | fnet | on Google Colab

### ISSUE THREAD

**Issue by mpriessner** [HenriquesLab/ZeroCostDL4Mic#4]
**Describe the bug**
When loading my own images into the google colab workbook, when running "Train the model" for training it on my images I kept receiving the following error:
Error message:
"....
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 32 and 27 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:612"

**To Reproduce**
I just loaded the two folders (one for brightfield and one for fluorescence) with my z-stack images. The images had as I found out the wrong dimensions -> 20 images per stack (expected 32 or 16)

**Expected behavior**
The solution to this problem:
I found out that the number of images of the z-stack to be able to process by the NN needs to be in the power of 2 (2, 4, 8, 16, 32 ...). I tested it now with 16 and 32 and it works for me in that case. I think it is also important that all the images have the same number of images in the z-Stack.

I hope this helps some of you in the future!

**Comment by Romain-Laine** [comment]
Thanks for this! We will add this to our Tips and Tricks page!
