### ISSUE TITLE
Supporting interactive visualization and annotation via ImJoy

### ISSUE THREAD

**Issue by oeway** [HenriquesLab/ZeroCostDL4Mic#41]
FYI: With [a recent PR](https://github.com/imjoy-team/imjoy-rpc/pull/54) in ImJoy-RPC, it is now possible to run interactive widgets in Google Colab! I think this will be useful for some applications in Zero.

There are many possibilities, you can basically use any current and future ImJoy plugins in Colab, for example:
1. visualizing massive multi-scale images in zarr format, try the [vizarr](https://github.com/hms-dbmi/vizarr/pull/29) example: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hms-dbmi/vizarr/blob/master/example/mandelbrot.ipynb)
(also see [this PR](https://github.com/hms-dbmi/vizarr/pull/29))

2. get user annotation for e.g. segmentation, see an example that uses [Kaibu](https://kaibu.org) here: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1uwBG7mGnzcycwthucS5-I-KVSajIxUjq)

Also see [here](https://github.com/Kitware/itk-vtk-viewer/issues/336), that we may also support [itk-vtk-viewer](https://kitware.github.io/itk-vtk-viewer/) soon. 

<img width="1271" alt="Screenshot 2020-08-20 at 11 08 58" src="https://user-images.githubusercontent.com/478667/90752674-f84f1600-e2d7-11ea-94f5-5022719a5425.png">

**Comment by Romain-Laine** [comment]
This looks awesome, Wei ! Thanks for sharing !

**Comment by Romain-Laine** [comment]
We now have an Interactive Segmentation notebook using Kaibu as you describe! Thanks again, Wei for all your help and support on this!
