### ISSUE TITLE
single plane (FNET) free labeling live/dead cells

### ISSUE THREAD

**Issue by reinat168** [HenriquesLab/ZeroCostDL4Mic#44]
Hello,
I understand that FNET works only on 3D images. I would like to train 2D phase contrast images whether a cells is dead or a live - by training it first on fluorescence images. Will I be able to do it using the FNET or should I look for another solution?
Thank you,
Reinat

**Comment by guijacquemet** [comment]
Hi,
Thanks for reaching out. Fnet indeed only works with 3D stacks. If you want to make predictions from 2D images then you could consider trying the ZeroCostDL4Mic pix2pix and/or 2D CARE notebooks. 
Cheers
Guillaume

**Comment by reinat168** [comment]
Thanks for your suggestions!
