### ISSUE TITLE
Problem to conect to Gdrive

### ISSUE THREAD

**Issue by insectito** [HenriquesLab/ZeroCostDL4Mic#45]
Hi,

I'm having trouble in the step where we are supposed to conect to google drive. I do as it says and I put the autorization code but then a time-out error apears. 
![image](https://user-images.githubusercontent.com/70763934/92268542-7c112100-eeda-11ea-8892-5f6e79193e43.png)

I tried with 2 different accounts, 2 browsers and 2 computers and still have the same issue.
Is this happening to other people?

Thank you

**Comment by guijacquemet** [comment]
Hi,
Thanks for reaching out!
Mounting Gdrive works fine on my end. 
 At what stage of the process does the error occur? After you copy and paste the link?
Also, did you make a copy of the notebook you are trying to use in your own GDrive? This is not required but can improve the stability
Cheers
Guillaume

**Comment by sbonaretti** [comment]
Hi! 
Same issue here - tried a couple of times. Thanks!

<img width="802" alt="Screen Shot 2020-09-05 at 11 52 26 AM" src="https://user-images.githubusercontent.com/13563701/92302695-62b9b480-ef6e-11ea-8ba2-a6ac3dc3eca0.png">

**Comment by guijacquemet** [comment]
Strange. Looking for similar issues online here are some common fixes:

- Try to manually copy the authorization code from the authorization button instead of clicking the copy button. 
- Too many files (thousands) in the GDrive top folder can also cause a timeout
-  Pressing Factory reset runtime may help

**Comment by guijacquemet** [comment]
Actually I also get the time-out when copying the authorization code using the "copy" button, copying the code directly works. Hopefully, this also solves your issues.

**Comment by sbonaretti** [comment]
Yes, it works! I copy/pasted manually instead of using the "copy" button, and it worked. Thanks for helping me on a Saturday! :)
