### ISSUE TITLE
run notebooks with local resources

### ISSUE THREAD

**Issue by pedgomgal1** [HenriquesLab/ZeroCostDL4Mic#47]
Hi guys!

first, congratulation for this awesome platform. I have been trying some notebooks, for example, the N2V one to denoise my noisy non-paired images. In my case, the free resources provided from Google Colab are not enough (i.e. RAM memory) to completly run the algorithm. Thus, I have tried to use the computing power of my local machine after "connecting to local environment of execution". This option only reports problems and tensorflow errors along the notebook execution... 

It there any tutorial or notebook available to work with both local enviroment and google colab resources? This would be a huge improvement for us, people with light knowledge in deep-learning but strongly interested in its applicability! 

Thank you in advance! best wishes!
Pedro

**Comment by guijacquemet** [comment]
Hi Pedro,

Many thanks for reaching out! We are currently working on a tutorial to explain how to connect ZeroCostDL4Mic to a local environment. It will not be available just yet though...
Yes, when connecting to your local environment you need to install several of the dependencies that are likely missing from your own computer.

Regarding N2V, are you running into GPU or Runtime RAM issues? if the Runtime RAM is running out, you could try to disable N2V augmentation. This often help fix Runtime issues. Especially if your training dataset is very large (ie large 3D stacks). 
If you are running out of GPU RAM, decreasing the patch size should help.
If you have a powerful computer, you could also try the Fiji N2V plugin
