### ISSUE TITLE
Problems running own data through Stardist Colab Notebook

### ISSUE THREAD

**Issue by kjmeade** [HenriquesLab/ZeroCostDL4Mic#48]
Hi, 

Thank you for creating these notebooks, 

I know little about coding so they are very useful. 

I've just had a couple of problems I was hoping you could help with please.

My laptop is installing the most up to date version of Numpy and Scipy which do not work with the code, as shown in the screen shots below.
![Numpy_Scipy_Issue](https://user-images.githubusercontent.com/71271677/93098738-1de4fa80-f69f-11ea-99b6-3de74a0ffa55.png)

![1st_Issue(Which_was_resolved)](https://user-images.githubusercontent.com/71271677/93098733-1cb3cd80-f69f-11ea-9b55-073e2a586411.png)

 I initially had a problem with my data not being read properly (Also shown in the screen shots) however you kindly offered guidance and I made sure that my images had been converted into the correct 8-bit tiff format. 

After trying the notebook again, I unfortunately came across another problem which I was hoping you would be able to provide guidance on how to overcome please. I attached the problem below. 

![New_Issue](https://user-images.githubusercontent.com/71271677/93098669-09a0fd80-f69f-11ea-8e96-ee4dc51e0953.png)

Thank you

**Comment by guijacquemet** [comment]
Hi,
Thanks for reaching out!
For your first error, this is normal. This does not affect the notebook functionalities.
Regarding your third issue, to me, it looks like your mask images are saved in the wrong format. Your masks should be saved as either 8bit or 16 bits tif images where each thresholded nuclei/ object has a different intensity value. These masks should also be 2D images. The error displayed here indicates that the image shape is wrong. 
Check our wiki here for more details on how to generate your own masks: https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki/Stardist
Cheers
Guillaume

**Comment by kjmeade** [comment]
Hi Guillaume,

Thank you so much for all of your help, I will have another go and see if I
can get the data to work.

Thanks again,
Katherine

**Comment by guijacquemet** [comment]
No worries. Do not hesitate to reach out if you are still having issues!

Cheers

Guillaume
