### ISSUE TITLE
U-net v1.10 "- loss: nan - val_loss: nan",  v1.5 ValueError: Tensor conversion requested dtype float32_ref , v1.10 

### ISSUE THREAD

**Issue by NuriaTaberner** [HenriquesLab/ZeroCostDL4Mic#55]
Hello, 

ERROR 1: I am trying to train U-Net with the last version, but I get "- loss: nan - val_loss: nan" (see below)

ERROR 2: Then I also tried an older version that in the past gave me better results ( v1.5. ), but in this case I get the following error: "_ValueError: Tensor conversion requested dtype float32_ref for Tensor with dtype float32: <tf.Tensor 'training_1/Adam/Adam/conv2d_1/kernel/m/Initializer/zeros:0' shape=(3, 3, 1, 64) dtype=float32>_" (see below)

Any idea of what I am doing wrong?

ERROR 1:
----------------------------------------------------------------------------------------------------------------------
Epoch 1/200
Found 21 images belonging to 1 classes.
Found 2 images belonging to 1 classes.
Found 2 images belonging to 1 classes.
Found 21 images belonging to 1 classes.
4/4 [==============================] - 3s 686ms/step - loss: 48540198518.8084 - val_loss: 10300715008.0000

Epoch 00001: val_loss improved from inf to 10300715008.00000, saving model to /content/gdrive/My Drive/Colab Notebooks/unet-master/Nuclei/640/reduced/re-model/re-model-22October/weights_best.hdf5
Epoch 2/200
4/4 [==============================] - 1s 338ms/step - loss: 5460510654.4727 - val_loss: 69490.6875

Epoch 00002: val_loss improved from 10300715008.00000 to 69490.68750, saving model to /content/gdrive/My Drive/Colab Notebooks/unet-master/Nuclei/640/reduced/re-model/re-model-22October/weights_best.hdf5
Epoch 3/200
4/4 [==============================] - 1s 330ms/step - loss: 182848.7949 - val_loss: 264032.6875

Epoch 00003: val_loss did not improve from 69490.68750
Epoch 4/200
4/4 [==============================] - 1s 330ms/step - loss: 238031.1406 - val_loss: 21348.3184

Epoch 00004: val_loss improved from 69490.68750 to 21348.31836, saving model to /content/gdrive/My Drive/Colab Notebooks/unet-master/Nuclei/640/reduced/re-model/re-model-22October/weights_best.hdf5
Epoch 5/200
4/4 [==============================] - 1s 329ms/step - loss: nan - val_loss: nan

---------------------------------------------------------------------------------------------------------
/
/
/
/

ERROR 2:
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-9-391cf671dad5> in <module>()
      3 start = time.time()
      4 # history = model.fit_generator(train_datagen, steps_per_epoch = number_of_steps, epochs=epochs, callbacks=[model_checkpoint,csv_log], validation_data = validation_datagen, validation_steps = validation_steps, shuffle=True, verbose=1)
----> 5 history = model.fit_generator(train_datagen, steps_per_epoch = number_of_steps, epochs=epochs, callbacks=[model_checkpoint, reduce_lr], validation_data = validation_datagen, validation_steps = validation_steps, shuffle=True, verbose=1)
      6 
      7 # Save the last model

17 frames

/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1656             use_multiprocessing=use_multiprocessing,
   1657             shuffle=shuffle,
-> 1658             initial_epoch=initial_epoch)
   1659 
   1660     @interfaces.legacy_generator_methods_support

/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
     40 
     41     do_validation = bool(validation_data)
---> 42     model._make_train_function()
     43     if do_validation:
     44         model._make_test_function()

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in _make_train_function(self)
    510                     training_updates = self.optimizer.get_updates(
    511                         params=self._collected_trainable_weights,
--> 512                         loss=self.total_loss)
    513                 updates = (self.updates +
    514                            training_updates +

/tensorflow-1.15.2/python3.6/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py in get_updates(self, loss, params)
    502         if g is not None and v.dtype != dtypes.resource
    503     ])
--> 504     return [self.apply_gradients(grads_and_vars)]
    505 
    506   def _set_hyper(self, name, value):

/tensorflow-1.15.2/python3.6/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py in apply_gradients(self, grads_and_vars, name)
    431         _ = self.iterations
    432         self._create_hypers()
--> 433         self._create_slots(var_list)
    434 
    435       apply_state = self._prepare(var_list)

/tensorflow-1.15.2/python3.6/tensorflow_core/python/keras/optimizer_v2/adam.py in _create_slots(self, var_list)
    147     # Separate for-loops to respect the ordering of slot variables from v1.
    148     for var in var_list:
--> 149       self.add_slot(var, 'm')
    150     for var in var_list:
    151       self.add_slot(var, 'v')

/tensorflow-1.15.2/python3.6/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py in add_slot(self, var, slot_name, initializer)
    583             dtype=var.dtype,
    584             trainable=False,
--> 585             initial_value=initial_value)
    586       backend.track_variable(weight)
    587       slot_dict[slot_name] = weight

/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/variables.py in __call__(cls, *args, **kwargs)
    258       return cls._variable_v1_call(*args, **kwargs)
    259     elif cls is Variable:
--> 260       return cls._variable_v2_call(*args, **kwargs)
    261     else:
    262       return super(VariableMetaclass, cls).__call__(*args, **kwargs)

/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/variables.py in _variable_v2_call(cls, initial_value, trainable, validate_shape, caching_device, name, variable_def, dtype, import_scope, constraint, synchronization, aggregation, shape)
    252         synchronization=synchronization,
    253         aggregation=aggregation,
--> 254         shape=shape)
    255 
    256   def __call__(cls, *args, **kwargs):

/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/variables.py in <lambda>(**kws)
    233                         shape=None):
    234     """Call on Variable class. Useful to force the signature."""
--> 235     previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
    236     for _, getter in ops.get_default_graph()._variable_creator_stack:  # pylint: disable=protected-access
    237       previous_getter = _make_getter(getter, previous_getter)

/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/variable_scope.py in default_variable_creator_v2(next_creator, **kwargs)
   2550       synchronization=synchronization,
   2551       aggregation=aggregation,
-> 2552       shape=shape)
   2553 
   2554 

/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/variables.py in __call__(cls, *args, **kwargs)
    260       return cls._variable_v2_call(*args, **kwargs)
    261     else:
--> 262       return super(VariableMetaclass, cls).__call__(*args, **kwargs)
    263 
    264 

/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/resource_variable_ops.py in __init__(self, initial_value, trainable, collections, validate_shape, caching_device, name, dtype, variable_def, import_scope, constraint, distribute_strategy, synchronization, aggregation, shape)
   1404           aggregation=aggregation,
   1405           shape=shape,
-> 1406           distribute_strategy=distribute_strategy)
   1407 
   1408   def _init_from_args(self,

/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/resource_variable_ops.py in _init_from_args(self, initial_value, trainable, collections, caching_device, name, dtype, constraint, synchronization, aggregation, distribute_strategy, shape)
   1536             initial_value = ops.convert_to_tensor(
   1537                 initial_value() if init_from_fn else initial_value,
-> 1538                 name="initial_value", dtype=dtype)
   1539           if shape is not None:
   1540             if not initial_value.shape.is_compatible_with(shape):

/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py in convert_to_tensor(value, dtype, name, preferred_dtype, dtype_hint)
   1182   preferred_dtype = deprecation.deprecated_argument_lookup(
   1183       "dtype_hint", dtype_hint, "preferred_dtype", preferred_dtype)
-> 1184   return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
   1185 
   1186 

/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py in convert_to_tensor_v2(value, dtype, dtype_hint, name)
   1240       name=name,
   1241       preferred_dtype=dtype_hint,
-> 1242       as_ref=False)
   1243 
   1244 

/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx, accepted_result_types)
   1271       raise ValueError(
   1272           "Tensor conversion requested dtype %s for Tensor with dtype %s: %r" %
-> 1273           (dtype.name, value.dtype.name, value))
   1274     return value
   1275 

ValueError: Tensor conversion requested dtype float32_ref for Tensor with dtype float32: <tf.Tensor 'training_1/Adam/Adam/conv2d_1/kernel/m/Initializer/zeros:0' shape=(3, 3, 1, 64) dtype=float32>

----------------------------------------------

**Comment by Romain-Laine** [comment]
Hi NuriaTaberner,
ERROR 1:
I have just tested the current notebooks on our test dataset and have not had any issue so it looks like it's not a general problem. But I have seen this problem in the past and that came from the data augmentation and more specifically the shifts in the data augmentation. 
So try and disable augmentation or disable just the shifts in the augmentation.
This seems to me like it's an issue where the loss get divided by zero in certain region of the image, say where it's shifted because the model learns to predict this with 100% confidence, but I might be completely wrong there.

ERROR 2:
If I remember correctly, Colab changed a few of its default packages some time ago, so that may have made the older versions obsolete. Anyway, in general, it's better to use the latest version unless there is something critical that changed and made your analysis impossible.

I hope this helps!

Romain

**Comment by NuriaTaberner** [comment]
Dear Romain

Thank you very much for your answer. 
I disabled augmentation and/or shifts, but the error persisted. 

For now I am trying to understand a bit more how the program works to see if I can fix the problem with my data... Let me know if you have any other idea. 

I noticed my labelled data had some gray regions due to scaling. I made a clear binary image. I checked both with white areas being 255 or 1 in 8bit images. But all the trials kept giving the same error. 

I tried modifying my learning rate. Right now it is 0.0000005 (which worked in the past), But I keep getting infinity:

> "4/4 [==============================] - 2s 536ms/step - loss: 0.9259 - val_loss: nan
> Epoch 00001: val_loss did not improve from inf"

I also noticed, right now I have the following messages which don't look good:

> WARNING:tensorflow:From /tensorflow-1.15.2/python3.6/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.
> 
> Epoch 1/300
> Found 0 images belonging to 1 classes.
> Found 1 images belonging to 1 classes.
> Found 1 images belonging to 1 classes.
> Found 0 images belonging to 1 classes
> 
> 

In a previous training with the same data I got:

> Epoch 1/200
> Found 65 images belonging to 1 classes.
> Found 31 images belonging to 1 classes.
> Found 65 images belonging to 1 classes.
> Found 31 images belonging to 1 classes.

If anything rings a bell, please let me know. 

Thank you

Nuria

**Comment by Romain-Laine** [comment]
Hi Nuria, 
Yes, it looks like no files were found for you to do the training on, so I am not surprised you're getting this issue.
Could you please check that the files are in the right folder and also let me know what extension/format these files are in?

Check a couple of other things please:
- 'Training on patches of size (x,y):' --> what does this say?
- Does running section 3.1 display properly some patches for you at the end?
- What did you use as percentage of validation?

With this, I'll be able to tell you a little more.
Also, you could send me a couple of exemple data for me to check.

Cheers,

Romain

**Comment by NuriaTaberner** [comment]
Dear Romain, 

Thank you very much for your answer. 

I followed your comments. 

Regarding the input data. It was on the right place. Everything is 640X640 8-bit. 
My training source had regions with zero values pixels. I filled those with and average noise. 

My patch desired size was 640x640, as I do not want to do any patching. I changed it to 320X320, and then I do get images for training and I do not get infinity in the val_loss anymore:

> Epoch 1/300
> Found 11 images belonging to 1 classes.
> Found 25 images belonging to 1 classes.
> Found 11 images belonging to 1 classes.
> Found 25 images belonging to 1 classes.


However, the actual number of images I had input are 96, not 36 as it says after running 4.1 section:

> ---------------------------- Main training parameters ----------------------------
> Number of epochs: 300
> Batch size: 4
> Number of training dataset: 36
> Number of training steps: 24
> Number of validation steps: 3
> ---------------------------- ------------------------ ----------------------------

Moreover, I don't obtain a good val_loss curve, using the same parameters I previously used (with an older version). The last time I tried I got funny spikes. 
![Capture](https://user-images.githubusercontent.com/15859461/98621191-101fbe80-234a-11eb-861f-918406c69067.PNG)

My previous training with an older version (no patching), the same data an the same parameters gave a model with what I was much more pleased:

> {'lr': 4.999999987376214e-07, 'beta_1': 0.8999999761581421, 'beta_2': 0.9990000128746033, 'decay': 0.0, 'epsilon': 1e-07, 'amsgrad': False}
> ---------------------------- Main training parameters ----------------------------
> Number of epochs: 200
> Batch size: 4
> Number of training dataset: 96
> Number of training steps: 24
> Number of validation steps: 8
> ---------------------------- ------------------------ ----------------------------

> Epoch 1/200
> Found 65 images belonging to 1 classes.
> Found 31 images belonging to 1 classes.
> Found 65 images belonging to 1 classes.
> Found 31 images belonging to 1 classes.
> 24/24 [==============================] - 114s 5s/step - loss: 0.6915 - acc: 0.6168 - val_loss: 0.6642 - val_acc: 0.7698

![Capture-2](https://user-images.githubusercontent.com/15859461/98621458-9f2cd680-234a-11eb-8751-b355e2e8144d.PNG)

I wonder if with the patching, it is really using all my images. Could I run it without any patching?

**Comment by Romain-Laine** [comment]
Hi Nuria,
Thanks for the info. We have just released a new version today so please try this one and see how things change.
Using the following suggestions if possible:
- I suggest you use a 512x512 patch size by the way, it's the biggest 2^n for you. I show below, again, the info about patch size. That's really quite important to read these details in this case.
<img width="1006" alt="Screenshot 2020-11-13 at 13 00 32" src="https://user-images.githubusercontent.com/21193399/99074754-3d6da600-25b0-11eb-872c-88fece5900a8.png">

- Disable data augmentation.

A few more questions for you, please:
- What release version of the notebook did you use to get the results you're "happy" with (as above)?
- Can you please show example images here of images and masks?
- Are all your files in the same file format with an exact 1 to 1 correspondence between the image and mask?

It's possible that images may be excluded if there isn't enough data in it, if it's all background it's currently excluded. More precisely each patch needs to contain at least 5% of foreground pixel to be a valid patch. 

See what patches are created in the content/ folder created for that in the session, see whether there are many patches that are rejected. This could easily explain what you have here.

<img width="1440" alt="Screenshot 2020-11-13 at 13 06 44" src="https://user-images.githubusercontent.com/21193399/99075272-1b285800-25b1-11eb-8d68-354ab1de56b9.png">

Let me know how this goes!
And please answer to my questions, otherwise I will not be able to help you much.

Cheers,

Romain

**Comment by NuriaTaberner** [comment]
Dear Romain, 

Thank you very much for all the help. 

 - I tried the new version. 

 - I use now 512x512

 - Disabled data augmentation

 - The previous version with what I was happier was probably 1.5 (sorry I didn't keep track), but last time I tried I was getting new errors as mentioned on the first message. 

 - Here is an example of the patches. As you can see, in my images, only very few pixels are positive in the label images. I want to segment features that are not specifically labelled, but recognizable.  
![Path_example](https://user-images.githubusercontent.com/15859461/99364406-47b5da00-28f9-11eb-9555-afb76bd16d14.PNG)
 - Also, when I look at the folders you mentioned, there are very few patches. Even though I uploaded 96 images of 640x640 pixels, only 11 patches seem to be created and only 2 are found in the rejected folder. 
This matches with the "images found":

> Epoch 1/300
> Found 3 images belonging to 1 classes.
> Found 8 images belonging to 1 classes.
> Found 3 images belonging to 1 classes.
> Found 8 images belonging to 1 classes.
> 24/24 [==============================] - 16s 684ms/step - loss: 0.8984 - val_loss: 0.8238

and a not so good fitting: 
![fitting](https://user-images.githubusercontent.com/15859461/99365322-784a4380-28fa-11eb-87de-d6bdcca7d371.PNG)

 - I checked that the files and masks are 1 to 1 and they are. 

 - The last model gave relatively good results (although not as good as in the past) when I run section 5.2 for quality control. 
![QualityControl](https://user-images.githubusercontent.com/15859461/99365614-df67f800-28fa-11eb-9c72-26697471e6b9.PNG)

However, when I run 6, I get a prediction that is worse and also straight bright lines where I think there has been the patching. 
![Prediction](https://user-images.githubusercontent.com/15859461/99365861-2bb33800-28fb-11eb-93b9-a514d5b86a63.PNG)

 - For what you say, it seems to me that for my data, the patching removes most of my training images, therefore the model fitting is not that good because there is effectively too little data. So if I ask the network to do the training on the original data I gave, then it uses all the images. 
in 4.1 I did the following quick change: 

> # !!! WARNING !!! Check potential issues with resizing at the ImageDataGenerator level
> # (train_datagen, validation_datagen) = prepareGenerators(Training_source, Training_target, data_gen_args, batch_size, target_size = ImageSize)
> #(train_datagen, validation_datagen) = prepareGenerators(Patch_source, Patch_target, data_gen_args, batch_size, target_size = (patch_width, patch_height))
> (train_datagen, validation_datagen) = prepareGenerators(Training_source, Training_target, data_gen_args, batch_size, target_size = (patch_width, patch_height))

The it evaluates all the images:
> Epoch 1/300
> Found 68 images belonging to 1 classes.
> Found 28 images belonging to 1 classes.
> Found 68 images belonging to 1 classes.
> Found 28 images belonging to 1 classes.

I am running it now and I will not be able to check until tomorrow. But I wanted to update. The validation loss, seems to be better than with the patches.

**Comment by Romain-Laine** [comment]
Hi Nuria,
OK, now I see the problem. 
I have now uploaded a new version of the notebook (v1.11.1) with bug fixes and modifications to allow you to do what you want.

First I have found a small bug in how the rejected patches are saved, which meant that it looked like there was only one rejected patch but there actually were many (this is what was going on with your dataset). This is now fixed. Try and re-run the patch generation and you'll see many more rejected patches.

Second, the patch rejection was hard coded to be rejecting all patches that had less than 2% of foreground pixels. This was a bit arbitrary and is now a parameter (`min_fraction`) adjustable by the user in the new version. So I suggest you select a `min_fraction` of either 0 or lower until you have enough patches for you to be happy with while still rejecting some empty patches.

So please try again with the new version and it should hopefully work with all the dataset now (providing you set `min_fraction` to 0). 

Have a go at this and let me know how it works !

Romain

**Comment by NuriaTaberner** [comment]
Dear Romain, 

Thank you very much. I think this changes let me get a good model for my type of data!
![QualityControl](https://user-images.githubusercontent.com/15859461/99636173-6eede200-2a86-11eb-8e90-f1a78528ca98.PNG)

I still need to play with the parameters I use so maybe I ask something again in the future, but for now I think this topic can be closed. 

Best wishes, 

Nuria

**Comment by Romain-Laine** [comment]
Excellent! 
That's great to hear! Good luck and feel free to let me know if you have any other issues!
One think to play with carefully is data augmentation, which may help you out.

Romain

**Comment by Romain-Laine** [comment]
Just one quick note that just occurred to me, Nuria!
You can use the notebook with DeepImageJ export (currently in beta but fully tested anyway) and do the predictions in Fiji/DeepImageJ instead of our notebook! They do a nice patch merging that will get rid of the lines that you see on predictions (we will be implementing something similar in the notebook eventually but not at the moment)!
https://deepimagej.github.io/deepimagej/

I hope this helps !

Romain

**Comment by NuriaTaberner** [comment]
Thank you Romaine! 
These days I cannot try it because I'm focusing in something else. But for sure I will try DeepImageJ once I get back to this topic.
