### ISSUE TITLE
CellPose

### ISSUE THREAD

**Issue by LPUoO** [HenriquesLab/ZeroCostDL4Mic#58]
Hello,

I just wanted to say that it would be super nice if there was an ImageJ-friendly [CellPose](https://github.com/MouseLand/cellpose) notebook.

:)

Thanks a lot!

**Comment by guijacquemet** [comment]
Hi,

Thanks for the notebook request! Cellpose is on our list. We will let you know when we have something to share!

Cheers

Guillaume

**Comment by pr4deepr** [comment]
I wrote a basic one for a folder of multi channel 2D tif images..
https://colab.research.google.com/drive/1alUHCdUNeeKAN6uqjqzKkxkvCxlWdvWl
As the 2D images are quick to process I've added an option to preview segmentations so as to tune the diameter, flow threshold and cell probability threshold just like the cellpose gui..
Would this be of interest @guijacquemet ?

**Comment by guijacquemet** [comment]
Hi @pr4deepr ,
Thanks a lot for sharing! Look great!
In case you decide to add the option of training/retraining CellPose, let us know! we would be happy to advertise your work on the ZeroCostDL4Mic wiki. See our guidelines if you are interested:
https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki/How-to-contribute

**Comment by pr4deepr** [comment]
Thanks. 
I have tried training on local jupyter notebooks, which I can convert to Google Colab ones. 
I can definitely do this.  I would be happy to try this and also get feedback..

**Comment by pr4deepr** [comment]
I haven't gotten a chance to work on the training aspect of this yet. But I have updated the prediction ones. Will be uploading notebooks here from now on:
https://github.com/pr4deepr/cellpose-colab

**Comment by LPUoO** [comment]
Thank you very much @pr4deepr.
I tried it and it works very well. I am sure that many ZeroCostDL4Mic users will find it useful too.

**Comment by guijacquemet** [comment]
Hi, 
I have now made a ZeroCostDL4Mic notebook for Cellpose. 
Let me know what you think!
Cheers
Guillaume

**Comment by LPUoO** [comment]
Thank you very much @guijacquemet,

I just tested it with some images and it is very cool. I really like the fact that one can use this notebook simply with the pre-trained model.

Since this notebook is in beta I took the liberty of highlighting a few things below: 

- In the introduction, the link to the publication appears to send us to Stardist's publication instead of Cellpose's.

- In 5.2 we have:
![image](https://user-images.githubusercontent.com/64419544/108882596-7c25ea00-75fc-11eb-9c24-c78d6dee3631.png)
But I believe it should say “quality control” instead of “training”. 
Same in 6.1 but it should say “prediction” instead of “training”.
(Also training is misspelt a couple of times throughout the notebook)

- The intro in section 6 is duplicated

- In the prediction (6.1), the dimensions of the output for a stack are not the same as the input. E.g. as input I tested a time course with 3 frames and the output appeared to be a multi channel tiff. When I tested an input with 18 time points (frames) the output I had was a stack with 18 slices (z). Also the pixel size is lost in the output masks. (this happened using bio-formats importer in Fiji)

- Accelator > Accelerator (1.1)
- Here, you can set the **the** path to a pre-trained" (3.3 intro)
- Data_folder: This folder should contains > contain (6.1)


That's it,
Thank you very much for making this notebook!

**Comment by guijacquemet** [comment]
Hi @LPUoO ,

Thanks a lot! I have now updated the notebook. If you find anything else I would be happy to correct further !
Regarding the image dimension, this is something a bit harder to fix as ImageJ read multidimensional data in peculiar way, I will have to see if it is possible.

Cheers
Guillaume

**Comment by LPUoO** [comment]
Hi @guijacquemet,
Just another 2 comments about the [very nice] Cellpose notebook.

In 6.1 we have "Object_diameter: Indicate the diameter of the objects (cells or Nuclei) you want to segment. If you input "0", this parameter will be estimated automatically for each of your images."
Maybe it should say that the Object_diameter is in pixels?

Finally, when generating predictions from stacks the output says

```
Your images are now being processed
Performing prediction on: ImageName.tif

processing 1 image(s)

time spent: running network 3.00s; flow+mask computation 5.38
estimated masks for 1 image(s) in 8.44 sec
>>>> TOTAL TIME 8.44 sec
processing 1 image(s)

time spent: running network 2.86s; flow+mask computation 5.27
estimated masks for 1 image(s) in 8.18 sec
>>>> TOTAL TIME 8.18 sec
processing 1 image(s)

time spent: running network 2.82s; flow+mask computation 5.31
estimated masks for 1 image(s) in 8.18 sec
>>>> TOTAL TIME 8.18 sec
```

It would be cool if it said which frame in the stack it is just to give an idea of the progress so if one has stacks with a thousand time-points one has an indication on how many frames and images are left to process.


Thanks a lot!

**Comment by guijacquemet** [comment]
Hi @LPUoO 

Thanks! Yes, these will be included in the next release!
I will also change the UI a bit since I noticed the runtime get disconnected when analysing very long stacks.
Cheers
Guillaume

**Comment by LPUoO** [comment]
Hi @guijacquemet,

Just another idea.
In the other notebooks when we create a model we have a report with all the parameters used for the training.

In Cellpose when we make predictions with the pre-made models we don't have anything similar. I am not sure but I believe that the Cellpose models can be updated with [contributed data](https://cellpose.readthedocs.io/en/latest/gui.html#contributing-training-data) so there will be different versions of the model over time.

So I thought that it might be a good idea to have an additional document created with information about the model version used, and the other parameters one can change including Object_diameter, Flow_threshold and Cell_probability_threshold or maybe even better have that information in the metadata of the masks created.

Cheers

**Comment by guijacquemet** [comment]
Hi,

Thanks for the great suggestion! I will add this to the to-do list!

I have still not implemented the PDF export in the Cellpose notebook yet

Cheers

Guillaume

**Comment by LPUoO** [comment]
Hi,
I noticed that despite opening the Cellpose notebook from the wiki I get:A new version of this notebook has been released. We recommend that you download it at https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki

**Comment by guijacquemet** [comment]
Hey @LPUoO ,
Good spot, this should be fixed now!
Cheers
G
