### ISSUE TITLE
StarDist 2D Augmentation fails - Image has wrong mode

### ISSUE THREAD

**Issue by nicoschra** [HenriquesLab/ZeroCostDL4Mic#60]
**Describe the bug**
Data augmentation fails for 16bit/32 tiff images, if not only rotation/flip are used and multiplication factor > 5

Processing <PIL.Image.Image image **mode=I;16B** size=1024x1024 at 0x7F09FECC5898> [....]
-> ValueError: image has wrong mode

**To Reproduce**
1. Load Sample Data for StarDist
2. Follow the standard Workflow 
3. Augmentation by at least a factor of 4 or 5
4. Set image shearing and skewing to some value above 0

**Expected behavior**
Data augmentation should save augmented images in "Augmented Folder", by shearing and skewing them.

**Location of Bug**

From side-package: Augmentor/Operations.py
/usr/local/lib/python3.6/dist-packages/Augmentor/Operations.py in do(image)
   1290                 image = image.crop((0, abs(shift_in_pixels), width, height))
   1291 
-> 1292                 return image.resize((width, height), resample=Image.BICUBIC)
   1293 
   1294         augmented_images = []

Problem coming from PIL version 7.0.0, and BICUBIC interpolation for skewing images. 
(also see: https://github.com/python-pillow/Pillow/issues/4402) 

**System:**
StarDist2 ZeroCostDL4Mic Notebook on Google Colab (happened for multiple GPUs)

**Potential Bug fix (happy to debate)**
 - Change every "Image.BICUBIC" in Operations.py of augmenter to "Image.NEAREST" (maybe theres a better way to force augmenter to only use NEAREST-interpolation)
 - Forcing Pillow to install as version Pillow==6.2.1

**Comment by guijacquemet** [comment]
Dear @nicoschra,
Thanks a lot for reaching out and very well spotted! I will fix this in the next release!
Cheers
Guillaume

**Comment by guijacquemet** [comment]
Hi,

I have now changed the way the augmentation is done in the StarDist notebook. The change mostly improves the RAM management but also fix the issue described here.

Thanks again for reaching out!

Cheers
Guillaume
