### ISSUE TITLE
3D RCAN not training

### ISSUE THREAD

**Issue by bvernay** [HenriquesLab/ZeroCostDL4Mic#61]
Good morning,

First thank you very much for your effort into putting this great resource together.
I'm trying to use the 3D RCAN model (on the ER dataset https://github.com/AiviaCommunity/3D-RCAN). The training step (4.2) does fail with the following output: see attached file.
[3DRCAN_training_error.txt](https://github.com/HenriquesLab/ZeroCostDL4Mic/files/5628687/3DRCAN_training_error.txt)

Happy to run test if needed and thank you for your help

Bertrand
********************************************
Bertrand Vernay, PhD
Head of the Photonic Microscopy Facility
http://quest.igbmc.fr/
http://www.igbmc.fr/technologies/5/team/55/
https://github.com/bvernay
Office:+33 (0)3 69 48 51 27
Office: CBI, E1009
ORCID 0000-0002-7843-3872

IGBMC - CNRS UMR 7104 - Inserm U 1258
1 rue Laurent Fries
BP 10142
67404 Illkirch CEDEX
France Tél +33 (0)3 88 65 32 00
Fax +33 (0)3 88 65 32 01

**Comment by guijacquemet** [comment]
Dear Bertrand,

Many thanks for reaching out. I have not tested for sure but my guess that the dataset you tested is failing because the Noisy and the Ground truth images do not have the same name. It is fine when you manually indicate the path (using the RCAN command line) but the notebook we created is expecting that the images can be linked (to enable us to automatically generate training and validation data).
I will test again later to make sure that this is the issue but I think changing the names of the images may solve your error.

Cheers

Guillaume

**Comment by bvernay** [comment]
Dear Guillaume

Thank you for the quick reply. I did make sure that I renamed the file after downloading the dataset.  I doubled check and they are identical in their respective HighSNR and LowSNR folders. From the log, the notebook does load the pairs of images but failed here:

ValueError: Tensor conversion requested dtype float32_ref for Tensor with dtype float32: <tf.Tensor 'training/Adam/Adam/conv3d_1/kernel/m/Initializer/zeros:0' shape=(3, 3, 3, 1, 32) dtype=float32>

Bertrand

**Comment by guijacquemet** [comment]
Thanks for confirming! Then you have done everything right :) 

I will look into it and see if I can reproduce the error and find a way to fix it!

**Comment by guijacquemet** [comment]
Hi again,
I think your issue may be related to a weird Colab behaviour. We need to downgrade Keras to train 3D-RCAN and this somehow does not always happen properly. Sometimes it upgrade Keras instead.
One way to fix this is to force a runtime restart after you have installed the required dependencies (step2). 

When you start the notebook from a fresh session, 
- run section 1 and 2. 
- Then you can click on "Runtime -- Restart Runtime" 
- Then run section 2 again (to load the correct dependencies in your new runtime)
- Carry on with the rest of the notebook

I will upload a new version of the notebook where this is clearly described. 
Let me know if that works for you

**Comment by bvernay** [comment]
Hi,

The above instructions fix seems to work. The model has started its training.

Thanks

Bertrand

**Comment by guijacquemet** [comment]
Hi,

I have now uploaded a new version of the notebook which should hopefully fix the issue!
Thanks again for reaching out!

Cheers
Guillaume

**Comment by bvernay** [comment]
Thank you very much for ytour reactivity. Tested and running fine.

**Comment by bvernay** [comment]
Hi Guillaume
Thank you very much for your reactivity. tested and running without issue now.
Best wishes
Bertrand
