### ISSUE TITLE
cell tracking on bright field live image

### ISSUE THREAD

**Issue by MinjieHu** [HenriquesLab/ZeroCostDL4Mic#65]
Hi,

Thanks for the awesome toolbox.

I am wondering is it possible to do cell tracking on bright field live image. Based on the tutorial, it looks like we can use YOLO to identify the cells. Can we go further to tracing these cells? Or do we have other ways to fulfill the task?

Thanks in advance for any help!

Minjie

**Comment by guijacquemet** [comment]
Hi Minjie,

Thanks for reaching out!

Depending on the kind of tracking you want to do, StarDist + TrackMate may be what you need. We published a short protocol paper here:
https://f1000research.com/articles/9-1279/v2

This work very well to track roundish cells from brightfield images

If your cells are too difficult to segment using StarDist (shape too irregular), then we will have something else for you soon :)

I will post it here when available (should be in the next few days)

Cheers

Guillaume

**Comment by MinjieHu** [comment]
Hi Guillaume,

Thanks for the quick response. Unfortunately, my cell is uniform. Some of them are roundish while some others are more fibroblast-like. I have no idea about how StarDist will preform but I am glad to give a try.

While I also did some search on line, I found some people have already use Mask R-CNN (https://github.com/matterport/Mask_RCNN)  to identify irregular cells in bright field and it seems work well. I don't know how it is comparing to the StarDist or your new method. Maybe you can give some comment on it.

Anyway, looking forward to see your new method soon!

Minjie

**Comment by guijacquemet** [comment]
Hi Minjie,
If your cells have a very elongated shapes, then StarDist will not be ideal. I would wait until we release the next thing.

If you are interested in Mask R-CNN, then check Usiigaci ( https://github.com/oist/Usiigaci)

Cheers

Guillaume

**Comment by MinjieHu** [comment]
Hi Guillaume,

Thanks for the suggestion. I will waiting for your new method as it is easier to setting up the analysis.

Minjie

**Comment by guijacquemet** [comment]
Hi Minjie,

We have now released a notebook for SplineDist. SplineDist can handle a much broader variability of shapes than StarDist and I used it for automated tracking of cells. 

The exact same protocol as the one we published here https://f1000research.com/articles/9-1279/v2 can be used for SplineDist

I hope this helps!
Cheers

**Comment by MinjieHu** [comment]
Hi Guillaume,

Thanks so much for this real quick updates!!!

I start to give it a try once I received the news. Here I got two questions about the protocol.

1. The model file generated by StarDist is a zip file while SplineDist generated a folder containing two h5 file, two json file and two npy file. Which file is suppose to be the model file that I can use for the semi-automated annotations or should I take the whole folder and compress it into zip file?
2. How can I use the model with FIJI? Should I still use it with StarDist in FIJI? I checked the FIJI update site and try to find one related with SplineDist, but failed. 

Thanks!
Minjie

**Comment by guijacquemet** [comment]
Hi Minjie,

Sorry I should have been clearer. Unfortunately, there are not Fiji plugin for SplineDist as of yet and you cannot use SplineDist models to do semi-automated annotation. This is also why the model is not exported in a zip file.

Cheers
Guillaume

**Comment by MinjieHu** [comment]
Hi Guillaume,

Thanks for clarify. I am start training now. Finger crossed.

By the way, if I want to trace cell division or cell fusion, do you have any suggestions?

Thanks!
Minjie

**Comment by guijacquemet** [comment]
Hi,

You can do all of that in TrackMate!

just allow for track fusion or splitting. Then check the linage. 

Cheers

Guillaume

**Comment by MinjieHu** [comment]
That's indeed a surprise for me!!

I got my trained model today and tried to apply the prediction. But I got a run out of memory error. I guess it's probably because my stack file is too big. For each stack file, I have around 130 images. Can we add one more step before the prediction, i.e., if the file is too big, then split it into smaller one?

Thanks!

**Comment by guijacquemet** [comment]
Hi,

Do you get a RAM issue at the prediction stage? 
What are the pixel dimension of your images?

Cheers
G

**Comment by MinjieHu** [comment]
Yes. It's at the prediction stage. The pixel dimension is 2044*2048.

**Comment by MinjieHu** [comment]
Hi Guillaume,

Just a small update. I believe the RAM issue is caused by the stack contains too many images. When I get a subset stack(10 images) of the original one, the prediction works well. The RAM issue should be easily fixed If there's some code to split the stack file. 

When I look into the produced track file, I only found tidy dot for each figure. Does each dot stands for a cell? How did the dot defined, the center of the masked region? And in the trackmate, I can only find `Estimated blob diameter = 1, Threshold = 1,` not the `downsampling factor = 1` option as showed in the paper.

Thanks for any help!

Minjie

**Comment by MinjieHu** [comment]
By the way, can I run the notebook locally? Our server have larger RAM although it doesn't contain a GPU. We also access to a HPC containing two GPU node. However, I am totally unfamiliar with GPU related staff. Based on my soft research, our GPU seems not based on nvidia as `nvidia-smi` didn't return anything. Could you point me somewhere that I can learn to how to set up to use our GPU node? Or can the notebook work without GPU? If it is, this should be the easiest way to solve all my problems. 

Thanks very much for the help!

Minjie

**Comment by guijacquemet** [comment]
Hi,

yes, the dot in the image is the center of the cell. The center of the cell is directly calculated in the SplineDist predictions. Each dot can then be tracked easily in TrackMate.

It will see if I can implement a fix so that the predictions use less RAM. 

You can of course run predictions on a local server. In particular, the prediction alone does not require GPU.

We wrote a short guide on this here https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki/Running-notebooks-locally

Alternatively, if your server supports Jupiter notebooks, then you can just open the notebook and run it. 

Here is an example of what needs to be done to run our notebook using JupiterLab https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki/Running-ZeroCostDL4Mic-notebooks-on-FloydHub

Cheers

Guillaume

**Comment by guijacquemet** [comment]
Actually, one short fix you could consider is to save your images as "image sequence" from Fiji. 
This way the predictions will be performed on a per-image basis instead of over the whole stack. You can then easily load the results as a Stack in Fiji by opening the whole result folder.

**Comment by MinjieHu** [comment]
Hi Guilaume,

Thanks for all the suggestions. Saving as "image sequence" is indeed a way to walkaround. 

I also try to set up our local server for prediction as I have huge amounts of live images. I do have the Jupiter lab accession and most of the installation works fine except the `python splinegenerator.py install`. The error is
```
2021-01-20 11:43:45.522804: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; 
2021-01-20 11:43:45.522858: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

``` 
And the installation will just stop there. Does it mean I need to have a GPU to finish the SplineDist installation?

Minjie

**Comment by guijacquemet** [comment]
Hi,
Yes it looks like you need a GPU to install SplineDist. I am not sure however if you would need this for prediction only.

Another way to solve your RAM problem would be to scale down the size of your images via interpolation. If your cells are very small on your original images this may not work well, but otherwise, this would decrease the amount of RAM needed quite considerably and would not actually affect your results.

Cheers
G

**Comment by MinjieHu** [comment]
Scale down the size sounds a good solution. I guess there might be some scale down python code that I can directly used in the notebook. Do you have any clue about this kind of code?

**Comment by guijacquemet** [comment]
You have a lot of options here but I would probably go for cv2.resize see here for info:
https://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html#cv2.resize

**Comment by guijacquemet** [comment]
Or if easier, just batch process it in Fiji.

If you resize your images, it would be best to resize your training dataset as well and to train a new model

**Comment by MinjieHu** [comment]
Thanks for all the suggestions. I will give it a try and update once I finished.

**Comment by MinjieHu** [comment]
Hi Guillaume,

I try to understand the code line by line and found some clue about why running out of memory. 
`X = list(map(imread,Y))` This line reads all the files together in the whole folder, and these two lines
```
prediction_stack = np.zeros((n_timepoint, timelapse.shape[1], timelapse.shape[2]))
Tracking_stack = np.zeros((n_timepoint, timelapse.shape[2], timelapse.shape[1]))
``` 
 will further create two object with the same size. This used a lot of memory as I have 11 stack images in the folder. 
So I switch to use a for loop to read file one by one. And it works now. Here's the code I use right now. 
```
if Data_type == 2 :
  print("Stacks are being predicted")
  np.random.seed(42)
  lbl_cmap = random_label_cmap()
  Y = sorted(glob(Data_folder))
#  X = list(map(imread,Y))
  X = imread(Y[0])
  n_channel = 1 if X[0].ndim == 2 else X[0].shape[-1]
#  n_channel = 1 if X.ndim == 2 else X.shape[-1]   
  axis_norm = (0,1)   # normalize channels independently
  # axis_norm = (0,1,2) # normalize channels jointly
  if n_channel > 1:
     print("Normalizing image channels %s." % ('jointly' if axis_norm is None or 2 in axis_norm else 'independently'))
  #Load a pretrained network
  model = SplineDist2D(None, name = Prediction_model_name, basedir = Prediction_model_path)
  
  names = [os.path.basename(f) for f in sorted(glob(Data_folder))]

  # Create a list of name with no extension
 
  name_no_extension = []
  for n in names:
    name_no_extension.append(os.path.splitext(n)[0])

  outputdir = Path(Results_folder)

# Save all ROIs and images in Results folder.
#  for n in Y:
  for num, i in enumerate(Y):
    X = imread(i)
#    for num, i in enumerate(X):
    print("Performing prediction on: "+i)

#    timelapse = np.stack(i[1:70])
    timelapse = np.stack(X)
    del i
    del X
    timelapse
    timelapse = normalize(timelapse, 1,99.8, axis=(0,)+tuple(1+np.array(axis_norm)))
    timelapse.shape

    n_timepoint = timelapse.shape[0]
    prediction_stack = np.zeros((n_timepoint, timelapse.shape[1], timelapse.shape[2]))
    Tracking_stack = np.zeros((n_timepoint, timelapse.shape[2], timelapse.shape[1]))

# Save the masks in the result folder
    if Mask_images or Tracking_file:
      for t in tqdm(range(n_timepoint)):
        img_t = timelapse[t]
        os.chdir(full_Prediction_model_path)
        labels, details = model.predict_instances(img_t)      
        prediction_stack[t] = labels

# Create a tracking file for trackmate

        for point in details['points']:
          cv2.circle(Tracking_stack[t],tuple(point),0,(1), -1)

      prediction_stack_32 = img_as_float32(prediction_stack, force_copy=False)
      Tracking_stack_32 = img_as_float32(Tracking_stack, force_copy=False)
      Tracking_stack_8 = img_as_ubyte(Tracking_stack_32, force_copy=True)
      
      Tracking_stack_8_rot = np.rot90(Tracking_stack_8, axes=(1,2))
      Tracking_stack_8_rot_flip = np.fliplr(Tracking_stack_8_rot)

      os.chdir(Results_folder)
      if Mask_images:
        imsave(names[num], prediction_stack_32)
      if Tracking_file:
        imsave(name_no_extension[num]+"_tracking_file.tif", Tracking_stack_8_rot_flip)

          

print("Predictions completed") 
```

Thanks for all the help!

Minjie

**Comment by guijacquemet** [comment]
Hi,
Great!, thanks a lot for posting a fix, I will include it in the next release!

Cheers

Guillaume

**Comment by guijacquemet** [comment]
Hi,
I have now updated the SplineDist Notebook. Thanks again
Cheers
Guillaume
