### ISSUE TITLE
U-net 2D: 5.2. Error mapping and quality metrics estimation

### ISSUE THREAD

**Issue by LPUoO** [HenriquesLab/ZeroCostDL4Mic#66]
Hi,
I might be wrong, but aren't the axis in this figure flipped?
ie shouldn't the vertical axis be the IoU and the horizontal one the threshold?

![image](https://user-images.githubusercontent.com/64419544/106310444-79cdab80-625b-11eb-9c85-954f211a1234.png)
This comes from U-net 2D: 5.2. Error mapping and quality metrics estimation.

Cheers

**Comment by guijacquemet** [comment]
Hi,

Thanks a lot! We will correct that in the next release!
Cheers
Guillaume

**Comment by LPUoO** [comment]
Thank you Guillaume,
See also https://github.com/HenriquesLab/ZeroCostDL4Mic/pull/64
Cheers

**Comment by guijacquemet** [comment]
Thanks! much appreciated!
These two notebooks have been updated

Cheers
Guillaume
