### ISSUE TITLE
Name Output images

### ISSUE THREAD

**Issue by CadotB** [HenriquesLab/ZeroCostDL4Mic#7]
I use successfully the Unet Collab to train and segment images. Unfortunately, the predicted images names are different from the input images. Is it possible to have same names or same name with a pre/su fix?
Thks

**Comment by Romain-Laine** [comment]
Hi CadotB, you're right. We currently save the predictions as "predicted_01.tif", "predicted_02.tif" etc. disregarding of the original filenames. I agree this is not great so let me add this to the list of additions for the next release and we'll take this! I think we could go for what you're suggesting with a prefix or a suffix stating it's the prediction file. 
In the meantime, I hope it's not too inconvenient for you to rename the files manually. We'll be working on a fix asap ! Thanks again for raising this issue.

**Comment by Romain-Laine** [comment]
Hi CadotB, I have taken a look at the code and fixed the issue already actually. So this fix will definitely be included in the next release. I suggest you keep an eye on the release page in the next few days (it will be release v1.2).

**Comment by CadotB** [comment]
Awesome Romain! I asked it because I have to cut my pics in mosaics so they can be analyzed, but then to reconstruct the full image, I need to keep somehow similar names. Thanks for the upgrade.

**Comment by Romain-Laine** [comment]
Hi CadotB, great! Out of curiosity, why do you need to cut your pictures? Did you have issues with image size trying to use the full image in U-net?

**Comment by CadotB** [comment]
Yes, when I was doing the training, it was not working with images above 1024x1024px. I opened an issue before about that and lucpaul told me this is probably one of the limitations of google collab.

**Comment by Romain-Laine** [comment]
OK, gotcha! Thanks for the quick reply.
