### ISSUE TITLE
Image Border Ghost Object Artefact

### ISSUE THREAD

**Issue by MicPhotonIGBMC** [HenriquesLab/ZeroCostDL4Mic#74]
Hi,

I'm transferring an issue initially posted on the StarDist GitHub as 
Image Border Ghost Object Artefact #116
https://github.com/mpicbg-csbd/stardist/issues/116#issuecomment-785772628

Here is the reply from Romain
Hi Bertrand and Uwe,
Thanks for pointing this out to us. I have now run another training session and indeed noticed the issue that you mentioned. That is not an issue that we had when we originally tested and released the notebook.

@MicPhotonIGBMC , would you like to file an issue on our GitHub page instead if that's a ZeroCost issue and not StarDist?
https://github.com/HenriquesLab/ZeroCostDL4Mic/issues

@uschmidt83 , were there any major changes to StarDist 3D in the past month that may have caused a change in behaviour that we should look into?

I will be testing these further in the coming days and will let you know.
Best,

Romain

**Comment by Romain-Laine** [comment]
Hi Bertrand,
Thanks for transferring this over. I am running a few tests and hope to get back to you shortly. I am checking whether default parameters can be set more appropriately and trying to understand where this issue comes from.

- Could I ask you please to share how the loss curves look like in your case? 
- Also, is your split in epoch because you restarted the session and used transfer learning?
- What augmentation did you use?

Thanks !

Romain

**Comment by Romain-Laine** [comment]
Hi Bertrand, 
@guijacquemet and myself have now tested and upgraded the StarDist notebook to a few things:
- it now runs TF2.4 --> more stable
- data augmentation is now performed at the image generator stage as is suggested by Uwe
- default parameters should be more adapted to the example dataset
- a few other minor changes (displays and minor bugs)

These changes now completely got rid of the issues you mentioned and training seems more stable. 
So please take the new notebook from the Wiki page for a spin and let us know how you get on.

Thanks for raising that issue!

Best,

Romain

**Comment by MicPhotonIGBMC** [comment]
Hi Romain,

Sorry for the delay to come back to you. Thank you for the debugging, going to test it now.

Bertrand

**Comment by guijacquemet** [comment]
Hey Bertrand,
Are you still having issues with this? Or is this fixed?
Let us know if you want us to look further into this
Cheers
Guillaume
