### ISSUE TITLE
Using the last version of StarDist3D ends up with a crash

### ISSUE THREAD

**Issue by sebherbert** [HenriquesLab/ZeroCostDL4Mic#80]
**Describe the bug**
Using the last version of StarDist3D ends up with a crash

**To Reproduce**
I copied the last version of the StarDist3D.ipynb to my drive and also redownloaded the example dataset.
While running the "2. Install StarDist and dependencies" cell I receive the following errors
```...
Successfully built reikna pytools
ERROR: scikit-tensor-py3 0.4.1 has requirement numpy==1.16.*, but you'll have numpy 1.19.5 which is incompatible.
ERROR: scikit-tensor-py3 0.4.1 has requirement scipy==1.3.*, but you'll have scipy 1.4.1 which is incompatible.
Installing collected packages: mako, funcsigs, reikna, configparser, pytools, pyopencl, scikit-tensor-py3, gputools
...
```
[Full output is attached here: Cell2_output.txt](https://github.com/HenriquesLab/ZeroCostDL4Mic/files/6140946/Cell2_output.txt)
Trying to run the rest of the notebook leads to this error at cell 3.2

```
Default advanced parameters enabled
Your images appear to have the wrong dimensions. Image dimension (1024, 1024)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-a7e8cdbd0f36> in <module>()
     71 #Find image XY dimension
     72 Image_Y = x.shape[1]
---> 73 Image_X = x.shape[2]
     74 
     75 # If default parameters, patch size is the same as image size
IndexError: tuple index out of range
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.0
 - Browser Firefox

**Additional context**
I believe the error in 3.2 to be related to the first one in section 2 so I'm trying to fix it out first but I may be wrong...
Section 2's seems to be a dependency issue, I'm trying to figure out a way to modify this. I was thinking of removing the version control of the packages and let pip figure out the best versions for itself but I'm not quite clear on how this cell works yet.
Maybe I also missed something obvious :) 
Let me know if I can add anything, I'll update if I get any progress on my side.

Best,
Sebastien

**Comment by guijacquemet** [comment]
Hi @sebherbert,
Thanks for reaching out!
You can ignore the issue with the dependencies, this is unrelated.
Looking at your error message it looks like the images you are using have the wrong dimension (2D images instead of 3D). Which example dataset are you using?

**Comment by sebherbert** [comment]
Thanks for the quick feedback!

It was this sample [here](https://zenodo.org/record/3715492#.XnMhuXUzY5l). It was indeed the wrong (2D dataset) that I was trying to use with the 3D code... I've just tested with the 2D code instead and it seems to work like a charm now.
Sorry, I missed that. Thanks for your help and for this tool!

Sebastien
