### ISSUE TITLE
DeepSTORM: Error with data localization/visualization in Section 6

### ISSUE THREAD

**Issue by kaarjel** [HenriquesLab/ZeroCostDL4Mic#82]
Dear Romain/ZeroCostDL4Mic team,

Thank you for your help previously with the local installation of DeepSTORM on our computer. It is now working well after Carlo installed CUDA 11. 

I am having an issue with the visualization part in DeepSTORM and was wondering if you have any idea about this. This error happens in both the local computer and on Colab, so I will show you how it looks like on Colab.

Everything works great until Section 6.2 and 6.3. In Section 6.1 I put in a SMLM dataset and the output looks great (below).

![image](https://user-images.githubusercontent.com/80034970/112152980-220c4a80-8be3-11eb-9f36-789a4acc29f3.png)

However when I render the localization.csv file in Thunderstorm or run **6.3 Visualization of the localizations** the output is either an error message or very sparse localizations that don't look like the image in Section 6.1. 

![image](https://user-images.githubusercontent.com/80034970/112153639-c1c9d880-8be3-11eb-982e-c6b83de0e87a.png)

OR

![image](https://user-images.githubusercontent.com/80034970/112153691-d27a4e80-8be3-11eb-8ef5-9c385ff7efcd.png)

There seems to be a discrepancy between the prediction and locs. The printed image size is also changed from the original 512x512, I wonder if this could be an issue. Hope you can help.

Best wishes,
Kaarjel

**Comment by Romain-Laine** [comment]
Hi Kaarjel,
Thanks for your input. Indeed, that's not right.
Would you be able to inspect the csv file to see whether there is anything wrong ?
Say, the presence of NaN or other formatting issues, missing lines, etc.
It might simply be that. In this case, there might be some checks we can do on the csv file to ensure it's readable again.

Cheers,

Romain

**Comment by kaarjel** [comment]
Hi Romain,

I will have a look at the csv file and see if anything is out of the ordinary. Will get back to you!

Cheers,
Kaarjel

**Comment by kaarjel** [comment]
Hi Romain,

Picking up from where we left off:

_Do you get that issue with any dataset or only specific frames of specific dataset?_ 
No I seem to get this with different datasets.

_Also, can you run the QC in Colab fine?_
Yes the QC in colab runs fine now. Actually we had an issue in QC where the output image size was incorrect and the target image scale was distorted or not produced at all. So my colleague
fixed it by defining the upsampling factor in the QC section:

```
    #upsampling_factor = int(Mhr/M)
    upsampling_factor = 8
    print('Upsampling factor: '+str(upsampling_factor))
    pixel_size_hr = pixel_size/upsampling_factor # in nm
```

_The upsampling factor should be picked up correctly. What does it read for Mhr, M and upsampling factor without re-setting it to 8_?
This is the output without changing anything and the upsampling factor is printed as 240 even though we used 8.
![image](https://user-images.githubusercontent.com/80034970/112341793-0166f200-8cc2-11eb-9786-1efefc91021e.png)


The visualization section also has a discrepancy in the image size which can be seen in my first post.  

In terms of datasets I have 2 models, one is for SMLM datasets that are binned to increase density of emitters, and the other is just the original tiff of 512x512. I could try to run your test datasets on Zenodo too to see if the problem persists.

Apologies for the overload of info, do let me know if you need clarification :)

Cheers,
Kaarjel

**Comment by JohannaRahm** [comment]
Hey Romain,

thanks for taking the time and looking into the issue! Some additonal information: We patched the training data in an external workflow. Therefore, in our case, the variable M defined through Sec 3.1a has the size of the small patch already and this throws off Sec 5.3 calculation of the upsampling factor, hence the hard coding of this parameter there.

upsampling_factor = int(Mhr/M) = (testdata_width*upsampling)/(trainingdata_width) = (512*8)/17 = 240

In general, I think this factor is calculated correctly! (if training data and testing data width and heights are the same)

To the viz in Sec 6.3:

Defining the cmap = "gray" displays localizations. The issue of the localizations not matching the predicted image remains, I will also have a closer look into it.

plt.imshow(locImage, norm = simple_norm(locImage, percent = 99.5), cmap="gray");

![image](https://user-images.githubusercontent.com/48733135/112347956-a2a47700-8cc7-11eb-81af-03e712b6af2e.png)

**Comment by Romain-Laine** [comment]
Hi both,
Nice job troubleshooting these. Yes, in fact, if the upsampling factor is evaluated wrongly, it would definitely make the visualization completely break. So hard coding in your separate implementation is a good way to fix this.
We also save a matrix for metadata that saves the upsampling factor that was used for training so you can recover that this way and that's how our inferences work.

"_if training data and testing data width and heights are the same_"
It should not be the case, I think the network can handle any types of data sizes. The upsampling factor is a relative parameter. 

Regarding visuliaztion, check your CSV file as I said before, does the code pick up the right number of frames/localizations?
If it does not use all of them from the CSV file for some reason (line breaks possibly), then it would look sparse.

I hope this helps!

Romain

**Comment by kaarjel** [comment]
Hi Romain,

You are absolutely right - there is a problem with the CSV file. I predicted the glia BIN10 using 3 models - the simulated dataset model from Zenodo, my single emitter model, and my overlapping emitter model. The predicted output for all 3 look great but in the CSV file, the models I trained do not have localizations in every frame in the CSV. It doesn't look like a format issue, more like a very short list of coordinates. Not sure why this is because the PNG images predicted in Section 6.1 look great for all models. 

As an example, here are (1) prediction with the Zenodo model and (2) prediction with my single emitter model.

![image](https://user-images.githubusercontent.com/80034970/112389340-df3a9780-8cf4-11eb-8745-9bc6888b7a0a.png)
![image](https://user-images.githubusercontent.com/80034970/112389388-f2e5fe00-8cf4-11eb-845d-87864e22a1c6.png)

And section 6.3 Visualization of the localizations. The table shows that the Zenodo model locs start with frame 1 but my model starts with 139 and erratic frame numbers. 
![image](https://user-images.githubusercontent.com/80034970/112389830-a7801f80-8cf5-11eb-9929-7440e47160f4.png)

![image](https://user-images.githubusercontent.com/80034970/112389637-5839ef00-8cf5-11eb-877d-8a54935de7b8.png)

Any idea why this is happening and what I could potentially do to solve this issue?

Cheers,
Kaarjel

**Comment by Romain-Laine** [comment]
Hi Kaarjel,
It looks like your model only picked up 417 localisations. See above. 
That's really few from the complete dataset, so it looks like you may need to train a model again to get better performance first.

Best,

Romain

**Comment by EliasNehme** [comment]
Hi Kaarjel,

I'm looking into the problem and will update soon.

Thanks,
Elias

**Comment by kaarjel** [comment]
Thanks Elias. We have decided to go with using the output images instead of the localization list but if it is an easy solve, it would be nice to have the list as well. 

Cheers,
Kaarjel
