### ISSUE TITLE
TrackMate parameters in Automated_tracking.py

### ISSUE THREAD

**Issue by esgomezm** [HenriquesLab/ZeroCostDL4Mic#83]
Hi there! 

I followed the very nice guidelines in the [StarDist + TrackMate manuscript](https://f1000research.com/articles/9-1279/v1) so I can use the code `Automated_tracking.py ` with my data. It's awesome, thank you for releasing it!

I just needed to change a couple of parameters. I think this might also happen to other users:
https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/3d75f9d5a72f86f47418a42c16571e843261e359/Tools/Automated_tracking/Automated_tracking.py#L106
Slightly modified it to: 
```python
DetectorKeys.KEY_RADIUS: Pixel_calibration, 
DetectorKeys.KEY_DOWNSAMPLE_FACTOR: 1,
```
With the same procedure to get the landmark of each cell (`cv2.circle(detections,tuple((x,y)),0,(1), -1)`),  the tracking landmarks have a diameter = 1 pixel, so if the pixel size is given in microns (0.8 for example), TrackMate does not detect them. For this same reason, I needed to change the `DOWNSAMPLE_FACTOR`.

**Comment by guijacquemet** [comment]
Hi @esgomezm 

Thanks for reaching out and glad you find it useful! Something even better is coming soon :)
Regarding the script, would it be useful if I added these two parameters as user input? Never had this issue, but I can see how it can be a problem.

Cheers

Guillaume

**Comment by esgomezm** [comment]
Hi @guijacquemet,

I'd ask at least for the landmark-diameter in pixels to internally adapt it to the pixel size, and let by default the values that you use in the StarDist notebook. This way it can be more general, IMO.

The downsampling parameter is less trivial for me. Downsampling = 1 worked better but I'm not sure what's the best way to set it up with new data. 

Also, I added the chance to close gaps because my cells enter and leave the focus plane, but this part is definitely more specific.

https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/3d75f9d5a72f86f47418a42c16571e843261e359/Tools/Automated_tracking/Automated_tracking.py#L120
```python
  settings.trackerSettings['GAP_CLOSING_MAX_DISTANCE'] = GAP_CLOSING_MAX_DISTANCE
  settings.trackerSettings['MAX_FRAME_GAP'] = MAX_FRAME_GAP
```
https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/3d75f9d5a72f86f47418a42c16571e843261e359/Tools/Automated_tracking/Automated_tracking.py#L209
```python
gd.addNumericField("LINKING_MAX_DISTANCE", 20, 1)
gd.addNumericField("GAP_CLOSING_MAX_DISTANCE", 20, 1)
```
https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/3d75f9d5a72f86f47418a42c16571e843261e359/Tools/Automated_tracking/Automated_tracking.py#L222
```python
GAP_CLOSING_MAX_DISTANCE = gd.getNextNumber()
MAX_FRAME_GAP = int(gd.getNextNumber())
```
May I ask whether the `keepDirectories` mode will change in the next release? :)

Thank you very much!
Esti

**Comment by guijacquemet** [comment]
All good suggestions thanks!

I have no plan to change the keepDirectories mode. But if this is an issue, let me know!
Also, in case you have not seen it, I also wrote a small R script to compile the data https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/master/Tools/Automated_tracking/Tracks_merge.R

Can be quite useful if you have a lot of results to merge

Cheers

Guillaume

**Comment by esgomezm** [comment]
Yes! I've used it and it works after changing the path specification in the code. Otherwise, all the new CSV files were stored together with the original tracking files.

I've let you a PR so you can see the changes and use them if you consider:

https://github.com/HenriquesLab/ZeroCostDL4Mic/pull/84

Cheers, 
Esti

**Comment by guijacquemet** [comment]
Awesome, thanks!

Cheers
Guillaume

**Comment by guijacquemet** [comment]
Hi,

I have finally found a bit of time to implement most of the changes you suggested! If you get the chance, let me know if it works better with your data!

Cheers
Guillaume

**Comment by esgomezm** [comment]
Hi @guijacquemet 

Perfect! Most of it should now work. 
The only important missing part is the `TrackBranchingAnalyzer` dependency in the tracker. Otherwise, you will not store the information about splits or even take them into account. 
I included it as shown [here](https://github.com/HenriquesLab/ZeroCostDL4Mic/pull/84/commits/85fed08012ffd8b85141e9af1fdae65bd8c98655) and it works perfectly.

Bests,
Esti

**Comment by guijacquemet** [comment]
Hi,
Thanks a lot! I have now updated the script!
Cheers
Guillaume
