### ISSUE TITLE
image dimension error

### ISSUE THREAD

**Issue by livecurious-ceyda** [HenriquesLab/ZeroCostDL4Mic#85]
Dear ZeroCostDL4Mic team,

I was playing with ZeroCostDL4Mic to get familiar with it. I have followed your guidelines for the Noise2Void (2D) network, and it worked without a hitch when I used the training images you have shared. 

Then, I wanted to use the images that I have collected from one of my previous internships. However, it gave me an error as the dimension of my images are 800x600 pixels.

What should I do to fix the problem? I have attached the screen shot for your review. As you can see, it says image dimensions does not match dims.

Best regards,
Ceyda

**Additional context**
![Noise2void_image_error](https://user-images.githubusercontent.com/81480737/112726969-28772b00-8f31-11eb-9817-b4c20cc5d029.JPG)

**Comment by guijacquemet** [comment]
Hi @livecurious-ceyda 
This error suggests that your images have the wrong number of dimensions. Are you using RGB images? or are you using 3D stacks?
Perhaps you could share an example image.
Cheers
Guillaume

**Comment by livecurious-ceyda** [comment]
Hi Guillaume!

Thank you for your reply. Yes, it is an RGB image! I have attached it for your review.

Best,
Ceyda

![NT-1_CB](https://user-images.githubusercontent.com/81480737/112829163-61caaa80-9099-11eb-9bd2-a1cd67b7380d.jpeg)

**Comment by guijacquemet** [comment]
Hi,

This is why you are having issues. The notebook is meant to denoise a single channel at the time. It is best to produce a specific model for each fluorescent channel you want to denoise. 
N2V can also denoise RGB images but here the noise of each channel is independent from the other so best to denoise separately before merging.

Cheers

Guillaume

**Comment by livecurious-ceyda** [comment]
Oh, I get it now. Thank you very much!

Best,
Ceyda
