### ISSUE TITLE
Stardist : stops during traning Tensorflow multiple warnings

### ISSUE THREAD

**Issue by Zeikad** [HenriquesLab/ZeroCostDL4Mic#86]
Hi,

I'm trying to use Stardist 2D notebook however it fails to complete the training. I don't know how to code but the only thing that caught my eye were multiple warning about Tensorflow (compatibility of package versions ?)

Here is what happened : 
**1- GPU access : ok** 
You have GPU access
Sun Apr  4 21:37:25 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    36W / 250W |   8347MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |

**2-Mounting the drive : ok**
**3 installing Stardist dependencies : first warning** 

> Building wheels for collected packages: reikna, pytools
>   Building wheel for reikna (setup.py) ... done
>   Created wheel for reikna: filename=reikna-0.7.5-cp37-none-any.whl size=122266 sha256=881bbd022ff0b40971fc1ce6625c4d948d6aee690594cf0d34eebce57a3d7c6b
>   Stored in directory: /root/.cache/pip/wheels/82/2d/ba/12c9ba3637183463c471bcf352f5bc1703ab7dfbec9842f04a
>   Building wheel for pytools (setup.py) ... done
>   Created wheel for pytools: filename=pytools-2021.2.2-py2.py3-none-any.whl size=60166 sha256=095ea87dcf1062cb291457ddfecc6cddf746520393eb6eca5b09485f597f2ee3
>   Stored in directory: /root/.cache/pip/wheels/a2/71/a4/2c1a223ad52e28a878053c37dc9d59a58a749eaa920ef00231
> Successfully built reikna pytools
> **ERROR: scikit-tensor-py3 0.4.1 has requirement numpy==1.16.*, but you'll have numpy 1.19.5 which is incompatible.
> ERROR: scikit-tensor-py3 0.4.1 has requirement scipy==1.3.*, but you'll have scipy 1.4.1 which is incompatible.**
> Installing collected packages: configparser, scikit-tensor-py3, mako, funcsigs, reikna, pytools, pyopencl, gputools
> Successfully installed configparser-5.0.2 funcsigs-1.0.2 gputools-0.2.9 mako-1.1.4 pyopencl-2021.1.5 pytools-2021.2.2 reikna-0.7.5 scikit-tensor-py3-0.4.1
> 

But somehow it made it till the end : 

> Using TensorFlow backend.
> 
> ------------------------------------------
> Libraries installed
> Notebook version: 1.12.2
> This notebook is up-to-date.
> 

**4 Setting training parameters : another warning, but not Tensorflow**

> Default advanced parameters enabled
> 
> TiffPage 0: TypeError: read_bytes() missing 3 required positional arguments: 'dtype', 'count', and 'offsetsize'
> 
> Loaded images (width, length) = (453, 462)
>  Your chosen patch_size is not divisible by 8; therefore the patch_size chosen is: 432
> Parameters initiated.

But again, it generated the "example image" with its mask. So I proceeded further 
**5-Data augmentation : I disabled it for now**
**6-Using pre-trained model : yes but was not able to find default learning rate**
**7-Preparation of the training data**
A warning (but not in red) 

> TiffPage 0: TypeError: read_bytes() missing 3 required positional arguments: 'dtype', 'count', and 'offsetsize'
> TiffPage 0: TypeError: read_bytes() missing 3 required positional arguments: 'dtype', 'count', and 'offsetsize'
> TiffPage 0: TypeError: read_bytes() missing 3 required positional arguments: 'dtype', 'count', and 'offsetsize'
> TiffPage 0: TypeError: read_bytes() missing 3 required positional arguments: 'dtype', 'count', and 'offsetsize'
> TiffPage 0: TypeError: read_bytes() missing 3 required positional arguments: 'dtype', 'count', and 'offsetsize'
> TiffPage 0: TypeError: read_bytes() missing 3 required positional arguments: 'dtype', 'count', and 'offsetsize'
> 100%|██████████| 10/10 [00:00<00:00, 261.23it/s]
> 100%|██████████| 10/10 [00:00<00:00, 179.38it/s]
> 
> Normalizing image channels independently
> number of images:  10
> - training:         9
> - validation:       1
> **WARNING:tensorflow:From /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.**
> Instructions for updating:
> If using Keras pass *_constraint arguments to layers.
> **WARNING:tensorflow:From /tensorflow-1.15.2/python3.7/keras/backend/tensorflow_backend.py:4070: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.**
> 
> 
> Using default values: prob_thresh=0.5, nms_thresh=0.4.
> **WARNING:tensorflow:From /tensorflow-1.15.2/python3.7/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.**
> 
> Config2D(axes='YXC', backbone='unet', grid=(2, 2), n_channel_in=1, n_channel_out=33, n_dim=2, n_rays=32, net_conv_after_unet=128, net_input_shape=(None, None, 1), net_mask_shape=(None, None, 1), train_background_reg=0.0001, train_batch_size=2, train_checkpoint='weights_best.h5', train_checkpoint_epoch='weights_now.h5', train_checkpoint_last='weights_last.h5', train_completion_crop=32, train_dist_loss='mae', train_epochs=400, train_foreground_only=0.9, train_learning_rate=0.0003, train_loss_weights=(1, 0.2), train_n_val_patches=None, train_patch_size=(432, 432), train_reduce_lr={'factor': 0.5, 'patience': 40, 'min_delta': 0}, train_shape_completion=False, train_steps_per_epoch=100, train_tensorboard=True, unet_activation='relu', unet_batch_norm=False, unet_dropout=0.0, unet_kernel_size=(3, 3), unet_last_activation='relu', unet_n_conv_per_depth=2, unet_n_depth=3, unet_n_filter_base=32, unet_pool=(2, 2), unet_prefix='', use_gpu=False)

I however continued : I had a bad feeling about this, a script is not dumb, its the user.

> WARNING:tensorflow:From /tensorflow-1.15.2/python3.7/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.where in 2.0, which has the same broadcast rule as np.where
> WARNING:tensorflow:
> The TensorFlow contrib module will not be included in TensorFlow 2.0.
> For more information, please see:
>   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
>   * https://github.com/tensorflow/addons
>   * https://github.com/tensorflow/io (for I/O related ops)
> If you depend on functionality not listed there, please file an issue.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/csbdeep/utils/tf.py:309: The name tf.summary.image is deprecated. Please use tf.compat.v1.summary.image instead.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/csbdeep/utils/tf.py:337: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/csbdeep/utils/tf.py:344: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.
> 
> Epoch 1/100
> 14/13 [===============================] - 3s 189ms/step - loss: 0.6856 - prob_loss: 0.0377 - dist_loss: 3.2392 - prob_kld: 0.0126 - dist_relevant_mae: 3.2389 - dist_relevant_mse: 35.0775 - val_loss: 0.4776 - val_prob_loss: 0.0497 - val_dist_loss: 2.1396 - val_prob_kld: 0.0103 - val_dist_relevant_mae: 2.1392 - val_dist_relevant_mse: 12.1289
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/csbdeep/utils/tf.py:372: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.
> 
> Epoch 2/100`

but it started rounding epoch, so I still had some hopes...until this : 

> Epoch 97/100
>  1/13 [=>............................] - ETA: 0s - loss: 0.2258 - prob_loss: 0.0326 - dist_loss: 0.9657 - prob_kld: 0.0035 - dist_relevant_mae: 0.9654 - dist_relevant_mse: 1.8165
> 
> ---------------------------------------------------------------------------
> 
> StopIteration                             Traceback (most recent call last)
> 
> <ipython-input-8-f6f4eca8a08f> in <module>()
>       5 
>       6 history = model.train(X_trn, Y_trn, validation_data=(X_val,Y_val), augmenter=augmenter,
> ----> 7                       epochs=number_of_epochs, steps_per_epoch=number_of_steps)
>       8 None;
>       9 
> 
> 3 frames
> 
> /tensorflow-1.15.2/python3.7/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
>     183             batch_index = 0
>     184             while steps_done < steps_per_epoch:
> --> 185                 generator_output = next(output_generator)
>     186 
>     187                 if not hasattr(generator_output, '__len__'):
> 
> StopIteration: 

Voilà...I'm sorry, I which I would be able to report this issue with a more appropriate "coding etiquette" but I don't know how to code. (I think I should start)

Hopping that someone from the team would be able to get what the problem is. 
Thank you for the massive work you are all doing

Best,
Zeinab

**Comment by guijacquemet** [comment]
Hey Zeinab,

Thanks for reaching out. Don't mind these TensorFlow errors, the notebook is using the "old" TensorFlow 1.15 to run so that the models trained can be compatible with Fiji.

Could you tell a bit more about your training dataset? 
I have seen this type of crash at the very end of training when the training images are rectangular instead of squares. 
If this is also your issue, I would suggest that you crop your training dataset. This can be done quite easily and quickly using the augmentor notebook found here: 
https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki#tools

Cheers
Guillaume

**Comment by Zeikad** [comment]
Hi,
oh ! indeed it is true that my images are not perfect squares. I'll crop them, and try again soon. I'll let you know if it worked.
Thank you so much for the quick answer !
Have a nice day,

**Comment by Zeikad** [comment]
Hi again,
Ok, so I used the augmentor notebook and it worked perfectly. I ended with a dataset of 44 cropped images 200x200 pixels, downloaded the dataset, and changed its directory as suggested. 
Restarted the procedure for Stardist using this new dataset. So far I didn't get the previous TiffPage 0: TypeError: . 
I chose to train to 200 epoch. And this time it seemed to work until the 198 epoch ;__;  and I got this : 

> 
> Epoch 00198: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
> Epoch 199/200
> 
> ---------------------------------------------------------------------------
> 
> StopIteration                             Traceback (most recent call last)
> 
> <ipython-input-7-f6f4eca8a08f> in <module>()
>       5 
>       6 history = model.train(X_trn, Y_trn, validation_data=(X_val,Y_val), augmenter=augmenter,
> ----> 7                       epochs=number_of_epochs, steps_per_epoch=number_of_steps)
>       8 None;
>       9 
> 
> 3 frames
> 
> /tensorflow-1.15.2/python3.7/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
>     183             batch_index = 0
>     184             while steps_done < steps_per_epoch:
> --> 185                 generator_output = next(output_generator)
>     186 
>     187                 if not hasattr(generator_output, '__len__'):
> 
> StopIteration: 

Could it be coming from my dataset ? 200 pixel of 44 images is too small for training ? 
If needed I can copy paste the entire workflow (but it will be a huge message) or maybe link a txt file with all the content of the notebook cells ? or if needed I can even share my dataset so one can try with exactly the same images. 

Thanks again for the help.
Best,
Zeinab

**Comment by guijacquemet** [comment]
Hei Zeinab,
If you can share your training dataset that would be the easiest.
Cheers
G

**Comment by Zeikad** [comment]
Hi,
Here it is : 
https://drive.google.com/drive/folders/1O6N4PTa5utYF07KqOjf2a8qnwoW_Ii3p?usp=sharing

Best,
Zeinab

**Comment by guijacquemet** [comment]
Hi,
After a few test. I think your images need to be at least 256x256 pixels to complete a successful training.
Cheers
G

**Comment by Zeikad** [comment]
Hi,
Okay, I'll try again with the correct size then. Thanks a Ton !

Best,
Zeinab
