### ISSUE TITLE
ZeroCostDL4Mic - 3D Unet -augmentation error

### ISSUE THREAD

**Issue by Eddymorphling** [HenriquesLab/ZeroCostDL4Mic#87]
Hello,
I have been using ZeroCostDL4Mic to perform machine learning using the 3D-Unet architecture. I come across this error in Section 3.2 of the 3D-Unet Google Colab pipeline. I have attached screen shots of the error and my training parameters. I have 15 training volumes which are 150x150x45 in size and currently use an input patch size of 120x120x40. Any advice would be much appreciated :) Thanks!

@guijacquemet 

<img width="604" alt="Augmentation_error" src="https://user-images.githubusercontent.com/67712116/115257125-6b25c080-a0f5-11eb-9751-0983b360b431.PNG">
<img width="614" alt="Trainining_parameters" src="https://user-images.githubusercontent.com/67712116/115257127-6bbe5700-a0f5-11eb-8bd6-3cbe15112de5.PNG">

**Comment by Eddymorphling** [comment]
Hi,
Sorry but I think I found out what was wrong. My validation split was too small. I had to increase that and that fixed the issue. I will close this post now.

**Comment by Eddymorphling** [comment]
It still shows me this error though

![image](https://user-images.githubusercontent.com/67712116/115259438-81cd1700-a0f7-11eb-92be-729e58fae3de.png)

**Comment by krentzd** [comment]
Hi, the error message has popped up for a few users, but it should not interfere with the rest of the notebook executing correctly. We're currently working on updating the notebook to address the issue and solve it with the next release.

**Comment by Eddymorphling** [comment]
Great, thanks for the quick response!

**Comment by krentzd** [comment]
No worries and thanks for raising the issue!
