### ISSUE TITLE
pix2pix QC step failing due to image scaling mismatch

### ISSUE THREAD

**Issue by rfechtner** [HenriquesLab/ZeroCostDL4Mic#88]
**Describe the bug**
I get a RuntimeError while predicting during the QC-step of the pix2pix_ZeroCostDL4Mic.ipynb 
"RuntimeError: Sizes of tensors must match except in dimension 0. Got 8 and 9 in dimension (The offending index is 0)"

Seems due to the differences in scaling when inferring opposed to training:
Training:  `--preprocess scale_width_and_crop --load_size $Image_min_dim --crop_size $patch_size`
Inferring: `--preprocess scale_width --load_size $patch_size_QC --crop_size $patch_size_QC`

`$patch_size_QC` is calculated based on the image and not a user paramerter, `$patch_size_QC` does not match  `$patch_size`, whicht seems to be nessecary for the prediction to work. Changing it manually again to `$patch_size` during the QC-Step solved the issue for me.

**Comment by guijacquemet** [comment]
Hi,

Thanks for reaching out! I will make sure this gets fixed in the next release.
Just to clarify, you get this issue because you choose a specific patch size during training?  
Cheers
Guillaume

**Comment by rfechtner** [comment]
Hi Guillaume,

I used the default of 512.
Please let me know if I can assist in any way.

Cheers
Ron
________________________________

**Comment by guijacquemet** [comment]
Thanks,
Two more questions, 
- Did you disable  "Use_Default_Advanced_Parameters" for training? or are you using images of different dimensions for training and for QC?  
Trying to decide on the most convenient way to fix the issue. Thanks

**Comment by rfechtner** [comment]
'Use_Default_Advanced_Parameters' was set to True for training, hence the default patch_size of 512.

Image sizes can vary a bit.
________________________________

**Comment by guijacquemet** [comment]
Thanks this is very helpful,

Ok, this is likely the issue then. The notebook assumes that all the images have the same dimension.
At the moment the patch size is chosen as the smallest dimension of a randomly chosen image. So if you have images of different dimensions, this will cause problems. 
I will add a fix for this

Thanks again

**Comment by guijacquemet** [comment]
The notebook has now been updated. This issue should now be fixed!
Cheers
Guillaume
