### ISSUE TITLE
3D UNET crashes at the 1st epoch

### ISSUE THREAD

**Issue by Eddymorphling** [HenriquesLab/ZeroCostDL4Mic#89]
Hello,

I came across this crash when I start training (section 4.1) on my datasets. From what I understand, is that there is not enough RAM to train, please correct me if I am mistaken. Here is a shot of the crash:

![image](https://user-images.githubusercontent.com/67712116/115618498-63fae000-a2b8-11eb-9076-4132a23928b3.png)

My current training volumes are 512x512x24 and I am using augmentation. I have attached screenshots of these parameters as well:

Training Parameters:
![image](https://user-images.githubusercontent.com/67712116/115618684-a7ede500-a2b8-11eb-9623-ef5fe9fe3450.png)

Augmentation Parameters:
![image](https://user-images.githubusercontent.com/67712116/115618779-c18f2c80-a2b8-11eb-8b35-586c7bb2ae72.png)

Any suggestions to fix the crash would be greatly appreciated again!
Thanks!

**Comment by Eddymorphling** [comment]
Oh think I figured it out. My input volumes are too large and I probably hit the GPU limit of Google Collab. I reduced it to 256x256x24 and it runs well!

I will now try to run the colab notebook using my local GPU which is a has more CUDA cores that the online Tesla T4.

**Comment by Eddymorphling** [comment]
Oh think I figured it out. My input volumes are too large and I probably hit the GPU limit of Google Collab. I reduced it to 256x256x24 and it runs well!

I will now try to run the colab notebook using my local GPU which is a has more CUDA cores that the online Tesla T4.

**Comment by guijacquemet** [comment]
Hi 
Thanks for reaching out! Yes, the Google collab GPU is crashing.  Decreasing patch size or the batch size should help fix this.

Cheers
Guillaume
