### ISSUE TITLE
'Visual_validation_after_training' is not defined

### ISSUE THREAD

**Issue by Erwan67** [HenriquesLab/ZeroCostDL4Mic#9]
**Describe the bug**
I have one error message when I star the Step 4

**To Reproduce**
1- I would like to create my model for stardist
2. I use Labkit to create two image labeling save as Tif (32bits)
3.I Create one googledrive folder: inside there are 2 anothers folder, one with name Training_source another one Training_Target. in this flder there are tif file source_1.tif source_2.tif and Target_1.tif and Target_2.tif 
4. I copy paste the link and when I start the step 4 there is this message:
**Screenshots**
![image](https://user-images.githubusercontent.com/51329059/78558121-5fc96500-7812-11ea-8172-ae961eac049f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version 80.0.3987.149 (Build officiel) (64 bits)

Thank's

**Comment by guijacquemet** [comment]
Hi,
Many thanks for reaching out !
I cannot reproduce the issue on my end. Just to check. Once you have input the parameters (step 3), did you run the cell ?

**Comment by Erwan67** [comment]
this is the link with my folder, if you woulke like to test 
https://drive.google.com/drive/folders/1pFs6yvq7O29MNgU6wSoGsCFFlMYmo_SI?usp=sharing

i think, I have run the cell, but now I have another message ...

![image](https://user-images.githubusercontent.com/51329059/78652210-b9d53380-78c1-11ea-96a7-9c2ab3cf7aa4.png)

**Comment by guijacquemet** [comment]
In this error it looks like you only have read access to the Google drive folder you are trying to use. Please choose a folder where you have read / write access. This should solve your issue
