### ISSUE TITLE
Running 3D unet on Local GPU

### ISSUE THREAD

**Issue by Eddymorphling** [HenriquesLab/ZeroCostDL4Mic#91]
Hello,

I am having trouble running the google colab (3D-Unet) on my local GPU. I am a beginner when it comes to Python and Google Colab, so I apologize for any mistakes made so far! Here is what I did till now:

Step 1: I setup a local env using Anaconda as per the instructions given on the Wiki - []https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki/Running-notebooks-locally and here - https://research.google.com/colaboratory/local-runtimes.html. Romain had sent me a link to download the requirement list for setting up the local env, which can be found here - https://www.dropbox.com/s/rkh1z85qf0birfh/requirements.txt?dl=0

Step 2: I had to make a few changes when connecting Google Colab with the local GPU and had to run the below codes to get Colab and my local GPU linked. Here is the code if anyone needs it:
```
jupyter notebook --NotebookApp.allow_origin='https://colab.research.google.com' \
  --port=9090 --no-browser

```
Step 3: After getting the Colab notebook and the local GPU connected and start running the notebook from Section 1, I start coming across various errors. Am I doing this right or  should do I have to meet any other requirements? I can also upload screenshots of the error codes if that helps. Thanks!

**Comment by guijacquemet** [comment]
Hey @Eddymorphling ,
Thanks for reaching out!
Perhaps the discussion here could help you? 
https://forum.image.sc/t/zerocost4dl-running-3d-unet-on-local-gpu/51784/6

**Comment by Eddymorphling** [comment]
Hi @guijacquemet . I am Praveen, I had created that post on the ImageJ forum :)

**Comment by guijacquemet** [comment]
Fair enough! 
Please do post the screenshot of the errors!

**Comment by Eddymorphling** [comment]
Ok, The notebook is now connected to the local GPU. I will start with Section 1.1
![image](https://user-images.githubusercontent.com/67712116/116278205-e6b5ec00-a74b-11eb-9996-f2002588f5b2.png)

**Comment by guijacquemet** [comment]
Hi,

This one should be easy to solve. To run the notebook locally you need to remove a few Google collab specific commands.
One of which is :
`%tensorflow_version 1.x`

Cheers
Guillaume

**Comment by Eddymorphling** [comment]
Hi, 
Thanks for that, removing it fixed it. Now I get this error when connecting to Google drive. Any suggestions on this one?
```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-75d3bec33370> in <module>
      2 
      3 # mount user's Google Drive to Google Colab.
----> 4 from google.colab import drive
      5 drive.mount('/content/gdrive')

ModuleNotFoundError: No module named 'google.colab
```

**Comment by guijacquemet** [comment]
Hi,
Here you can delete 
```
from google.colab import drive
drive.mount('/content/gdrive')
```
You do not need to mount your Gdrive when running locally. You will be able to access your local files directly.

**Comment by Eddymorphling** [comment]
Thanks! I see that when running locally it defaults to the C:| (boot drive) and not sure how to direct it to anoter local drive. What should I run to get another local drive mounted?

In the next section 2.1 when I try to install 3D-Unet, I get the following error:
```

File "<ipython-input-7-d0f2f0a837db>", line 12
    import elasticdeform
       ^
SyntaxError: from __future__ imports must occur at the beginning of the file
```

**Comment by Eddymorphling** [comment]
Great, that seems to have fixed it. I had to troubleshoot minor things in the rest of the Sections and everything works well now. Thanks for your help.
