### ISSUE TITLE
Unet 2D Missing convolution layers during oversampling steps

### ISSUE THREAD

**Issue by Natuy** [HenriquesLab/ZeroCostDL4Mic#92]
Hello,
I am currently using Unet-2D notebook and was wondering why the expansive path has only one 3x3 convolution at each step instead of the two shown in U-Net: Convolutional Networks for Biomedical Image Segmentation and implemented in zhixuhao's github (https://github.com/zhixuhao/unet)

**Comment by Romain-Laine** [comment]
Hi Natuy, 
Sorry for the delay, I just checked again and our notebook uses the same architecture as in the U-Net from Zhixuhao, we only add the option of choosing the number of pooling steps to decide the depth of the network. By default it is set to 2 but you can set it to `pooling_steps`: 4 to get the exact same architecture as above.

I hope this helps.
Best,

Romain

**Comment by Natuy** [comment]
Hi Romain,
Thanks for your answer,
I just checked again the models created from the notebook and from Zhixuhao's U-Net , I used `pooling steps`= 4 to have the same architecture, but there are some differences between the two.
Here are the summaries of the two models:
- [Model_Summary Notebook.txt](https://github.com/HenriquesLab/ZeroCostDL4Mic/files/6507567/Model_Summary.Notebook.txt)
- [Model_Summary Zhixuhao.txt](https://github.com/HenriquesLab/ZeroCostDL4Mic/files/6507568/Model_Summary.Zhixuhao.txt)

Just after the second merge layer (`concatenate_2`) there is only one Conv2D before upsampling, same thing again after `concatenate_3`

Cheers,
Natuy

**Comment by Romain-Laine** [comment]
Yes, you're right! It's our bad. We're working on a fix. It will be available soon!
Best,

Romain
