### ISSUE TITLE
Recomended resolution

### ISSUE THREAD

**Issue by jtyytim** [HenriquesLab/ZeroCostDL4Mic#93]
Hello,

Thanks for all the models provided here. I am just a little bit confused about the resolution of the images. For example, are there any suggestions on how to choose the resolution of the training images, for the U-Net model or stardist model?

Looking forward to your reply,
Thiem

**Comment by guijacquemet** [comment]
Hi,
Thanks for reaching out!
We typically train using 512x512 or 1024x1024 images. But both notebook can accommodate different image dimensions. 
StarDist does not like rectangular images, however. 
In the Unet notebook, you can patch your dataset to whatever image dimension you want to use for training. 
You can also use the Augmentor notebook to randomly crop images to your chosen dimensions.

I hope this helps

Cheers

Guillaume

**Comment by uschmidt83** [comment]
> StarDist does not like rectangular images, however.

StarDist can be trained just fine with rectangular patch sizes. However, maybe you're using data augmentation that flips the axes of the patch. Then you just make sure that the patch size fits in the smallest dimension.

**Comment by guijacquemet** [comment]
@uschmidt83 thanks, 
For some reason, StarDist training (in our notebook) always crashes during the last epoch when we use rectangular images.  Never managed to find the cause (with or without augmentation).

**Comment by uschmidt83** [comment]
We never observed this... must be something specific to your notebooks.

**Comment by guijacquemet** [comment]
As per my recommendation above :)

**Comment by jtyytim** [comment]
> Hi,
> Thanks for reaching out!
> We typically train using 512x512 or 1024x1024 images. But both notebook can accommodate different image dimensions.
> StarDist does not like rectangular images, however.
> In the Unet notebook, you can patch your dataset to whatever image dimension you want to use for training.
> You can also use the Augmentor notebook to randomly crop images to your chosen dimensions.
> 
> I hope this helps
> 
> Cheers
> 
> Guillaume

Thanks for your response. So if I understood well, both models (Unet and stardist) can work well with the square images (m x m). But the dimension of my image is 2048 x 2048. Might this dimension be too large for the neuron network (Unet for example)?

Thiem

**Comment by guijacquemet** [comment]
Yes, both notebook should work fine with 2048 x 2048. 
For the StarDist notebook, 2048x2048 may cause you trouble for training depending on which GPU you get allocated. You can decrease the patch size used during training to something smaller to avoid this issue. But I would recommend randomly cropping your images to 1024x1024 using the Augmentor notebook (you can augment the size of your training dataset at the same time).

In the Unet notebook, you should be able to load your 2048 x 2048 images with no issues. 
You will not be able to use 2048 x 2048 as a patch size hovewer. But you can easily generate patches directly in the notebook.

Cheers
Guillaume

**Comment by jtyytim** [comment]
In fact, on my GPU, the image 2048 x 2048 can't be loaded with Unet model (problem out of memory). So I set the input size as 512 x 512 or 1024 x 1024 by scaling down the image directly. But as you said, I think maybe the method Augmentor sounds better. I think I'll try this method next time.

Thanks!
Thiem

**Comment by guijacquemet** [comment]
In the Unet 2D notebook, by default, your images should be cropped into 512x512 patches. Did you change the size of the patches in the advanced settings?

**Comment by jtyytim** [comment]
In fact, I used another unet notebook, so that's why there are some differences...

**Comment by guijacquemet** [comment]
Fair enough, do not hesitate to reach out if you have troubles with ours!

Good luck with your analyses!

Cheers

Guillaume
