### ISSUE TITLE
Running N2V-3D locally does not use local GPU 

### ISSUE THREAD

**Issue by Eddymorphling** [HenriquesLab/ZeroCostDL4Mic#95]
Hello again kind folks,

I have some issues running the N2V-3D notebook using my local resources. I managed to create a local conda env with python 3.7.9 and installed the following simple requirement package list that I found in the notebook:

astropy==4.2.1
cloudpickle==1.3.0
csbdeep==0.5.2
cycler==0.10.0
dask==2.12.0
fpdf==1.7.2
imagecodecs==2021.4.28
imageio==2.4.1
ipykernel==5.5.4
joblib==1.0.1
kiwisolver==1.3.1
matplotlib==3.4.2
multiprocess==0.70.11.1
n2v==0.2.1
numexpr==2.7.3
numpy==1.19.5
pandas==1.1.5
psutil==5.8.0
py==1.10.0
q==2.6
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
sortedcontainers==2.3.0
tblib==1.7.0
tensorflow==1.15.0
tifffile==2021.4.8
toolz==0.11.1
tqdm==4.41.1
wget==3.2

The install went well and I managed to get the local GPU connected to the N2V notebook via Jupyter. Now when I run Section 1.1 (to check GPU access) its does not see the GPU and shows me this message: 
```
You do not have GPU access.
Did you change your runtime ?
If the runtime setting is correct then Google did not allocate a GPU for your session
Expect slow performance. To access GPU try reconnecting later
```
I checked my runtime and it uses the GPU. The rest of the notebook sections run fine but for training the datasets, the notebook uses the local CPU instead of the GPU because of the above issue and as a result this as very slow. 

I also had to delete `%tensorflow_version 1.x` in Section 1.1 as Jupyter is not compatible with this.. Any suggestions on how to fix this issue? Thanks again!

**Comment by guijacquemet** [comment]
Hi,
Thanks for reaching out!
Do you have CUDA installed?

**Comment by Eddymorphling** [comment]
Ah, I overlooked my CUDA version currently installed. I have been running 3DUnet locally  which runs on TF2.4 and requires CUDA 11.0. I forgot that N2V-3D runs on TF 1.15, so I had to install CUDA 10.0 on the local conda env:

```
conda install cudatoolkit=10.0
conda install cudnn=7.6
pip3 install tensorflow-gpu==1.15
```

The notebook works well now. Thank you for the help again. I will close this thread now.
