### ISSUE TITLE
ValueError in Augmentor section of CARE notebook 

### ISSUE THREAD

**Issue by mayeshh** [HenriquesLab/ZeroCostDL4Mic#96]
When I attempt to change the `Multiply_dataset_by = 2` to `Multiply_dataset_by = 10` I get a ValueError: Image has wrong mode. When I use the default value of 2 the notebook runs without issue. For a smaller dataset such as mine with 44 training images, I was, perhaps naively, attempting to increase the number of data in the Augmentor step. 

I have successfully run the UNet notebook on the same training dataset, so I know that the file names and file types follow the convention these notebooks require. 

<img width="1275" alt="augmentor_error" src="https://user-images.githubusercontent.com/26913051/118900837-c00c5080-b8c6-11eb-93e9-e8f7e4caeba7.png">

I am working on macOS Big Sur 11.2.3 with the Firefox browser.

**Comment by guijacquemet** [comment]
Hi @mayeshh 
Thanks for reaching out! 
I will fix this ASAP
Cheers
Guillaume

**Comment by guijacquemet** [comment]
Hi @mayeshh
This issue should now be fixed with the latest release!
Thanks again
Cheers
Guillaume
